@class NSUUID, NSObject, NSDate, RTFixedSizeQueue, NSString, RTDefaultsManager, RTDistanceCalculator, RTLearnedLocationManager, SMSessionStore, RTLocationManager;
@protocol OS_dispatch_queue;

@interface SMSessionMetricManager : NSObject <SMSessionManagerObserverProtocol>

@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTDistanceCalculator *distanceCalculator;
@property (retain, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (retain, nonatomic) SMSessionStore *sessionStore;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSUUID *currentDeviceIdentifier;
@property (retain, nonatomic) NSDate *sessionStartDate;
@property (retain, nonatomic) NSDate *sessionEndDate;
@property (retain, nonatomic) RTFixedSizeQueue *etaUpdateStateQueue;
@property (retain, nonatomic) RTFixedSizeQueue *etaUpdateSubmissionQueue;
@property (nonatomic) double closestTimeIntervalToExceedingETA;
@property (nonatomic) unsigned long long sessionType;
@property (nonatomic) double initialDestinationExpectedTravelTime;
@property (nonatomic) double previousCrowFliesETA;
@property (nonatomic) double previousMapsExpectedETA;
@property (nonatomic) double maxCrowFliesScaleFactor;
@property (nonatomic) double maxMapsETAScaleFactor;
@property (nonatomic) char didDestinationAnomalyTrigger;
@property (nonatomic) char noProgressTriggered;
@property (nonatomic) char routeDeviationTriggered;
@property (nonatomic) char didArriveSafely;
@property (nonatomic) char sosTriggered;
@property (nonatomic) char userEndedSession;
@property (nonatomic) char didTriggerOccur;
@property (nonatomic) double initialDistance;
@property (nonatomic) unsigned long long sessionDestinationType;
@property (nonatomic) double ratioOfFirstAnomalyDistanceToTotalDistance;
@property (nonatomic) double mostRecentLocationDistance;
@property (nonatomic) double originalNominalTravelTime;
@property (nonatomic) unsigned long long firstAnomalyTriggerCategoryEnum;
@property (nonatomic) int numExtensions;
@property (nonatomic) unsigned long long originatingLocationTypeEnum;
@property (nonatomic) unsigned long long numAnomalyPrompt;
@property (nonatomic) unsigned long long numAnomalyPromptDuringHysteresis;
@property (nonatomic) unsigned long long numHandoff;
@property (nonatomic) unsigned long long numLPMSeparation;
@property (nonatomic) unsigned long long numTakeover;
@property (nonatomic) unsigned long long numUnsupportedDeviceSeparation;
@property (nonatomic) unsigned long long numUserDisabledConnectivity;
@property (nonatomic) char didWorkoutEnd;
@property (nonatomic) char didWorkoutPause;
@property (nonatomic) char isWorkoutAlwaysOn;
@property (nonatomic) unsigned long long modeOfTransportation;
@property (nonatomic) unsigned long long numRecipients;
@property (copy, nonatomic) NSString *workoutActivityTypeString;
@property (nonatomic) char didHandoffOccur;
@property (nonatomic) char wasActiveAtStart;
@property (nonatomic) char wasActiveAtEnd;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void).cxx_destruct;
- (void)_reset;
- (void)_setup;
- (void)_gatherSessionDestinationStats:(id)a0;
- (void)onWorkoutPaused;
- (void)onLPMSeparation;
- (id)_createDestinationMetricDictionary;
- (id)_createInitiatorPerSessionDetailsMetricDictionary;
- (char)_isCellularActivated;
- (char)_isStandalone;
- (void)_onDailyMetricsNotification:(id)a0;
- (void)_submitTerminationMetricsWithSuccess:(char)a0 reason:(unsigned long long)a1 error:(id)a2;
- (void)_updateETASubmissionStates;
- (void)cacheMostRecentLocationDistance:(double)a0;
- (id)collectDestinationSessionMetrics;
- (id)collectInitiatorPerSessionMetrics;
- (id)getLocationsForInterval:(id)a0 nearBoundingLocation:(id)a1;
- (id)getRTLocationOfInterestForCLLocation:(id)a0;
- (id)initWithDefaultsManager:(id)a0 learnedLocationManager:(id)a1 sessionStore:(id)a2 locationManager:(id)a3 currentDeviceIdentifier:(id)a4;
- (void)initialDistance:(double)a0;
- (void)onBecomingActiveDevice:(id)a0;
- (void)onBecomingNonActiveDevice:(id)a0;
- (void)onCrowFliesETAUpdate:(double)a0;
- (void)onDailyMetricsNotification:(id)a0;
- (void)onDeclareAnomalyForTriggerCategory:(unsigned long long)a0;
- (void)onMapsETAUpdate:(double)a0;
- (void)onSessionChangedWithConfiguration:(id)a0;
- (void)onSessionEndedForActiveDevice:(char)a0;
- (void)onSessionStartedWithState:(id)a0;
- (void)onSessionTerminationResult:(char)a0 reason:(unsigned long long)a1 error:(id)a2;
- (void)onShouldUpdateETAUpperBoundWithETAUpdateState:(id)a0;
- (void)onUnsupportedDeviceSeparation;
- (void)onUserActionWithRemoteCommand:(long long)a0 remoteCommandType:(long long)a1 error:(long long)a2 errorDomain:(id)a3;
- (void)onUserDisabledConnectivity;
- (void)onWorkoutEnded;
- (void)setup;
- (void)submitMetrics;
- (void)updateClosestTimeIntervalToExceedingETAWithTimeInterval:(double)a0;

@end
