@class SMHandoffMetricsManager, RTDefaultsManager, RTContactsManager, RTTimer, RTBiomeManager, RTLocationManager, SMScreenLockMonitor, RTAuthorizationManager, RTWatchWristStateManager, NSString, SMSessionManagerState, SMAnomalyAlertManager, RTXPCTimerAlarm, SMMessagingService, RTTimerManager, SMSessionStore, RTPlatform, SMSessionManagerStatus, SMActiveSessionDetails, SMSessionMetricManager, NSObject, SMAppDeletionManager, RTStarkManager, CLLocation, SMCarPlayAlertManager, RTLocationAwarenessManager, SMLocalSessionState, NSHashTable;
@protocol OS_dispatch_queue, SMActiveSessionZoneProtocol;

@interface SMSessionManager : NSObject <IDSServiceDelegate, SMActiveSessionZoneObserverProtocol, SMInitiatorSessionConfigurationProtocol, SMInitiatorGroupChatProtocol, SMSessionManagerMonitorProtocol, SMSessionManagerCacheProtocol, SMSessionManagerRegistrationProtocol, SMUserNotificationProtocol, SMAppDeletionObserverProtocol> {
    SMSessionManagerState *_state;
    SMLocalSessionState *_localState;
    SMHandoffMetricsManager *_handoffMetrics;
}

@property (retain, nonatomic) SMActiveSessionDetails *activeSessionDetails;
@property (retain, nonatomic) RTTimer *activeSessionDetailsTimeoutTimer;
@property (nonatomic) double activeSessionDetailsFetchTimeout;
@property (retain, nonatomic) RTBiomeManager *biomeManager;
@property (nonatomic) double cacheReleaseMaxDuration;
@property (nonatomic) long long cachedInitiatorEligibilty;
@property (retain, nonatomic) RTTimer *handoffRetryTimer;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *initiatorEligibilityQueue;
@property (nonatomic) double magnetBreakTimerInterval;
@property (nonatomic) double sendSessionEndMessageTimeout;
@property (retain, nonatomic) RTTimerManager *timerManager;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) id<SMActiveSessionZoneProtocol> activeSessionDetailsDelegate;
@property (retain, nonatomic) RTXPCTimerAlarm *checkInXPCTimerAlarm;
@property (retain, nonatomic) RTXPCTimerAlarm *magnetBreakTimer;
@property (retain, nonatomic) RTXPCTimerAlarm *cacheReleaseXPCTimerAlarm;
@property (retain, nonatomic) RTXPCTimerAlarm *endAwarenessBeforeUnlockXPCTimerAlarm;
@property (retain, nonatomic) RTXPCTimerAlarm *endCarouselSessionXPCTimerAlarm;
@property (retain, nonatomic) SMScreenLockMonitor *screenLockMonitor;
@property (retain, nonatomic) NSHashTable *observers;
@property (retain, nonatomic) RTContactsManager *contactsManager;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) RTPlatform *platform;
@property (retain, nonatomic) SMSessionMetricManager *sessionMetricManager;
@property (retain, nonatomic) SMSessionStore *sessionStore;
@property (nonatomic) unsigned long long sessionStoreAvailability;
@property (nonatomic) unsigned long long handoffRebootReconciliationState;
@property (retain, nonatomic) RTLocationAwarenessManager *locationAwarenessManager;
@property (retain, nonatomic) SMMessagingService *messagingService;
@property (retain, nonatomic) RTStarkManager *starkManager;
@property (retain, nonatomic) SMCarPlayAlertManager *carPlayAlertManager;
@property (retain, nonatomic) SMAnomalyAlertManager *anomalyAlertManager;
@property (retain, nonatomic) CLLocation *lastLocation;
@property (retain, nonatomic) SMSessionManagerStatus *status;
@property (nonatomic) BOOL statusStored;
@property (nonatomic) BOOL statusStoreInProgress;
@property (nonatomic) BOOL statusUpdatePending;
@property (readonly, nonatomic) RTAuthorizationManager *authorizationManager;
@property (retain, nonatomic) RTWatchWristStateManager *wristStateManager;
@property (nonatomic) unsigned long long wristState;
@property (retain, nonatomic) SMAppDeletionManager *appDeletionManager;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)SessionHandoffRebootReconciliationStateToString:(unsigned long long)a0;
+ (id)SessionHandoffRebootReconciliationDecisionToString:(unsigned long long)a0;

- (void).cxx_destruct;
- (id)state;
- (void)removeObserver:(id)a0;
- (void)addObserver:(id)a0;
- (void)_removeObserver:(id)a0;
- (void)_registerForNotifications;
- (void)_unregisterForNotifications;
- (BOOL)_isActiveDevice;
- (void)_onDeletedConversation:(id)a0 handler:(id /* block */)a1;
- (void)onWristStateChangeNotification:(id)a0;
- (void)_performStateSyncOriginatedTransitionTo:(id)a0 transitionType:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)_terminateSessionWithSessionID:(id)a0;
- (void)promptDirectTriggerWithContext:(id)a0;
- (void)_addObserver:(id)a0;
- (void)_backdoorSetState:(id)a0;
- (void)_becomeActiveDeviceForSessionWithHandler:(id /* block */)a0;
- (void)_bootstrapHysteresisState;
- (void)_bootstrapToState;
- (BOOL)_canDeviceModifyState;
- (void)_cancelMagnetBreakTimerAndExitHysteresisState;
- (id)_checkDefaultsForCacheReleaseDateWithState:(id)a0;
- (void)_checkIfHandoffCriteriaSatisfiedForState:(id)a0 handler:(id /* block */)a1;
- (void)_checkInitiatorEligibilityWithIsHandoff:(BOOL)a0 completion:(id /* block */)a1;
- (void)_clearActiveSessionDetailsTimeoutTimer;
- (void)_clearHysteresisState;
- (void)_endCarouselSession;
- (void)_endRemoteSessionForSessionID:(id)a0 reason:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)_endSessionForSessionID:(id)a0 reason:(unsigned long long)a1 handler:(id /* block */)a2;
- (unsigned long long)_evaluateHandoffRebootReconciliationState:(id)a0;
- (unsigned long long)_getCurrentHysteresisStateType;
- (unsigned long long)_getEndSessionStateWithReason:(unsigned long long)a0;
- (id)_getMostRecentSessionState;
- (void)_handleMagnetBreak;
- (void)_handleMagnetConnect:(long long)a0;
- (void)_handleTransitionToStateAfterBootstrap:(id)a0 isActiveDevice:(BOOL)a1;
- (void)_handoffSessionForSessionID:(id)a0 retryCount:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)_initializeSessionWithSessionID:(id)a0 conversation:(id)a1 handler:(id /* block */)a2;
- (void)_initializeUserDisabledConnectivityWatchDefault;
- (void)_invalidateScreenLockMonitor;
- (void)_invalidateSessionManagerXPCTimerAlarms;
- (void)_invalidateTimer:(id)a0;
- (BOOL)_isActiveSessionDetailsFetchAttemptFailed;
- (BOOL)_isActiveSessionDetailsFetchedFromCloudKitSinceBoot;
- (BOOL)_isActiveSessionDetailsLocalRecordExpired;
- (BOOL)_isActiveSessionDetailsOutOfSync;
- (BOOL)_isEffectivePairedDeviceNearby;
- (BOOL)_isEffectivePairedDeviceSameAsActiveDeviceWithIdentifier:(id)a0;
- (BOOL)_isEligibleOutOfOrderEndSessionMessage:(id)a0 currentSessionManagerState:(id)a1;
- (BOOL)_isEligibleOutOfOrderStateSyncMessage:(id)a0 currentSessionManagerState:(id)a1;
- (BOOL)_isEligibleRecentHandoffMessage:(id)a0 currentSessionManagerState:(id)a1;
- (BOOL)_isEligibleToBecomeNonActiveDeviceForHandoffStateSyncMessage:(id)a0;
- (BOOL)_isEligibleToProcessSessionTypeKeyReleaseMessage:(id)a0;
- (BOOL)_isEligibleToSendStateUpdateReqMessageAfterBootstrap:(id)a0 isActiveDevice:(BOOL)a1;
- (BOOL)_isEligibleTransitionFromStateSyncMessage:(id)a0 currentSessionManagerState:(id)a1;
- (BOOL)_isHandoffAllowedInSessionState:(unsigned long long)a0;
- (BOOL)_isLocalStateInSyncWithActiveSessionDetails:(id)a0 deviceSessionManagerState:(id)a1;
- (BOOL)_isMultiDeviceSetupForLocalState:(id)a0;
- (BOOL)_isRemoteSessionEndForPreviousState:(id)a0 nextState:(id)a1;
- (BOOL)_isSessionManagerStateStaleToHandoff;
- (BOOL)_isWatchDeviceEligibleForHandoff;
- (BOOL)_isWatchInLowPowerMode;
- (BOOL)_isWatchOnWristEligibilityCriteriaSatisfied;
- (void)_modifyRemoteSessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)_modifySessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)_notifyObserversForBecomingActiveDevice;
- (void)_notifyObserversForBecomingNonActiveDevice;
- (void)_notifyObserversForConfigurationChange;
- (void)_notifyObserversForLocalStateChange;
- (void)_notifyObserversForSecondarySOSTrigger;
- (void)_notifyObserversForSessionEndForActiveDevice:(BOOL)a0;
- (void)_notifyObserversForSessionResume;
- (void)_notifyObserversForStart;
- (void)_notifyObserversForStateChangeWithTransitionType:(unsigned long long)a0;
- (void)_notifyObserversForTriggerResponse;
- (void)_onActiveSessionDetailsFetchAttemptFromCKCompleted:(id)a0 success:(BOOL)a1 error:(id)a2;
- (void)_onActiveSessionDetailsTimeoutTimerExpiry;
- (void)_onDeletedMessage:(id)a0 handler:(id /* block */)a1;
- (void)_onHandoffRetryTimerExpiry;
- (void)_onMessagesAppUninstalled;
- (void)_onScheduledSendForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)_onSessionStoreNotification:(id)a0;
- (void)_onWristStateChangeNotification:(id)a0;
- (void)_overrideMagnetBreakIntervalIfNeeded;
- (void)_performActionsAndUpdatesUponStateTransitionWithType:(unsigned long long)a0;
- (BOOL)_performStateTransitionTo:(id)a0 transitionType:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)_playCacheReleaseAndUpdatingSound;
- (void)_postAnomalyAlert;
- (void)_postCacheReleaseAndUpdatingWithTargetDate:(id)a0;
- (void)_postEndAwarenessLiveActivity;
- (void)_processNearbyEffectivePairedDeviceChanged:(id)a0;
- (unsigned long long)_reconciliationDecisionForState:(id)a0 isActiveDevice:(BOOL)a1;
- (unsigned long long)_reconciliationForDecisionForCKFetchCompleted:(id)a0;
- (void)_reconnectCarouselSessionAndSetupTimer;
- (void)_registerForConnectivityNotifications;
- (void)_resetInitializationWithHandler:(id /* block */)a0;
- (void)_resetPendingSendSessionEndMessage;
- (void)_respondToTriggerPromptForSessionID:(id)a0 response:(long long)a1 handler:(id /* block */)a2;
- (void)_respondToTriggerPromptWithRemoteControlSessionID:(id)a0 response:(long long)a1 handler:(id /* block */)a2;
- (void)_sessionInitializedWithAllowReadToken:(id)a0 safetyCacheKey:(id)a1 scheduledSendMessageGUID:(id)a2 completionHandler:(id /* block */)a3;
- (BOOL)_sessionSupportsHandoff;
- (void)_setHysteresisState:(unsigned long long)a0;
- (void)_setPendingSendSessionEndMessageWithReason:(unsigned long long)a0 associatedGUID:(id)a1;
- (void)_setUpCacheReleaseTimer;
- (void)_setUpEndCarouselSessionTimer;
- (void)_setupAnomalyAlerts;
- (void)_setupAnomalyAlertsOnResume;
- (void)_setupTimerAndLockMonitorForEndAwareness;
- (void)_setupTimerForAnomaly;
- (void)_setupWarningStates;
- (void)_setupWithObservers:(id)a0;
- (BOOL)_shouldAlertNowWithTargetAlertDate:(id)a0;
- (BOOL)_shouldExitHysteresisState:(unsigned long long)a0 nearbyDeviceConnected:(BOOL)a1;
- (BOOL)_shouldRetryForHandoffError:(id)a0 retryCount:(unsigned long long)a1;
- (void)_startActiveSessionDetailsTimerWithLatency:(double)a0;
- (void)_startCarouselSession;
- (void)_startHandoffRetryTimerWithLatency:(double)a0 sessionID:(id)a1 retryCount:(unsigned long long)a2 handoffCompletion:(id /* block */)a3;
- (id)_stateTransitionDecisionToState:(id)a0 transitionType:(unsigned long long)a1;
- (BOOL)_stateValidForSendSessionEndMessageRetry:(id)a0;
- (BOOL)_stateValidForSendingEndSessionMessage:(id)a0;
- (BOOL)_stateValidForSessionResume:(id)a0;
- (void)_stopPlayingCacheReleaseAndUpdatingSound;
- (void)_teardownAnomalyAlerts;
- (void)_transitionToState:(id)a0 transitionType:(unsigned long long)a1;
- (void)_updateActivityWithState:(id)a0;
- (void)_updateActivityWithState:(id)a0 shouldNotify:(BOOL)a1;
- (void)_updateConnectivityAndStatusSignalsObserverUponStateTransition;
- (id)_updateDestinationForRoundTripSessionConfiguration:(id)a0;
- (void)_updateLastLocationWithLocations:(id)a0;
- (void)_updateLocationObserverUponStateTransition;
- (void)_updateReceiverWithEstimatedEndDate:(id)a0 coarseEstimatedEndDate:(id)a1 sessionID:(id)a2;
- (void)_updateReceiverWithLowPowerModeWarningStateUpdate:(long long)a0 sessionID:(id)a1;
- (void)_updateSessionWithConversation:(id)a0 sosReceivers:(id)a1 handler:(id /* block */)a2;
- (void)_updateTimersUponStateTransition:(unsigned long long)a0;
- (void)_updateUnsupportedSeparationStateIfNeededWithNotify:(BOOL)a0;
- (void)_updateUnsupportedSeparationStateWithNewState:(BOOL)a0 shouldNotify:(BOOL)a1;
- (void)_updateUserDisabledConnectivityStatus;
- (void)bootstrapToState;
- (void)cancelInitializationForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)cancelInitializationWithHandler:(id /* block */)a0;
- (id)checkSessionIDAndCanDeviceModifyStateWithSelector:(SEL)a0 sessionID:(id)a1;
- (id)checkSessionIDCanDeviceModifyStateAndSessionStateWithSelector:(SEL)a0 sessionID:(id)a1 validSessionStates:(id)a2;
- (id)checkSessionIDWithSelector:(SEL)a0 sessionID:(id)a1;
- (id)checkSessionStateWithSelector:(SEL)a0 validSessionStates:(id)a1;
- (void)endSessionForSessionID:(id)a0 reason:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)fetchCurrentLocalSessionStateWithHandler:(id /* block */)a0;
- (void)fetchCurrentSessionStateWithHandler:(id /* block */)a0;
- (void)fetchSOSReceiversWithCompletion:(id /* block */)a0;
- (void)handoffSessionForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)iMessageGroupDisplayNameChangedFor:(id)a0;
- (void)iMessageGroupMembershipChangedFor:(id)a0;
- (void)iMessageGroupPhotoChangedFor:(id)a0;
- (id)initWithAuthorizationManager:(id)a0 biomeManager:(id)a1 contactsManager:(id)a2 defaultsManager:(id)a3 locationManager:(id)a4 platform:(id)a5 sessionMetricManager:(id)a6 sessionStore:(id)a7 messagingService:(id)a8 carPlayAlertManager:(id)a9 observers:(id)a10 activeSessionDetailsDelegate:(id)a11 wristStateManager:(id)a12 appDeletionManager:(id)a13;
- (void)initializeSessionWithConversation:(id)a0 handler:(id /* block */)a1;
- (void)initializeSessionWithSessionID:(id)a0 conversation:(id)a1 handler:(id /* block */)a2;
- (void)kickedFromIMessageGroupWith:(id)a0;
- (id)localState;
- (void)logSignPostForStateTransition:(id)a0;
- (void)modifySessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)onActiveSessionDetailsFetchAttemptFromCKCompleted:(id)a0 success:(BOOL)a1 error:(id)a2;
- (void)onDataSettingsChangedNotification;
- (void)onDeletedConversation:(id)a0 handler:(id /* block */)a1;
- (void)onDeletedMessage:(id)a0 handler:(id /* block */)a1;
- (void)onLocationNotification:(id)a0;
- (void)onMessagesAppUninstalled;
- (void)onScheduledSendForSessionID:(id)a0;
- (void)onScheduledSendMessageCanceledForSessionID:(id)a0 guid:(id)a1;
- (void)onScheduledSendMessageScheduledForSessionID:(id)a0 guid:(id)a1 date:(id)a2;
- (void)onSessionStartMessageSendResultWithMessage:(id)a0 messageGUID:(id)a1 success:(BOOL)a2 error:(id)a3;
- (void)onSessionStoreNotification:(id)a0;
- (void)overrideMagnetBreakIntervalIfNeeded;
- (void)processEmergencyContactsNotifiedMessage:(id)a0;
- (void)processModifySessionConfigurationRemoteControlMessage:(id)a0;
- (void)processNearbyEffectivePairedDeviceChanged:(id)a0;
- (void)processResponseToTriggerPromptRemoteControlMessage:(id)a0;
- (void)processSessionEndRemoteControlMessage:(id)a0;
- (void)processSessionTypeKeyRelease:(id)a0;
- (void)processStateSyncMessage:(id)a0;
- (void)processStateSyncUpdateReqMessage:(id)a0;
- (void)promptDestinationAnomalyVerificationWithContext:(id)a0;
- (void)promptDestinationAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptEstimatedEndDateUpdateWithContext:(id)a0;
- (void)promptRoundTripAnomalyVerificationWithContext:(id)a0;
- (void)promptRoundTripAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptSafeArrivalWithContext:(id)a0;
- (void)promptSafeArrivalWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptTimerEndedVerificationWithContext:(id)a0;
- (void)promptTimerEndedVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptWorkoutAnomalyVerificationWithContext:(id)a0;
- (void)promptWorkoutAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptWorkoutSessionEndVerificationWithContext:(id)a0 handlers:(id /* block */)a1;
- (void)respondToNotificationWithIdentifier:(id)a0 sessionIdentifier:(id)a1 actionIdentifier:(id)a2 handler:(id /* block */)a3;
- (void)respondToTriggerPromptForSessionID:(id)a0 response:(long long)a1 handler:(id /* block */)a2;
- (void)sendSafetyCacheForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)sendSessionEndMessageWithReason:(unsigned long long)a0 associatedGUID:(id)a1 state:(id)a2;
- (void)sessionInitializedWithSessionID:(id)a0 allowReadToken:(id)a1 safetyCacheKey:(id)a2 scheduledSendMessageGUID:(id)a3 completionHandler:(id /* block */)a4;
- (void)setupWarningStates;
- (void)setupWithObservers:(id)a0;
- (void)startSessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)storeManagerStatusInStore:(unsigned long long)a0 completion:(id /* block */)a1;
- (void)terminateSessionWithSessionID:(id)a0;
- (void)updateManagerStatusInStoreWithCompletion:(id /* block */)a0;
- (void)updateUserWithContext:(id)a0;
- (void)updateUserWithTriggerContext:(id)a0;

@end
