@class NFAWDVersionInfo, NSObject, NSCountedSet, NSData, AWDServerConnection, NSUserDefaults;
@protocol OS_dispatch_queue;

@interface NFAWDLogger : NSObject {
    unsigned int _hwType;
    AWDServerConnection *_awdServer;
    unsigned long long _previousTransactionState;
    NSData *_uuid;
    unsigned long long _uuidRefTimestamp;
    NSUserDefaults *_userDefault;
    NSData *_tsmUuid;
    unsigned long long _tsmUuidRefTimestamp;
    NSData *_rmpUuid;
    unsigned long long _rmpUuidRefTimestamp;
    NFAWDVersionInfo *_versionInfo;
    NSData *_deviceExceptionUuid;
    unsigned long long _previousVASTransactionState;
    NSObject<OS_dispatch_queue> *_awdSubmissionQueue;
    unsigned long long _middlewareExceptionCount;
    unsigned long long _previousCardIngestionSessionState;
    unsigned long long _previousExpressTransactionState;
    NSData *_restrictedModeID;
    NSCountedSet *_expressTransactionInfo;
    unsigned int _terminalType;
}

@property (copy) NSData *activeAID;

+ (id)sharedAWDLogger;

- (id)init;
- (void).cxx_destruct;
- (unsigned long long)getTimestamp;
- (unsigned int)getBatteryPercent;
- (void)_registerNFCVersionMetric;
- (void)_registerGeneralStatisticMetric;
- (void)_registerDeviceExceptionStatisticMetric;
- (void)_registerExpressTransactionStatisticMetric;
- (void)_registerLPCDStatisticMetric;
- (void)enableQueryMetricsListener;
- (void)_updateStats:(id)a0 reset:(BOOL)a1;
- (void)updateStats:(id)a0 reset:(BOOL)a1;
- (BOOL)incrementMiddlewareExceptionCountWithReset:(BOOL)a0;
- (void)_postAWDEvent:(id)a0 withTimestamp:(unsigned long long)a1;
- (void)postAWDEvent:(id)a0;
- (id)generateUUID;
- (void)postAWDFieldEventWithFieldOn:(BOOL)a0 withTechnology:(unsigned int)a1;
- (void)postAWDCRSAuthInitEventWithStatus:(unsigned int)a0;
- (void)postAWDCRSAuthWithStatus:(unsigned int)a0 withMethod:(unsigned int)a1;
- (void)postAWDCRSAuthECommerceWithParameters:(id)a0;
- (void)postAWDCRSDeAuthWithStatus:(unsigned int)a0;
- (void)postAWDSESelectEventWithAID:(id)a0;
- (void)postAWDCRSActivationTimerExpiredWithVersion:(unsigned int)a0 withStatus:(unsigned int)a1;
- (void)postAWDExpressTransactionEvent:(id)a0;
- (void)postAWDCardIngestionSessionStateChange:(id)a0;
- (void)postAWDCardIngestionReaderStateChangeWithType:(unsigned int)a0 errorCode:(unsigned int)a1;
- (void)_postAWDHCIStartOfTransactionEventWithParametersLegacy:(id)a0 currentTimestamp:(unsigned long long)a1;
- (void)postAWDHCIStartOfTransactionEventWithParameters:(id)a0;
- (void)_postAWDHCIEndOfTransactionEventWithParametersLegacy:(id)a0 currentTimestamp:(unsigned long long)a1;
- (void)postAWDHCIEndOfTransactionEventWithParameters:(id)a0;
- (void)postAWDFelicaHCIEndOfTransactionEventWithParameters:(id)a0;
- (void)postAWDTransactionLastRAPDU;
- (void)postAWDTransactionEndOfOperation;
- (void)postAWDAPNReceived;
- (void)postAWDSERemovedEvent:(id)a0;
- (void)postAWDRestrictedModeFromContactlessMode:(BOOL)a0;
- (void)postAWDSERestrictedModeEntered:(id)a0;
- (void)postAWDSERestrictedModeExited;
- (void)postAWDTSMStartWithParameters:(id)a0;
- (void)postAWDTSMEndWithParameters:(id)a0;
- (void)postAWDTSMEndOfSession;
- (void)postAWDTSMConnectivityException:(unsigned int)a0;
- (void)postAWDVersionInfo:(id)a0;
- (void)postAWDSEMemoryInfo:(id)a0;
- (void)postAWDVASSelectOSE:(id)a0;
- (void)postAWDVASGetData:(id)a0;
- (void)postAWDVASTransactionException:(unsigned int)a0 withSWStatus:(unsigned int)a1;
- (void)postAWDReaderModeExceptionForType:(unsigned int)a0 tagType:(unsigned int)a1 rfFrameInterface:(BOOL)a2 withErrorCode:(unsigned int)a3;
- (void)postAWDPLLUnlockEvent;
- (void)postAWDMiddlewareException:(unsigned int)a0 mwVersion:(unsigned int)a1 errorType:(unsigned int)a2 errorCode:(unsigned int)a3 breadcrumb:(unsigned long long)a4 checkMaxExceptionCounter:(BOOL)a5;
- (void)_resetAWDLoadStackExceptionCount;
- (void)_postAWDHardwareExceptionEventWithAssertionCounter:(unsigned int)a0 hardwareType:(unsigned int)a1 wdogDump:(unsigned int *)a2 hwFltDump:(unsigned int *)a3;
- (void)postAWDRadioIsEnabledStatistic:(BOOL)a0 changed:(BOOL)a1;
- (void)postAWDReaderSessionEventWithParameters:(id)a0;
- (void)_postReaderSessionStartedWithType:(unsigned int)a0 uuid:(id)a1;
- (void)_postReaderSessionEndedWithType:(unsigned int)a0 uuid:(id)a1 startTime:(id)a2 params:(id)a3;
- (void)_postReaderSessionBurnoutTimerInvokedWithType:(unsigned int)a0 uuid:(id)a1 startTime:(id)a2 params:(id)a3;
- (void)_postReaderSessionPollingStartedWithType:(unsigned int)a0 uuid:(id)a1 startTime:(id)a2 params:(id)a3;
- (void)_postReaderSessionTagFoundWithType:(unsigned int)a0 uuid:(id)a1 startTime:(id)a2 params:(id)a3;
- (void)_postReaderSessionTagReadWithType:(unsigned int)a0 uuid:(id)a1 startTime:(id)a2 params:(id)a3;
- (void)postReaderModeIngestionSessionStarted:(id)a0;
- (void)postReaderModeIngestionSessionEnded:(id)a0 startTime:(unsigned long long)a1;
- (void)postAWDPeerPaymentEnrollmentWithParameters:(id)a0;
- (void)postAWDPeerPaymentRequestWithParameters:(id)a0;
- (void)postAWDPurpleTrustOperationWithParameters:(id)a0;
- (void)postAWDHCIActivityTimeout:(id)a0;
- (void)postAWDHCEStartEvent:(id)a0;
- (void)postAWDHCEStateChangeEvent:(unsigned int)a0;
- (void)postAWDHCEEndEvent;
- (void)postAWDFelicaStateChangeEvent:(id)a0;
- (void)postAWDMobileSoftwareUpdateException:(unsigned int)a0;
- (void)getAWDUniversityCode:(id)a0 universityCodes:(unsigned int *)a1;

@end
