@class NSMutableDictionary, NSDictionary, NSObject, MAAutoAssetControlStatistics, MAAutoAssetUpdatePolicy, NSMutableArray, SUCoreFSM, NSString, SUCoreConnectServerPolicy, SUCoreLog, SUCoreConnectServer, MADAutoAssetPersisted, MAAutoAssetSelector, NSArray, NSTimer, MADAutoAssetJob;
@protocol OS_dispatch_queue;

@interface MADAutoAssetControlManager : NSObject <SUCoreFSMDelegate, SUCoreConnectServerDelegate>

@property (readonly, retain, nonatomic) SUCoreLog *logger;
@property (readonly, retain, nonatomic) NSObject<OS_dispatch_queue> *sharedDispatchQueue;
@property (retain, nonatomic) SUCoreConnectServerPolicy *serverConnectionPolicy;
@property (retain, nonatomic) SUCoreConnectServer *connectionServer;
@property (readonly, retain, nonatomic) NSDictionary *stateTable;
@property (retain, nonatomic) NSString *latestSafeSummary;
@property (retain, nonatomic) SUCoreFSM *autoControlManagerFSM;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedActiveJobs;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedKnownDescriptors;
@property (retain, nonatomic) NSMutableDictionary *currentStatusBySelector;
@property (retain, nonatomic) NSMutableDictionary *currentJobsBySelector;
@property (retain, nonatomic) NSMutableDictionary *currentJobsByUUID;
@property (nonatomic) BOOL stagerResumed;
@property (retain, nonatomic) MADAutoAssetJob *stagerCurrentJob;
@property (retain, nonatomic) MADAutoAssetJob *stagerBondedToAutoJob;
@property (retain, nonatomic) NSString *stagerCurrentJobUUID;
@property (retain, nonatomic) MAAutoAssetSelector *stagerDownloadingSelector;
@property (retain, nonatomic) NSMutableDictionary *lookupGrantsByAssetType;
@property (retain, nonatomic) NSMutableDictionary *downloadedDescriptorsBySelector;
@property (retain, nonatomic) NSMutableDictionary *descriptorsByAssetType;
@property (readonly, retain, nonatomic) MAAutoAssetUpdatePolicy *defaultUpdatePolicy;
@property (retain, nonatomic) NSMutableDictionary *timedOperations;
@property (retain, nonatomic) NSMutableDictionary *clientRequestsBeingTracked;
@property (retain, nonatomic) NSMutableArray *clientRequestsAwaitingSync;
@property (retain, nonatomic) NSMutableArray *clientRequestsAwaitingFirstUnlock;
@property (retain, nonatomic) NSMutableArray *downloadManagerEventsAwaitingResumed;
@property (retain, nonatomic) NSArray *downloadManagerInFlightTasks;
@property (retain, nonatomic) NSTimer *beyondFirstUnlockPollTimer;
@property (retain, nonatomic) NSTimer *awaitDownloadManagerSyncTimer;
@property (nonatomic) BOOL receivedDownloadManagerSync;
@property (nonatomic) BOOL maintainingActiveJobStatus;
@property (retain, nonatomic) NSMutableDictionary *activelyEliminatingSelectors;
@property (retain, nonatomic) MAAutoAssetControlStatistics *statistics;
@property (nonatomic) double statisticsNextMaintenanceReport;
@property (nonatomic) BOOL preferenceScheduledAlwaysNonDiscretionary;
@property (nonatomic) BOOL preferenceScheduledBackupTriggersDisabled;
@property (nonatomic) long long preferenceConnectorInitialWaitSecs;
@property (retain, nonatomic) NSArray *preferenceConnectorBackoffRetryTimes;
@property (nonatomic) long long preferenceConnectorWaitBeforeRetrySecs;
@property (nonatomic) BOOL preferenceAutoAssetObserverIgnoreNetworkStatus;
@property (retain, nonatomic) NSString *preferenceAsIfBootedOSIsOSVersion;
@property (retain, nonatomic) NSString *preferenceAsIfBootedOSIsBuildVersion;
@property (nonatomic) BOOL preferenceAlwaysPromoteStagedAssets;
@property (nonatomic) long long preferenceActivityIntervalSecs;
@property (nonatomic) long long preferencePushActivityIntervalSecs;
@property (nonatomic) long long preferenceBeforeFirstPollSecs;
@property (nonatomic) BOOL simulateOperationRequested;
@property (retain, nonatomic) NSMutableDictionary *simulateOperationsBySelector;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)assetRepresentationName:(long long)a0;
+ (id)createSeverMessageWithName:(id)a0 sender:(id)a1 clientID:(id)a2 response:(id)a3 error:(id)a4;
+ (id)migrateMismatchedPersistedStateVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (void)autoAssetStagerJobDownloadProgress:(id)a0 withProgressError:(id)a1;
+ (void)autoAssetStagerJobDownloadDone:(id)a0 withDownloadError:(id)a1;
+ (id)_getAutoControlManagerStateTable;
+ (id)autoControlManager;
+ (void)lockerResumed;
+ (void)stagerResumed:(id)a0;
+ (void)schedulerResumed;
+ (void)downloadManagerStateSyncSkipped;
+ (void)downloadManagerStateSyncDetermined:(id)a0;
+ (void)catalogDownloadJobFinished:(id)a0 withCatalog:(id)a1 error:(id)a2;
+ (void)assetConfigJobFinished:(id)a0 error:(id)a1;
+ (void)assetDownloadJob:(id)a0 progressReport:(id)a1;
+ (void)assetDownloadJobFinished:(id)a0 error:(id)a1;
+ (void)autoAssetJobObtainLookupGrant:(id)a0 forAutoAssetUUID:(id)a1 fromAutoAssetJob:(id)a2;
+ (void)autoAssetJobReleaseLookupGrant:(id)a0 forAutoAssetUUID:(id)a1 fromAutoAssetJob:(id)a2;
+ (void)autoAssetJobReadyToDownload:(id)a0 withAutoAssetUUID:(id)a1 fromAutoAssetJob:(id)a2 withOriginalSelector:(id)a3 downloadingDescriptor:(id)a4 baseForPatchDescriptor:(id)a5;
+ (void)autoAssetJobIssueProgress:(id)a0 forAutoAssetSelector:(id)a1 withAutoAssetUUID:(id)a2 withJobInformation:(id)a3 withResponseError:(id)a4;
+ (void)autoAssetJobIssueReply:(id)a0 forAutoAssetSelector:(id)a1 withAutoAssetUUID:(id)a2 fromAutoAssetJob:(id)a3 withOriginalSelector:(id)a4 withJobInformation:(id)a5 withResponseError:(id)a6;
+ (id)autoAssetJob:(id)a0 bondWithStagerDownloading:(id)a1;
+ (void)autoAssetStagerJobDetermineDone:(id)a0 withDetremineError:(id)a1;
+ (void)autoAssetJobFinished:(id)a0 withAutoAssetUUID:(id)a1 schedulerInvolved:(BOOL)a2 potentialNetworkFailure:(BOOL)a3;
+ (void)stagerRequestAlreadyDownloadedDescriptors;
+ (void)stagerStartJobDetermineIfAvailable:(id)a0 withAssetTargetOSVersion:(id)a1 withAssetTargetBuildVersion:(id)a2;
+ (void)stagerStartJobDownloadForStaging:(id)a0 withAssetTargetOSVersion:(id)a1 withAssetTargetBuildVersion:(id)a2;
+ (void)stagerCancelCurrentJob;
+ (void)stagerEliminatedSelector:(id)a0;
+ (void)schedulerTriggeredSelectors:(id)a0;
+ (void)schedulerTriggeredNoActivity;
+ (void)schedulerEliminatedSelector:(id)a0;
+ (void)handleReceivedPushNotifications:(id)a0;
+ (void)copyCurrentDownloadedDescriptors:(BOOL)a0 unlockedDescriptors:(id *)a1 lockedOverridableDescriptors:(id *)a2 lockedNeverRemoveDescriptors:(id *)a3 stagedDescriptors:(id *)a4;
+ (BOOL)assetBeingGarbageCollected:(id)a0 atEmergencyUrgency:(BOOL)a1;
+ (void)garbageCollectionOperationComplete:(BOOL)a0 originalUnlockedDescriptors:(id)a1 originalLockedOverridableDescriptors:(id)a2 originalLockedNeverRemoveDescriptors:(id)a3 originalStagedDescriptors:(id)a4 reclaimedV2AssetCount:(long long)a5 reclaimedV2AssetSpace:(long long)a6 reclaimedUnlockedCount:(long long)a7 reclaimedUnlockedSpace:(long long)a8 reclaimedLockedOverridableCount:(long long)a9 reclaimedLockedOverridableSpace:(long long)a10 reclaimedLockedNeverRemoveCount:(long long)a11 reclaimedLockerNeverRemoveSpace:(long long)a12 reclaimedStagedCount:(long long)a13 reclaimedStagedSpace:(long long)a14 reclaimedMetadataBlockedCount:(long long)a15 reclaimedMetadataBlockedSpace:(long long)a16 totalReclaimedSpace:(long long)a17;
+ (id)migrateMismatchedPersistedDescriptorVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (id)replyMessageNameForRequest:(id)a0;
+ (id)newSummaryForRequestMessage:(id)a0 includingSelector:(BOOL)a1;
+ (id)selectDispatchQueue:(id)a0;
+ (id)allocIntervalString:(long long)a0;
+ (void)persistForJobSelector:(id)a0 persistingJobDescriptor:(id)a1 withFirstClientName:(id)a2;
+ (void)persistForJobSelector:(id)a0 persistingJobDescriptor:(id)a1 justPatched:(BOOL)a2 withFirstClientName:(id)a3;
+ (void)persistForJobSelector:(id)a0 persistingJobDescriptor:(id)a1 justDownloaded:(BOOL)a2 justPatched:(BOOL)a3 withFirstClientName:(id)a4;
+ (id)loadDescriptorsForJobSelector:(id)a0 promotingIfCurrentlyStaged:(id)a1;
+ (id)localAssetURLForDescriptor:(id)a0;
+ (BOOL)isDeviceConsideredBeforeFirstUnlock;
+ (BOOL)preferenceScheduledAlwaysNonDiscretionary;
+ (BOOL)preferenceScheduledBackupTriggersDisabled;
+ (long long)preferenceConnectorInitialWaitSecs;
+ (id)preferenceConnectorBackoffRetryTimes;
+ (long long)preferenceConnectorWaitBeforeRetrySecs;
+ (BOOL)preferenceAutoAssetObserverIgnoreNetworkStatus;
+ (id)preferenceAsIfBootedOSIsOSVersion;
+ (id)preferenceAsIfBootedOSIsBuildVersion;
+ (BOOL)preferenceAlwaysPromoteStagedAssets;
+ (long long)preferenceActivityIntervalSecs;
+ (long long)preferencePushActivityIntervalSecs;
+ (long long)preferenceBeforeFirstPollSecs;
+ (BOOL)selectorToBeIncluded:(id)a0 basedOnControl:(id)a1;
+ (BOOL)descriptorToBeIncluded:(id)a0 basedOnControl:(id)a1;

- (id)init;
- (void).cxx_destruct;
- (id)_summary;
- (id)summary;
- (void)handleMessage:(id)a0 proxyObject:(id)a1 reply:(id /* block */)a2;
- (void)connectionClosedForClientID:(id)a0;
- (void)_initializeSUCore;
- (void)_initializeServerConnectionPolicy;
- (long long)performAction:(id)a0 onEvent:(id)a1 inState:(id)a2 withInfo:(id)a3 nextState:(id)a4 error:(id *)a5;
- (long long)actionUnknownAction:(id)a0 error:(id *)a1;
- (id)_updateLatestSummary;
- (void)_schedulePushNotifications:(id)a0;
- (void)_initializeConnectionServer;
- (void)_initializeCachedPreferences;
- (void)_initializeAutoControl;
- (long long)action_StartUnlockPollingTimer:(id)a0 error:(id *)a1;
- (long long)action_PollDecideBefore1stUnlock:(id)a0 error:(id *)a1;
- (long long)action_SyncSkippedDecideBefore1st:(id)a0 error:(id *)a1;
- (long long)action_SyncDecideBefore1st:(id)a0 error:(id *)a1;
- (long long)action_LoadPersistedResumeLocker:(id)a0 error:(id *)a1;
- (long long)action_ResumeStager:(id)a0 error:(id *)a1;
- (long long)action_SyncedResumeStager:(id)a0 error:(id *)a1;
- (long long)action_ResumeScheduler:(id)a0 error:(id *)a1;
- (long long)action_PromoteResumeScheduler:(id)a0 error:(id *)a1;
- (long long)action_SyncInFlightDownloads:(id)a0 error:(id *)a1;
- (long long)action_Synced:(id)a0 error:(id *)a1;
- (long long)action_ResumeJobsBefore1st:(id)a0 error:(id *)a1;
- (long long)action_ResumeJobs:(id)a0 error:(id *)a1;
- (long long)action_FailClientTimedOut:(id)a0 error:(id *)a1;
- (long long)action_QueueClientRequest:(id)a0 error:(id *)a1;
- (long long)action_QueueClientRequestBefore1st:(id)a0 error:(id *)a1;
- (long long)action_RemoveQueuedClient:(id)a0 error:(id *)a1;
- (long long)action_RouteClientRequest:(id)a0 error:(id *)a1;
- (long long)action_RouteClientClosed:(id)a0 error:(id *)a1;
- (long long)action_QueueDownloadManager:(id)a0 error:(id *)a1;
- (long long)action_RouteCatalogFinished:(id)a0 error:(id *)a1;
- (long long)action_RouteConfigFinished:(id)a0 error:(id *)a1;
- (long long)action_RouteAssetProgress:(id)a0 error:(id *)a1;
- (long long)action_RouteAssetFinished:(id)a0 error:(id *)a1;
- (long long)action_Before1stCatalogFinished:(id)a0 error:(id *)a1;
- (long long)action_Before1stConfigFinished:(id)a0 error:(id *)a1;
- (long long)action_Before1stAssetProgress:(id)a0 error:(id *)a1;
- (long long)action_Before1stAssetFinished:(id)a0 error:(id *)a1;
- (long long)action_SyncedReviewUnlocked:(id)a0 error:(id *)a1;
- (long long)action_SyncedReviewBefore1st:(id)a0 error:(id *)a1;
- (long long)action_ObtainLookupGrant:(id)a0 error:(id *)a1;
- (long long)action_ReleaseLookupGrant:(id)a0 error:(id *)a1;
- (long long)action_ProvidePersistedForJob:(id)a0 error:(id *)a1;
- (long long)action_IssueClientProgressReports:(id)a0 error:(id *)a1;
- (long long)action_IssueClientReplyJobResponse:(id)a0 error:(id *)a1;
- (long long)action_RemoveFinishedJob:(id)a0 error:(id *)a1;
- (long long)action_ScheduleJobsBefore1st:(id)a0 error:(id *)a1;
- (long long)action_ScheduleJobs:(id)a0 error:(id *)a1;
- (long long)action_LogStatistics:(id)a0 error:(id *)a1;
- (long long)action_IgnorePushNotifications:(id)a0 error:(id *)a1;
- (long long)action_HandlePushNotifications:(id)a0 error:(id *)a1;
- (long long)action_StagerAlreadyDownloaded:(id)a0 error:(id *)a1;
- (long long)action_StagerJobStartDetermine:(id)a0 error:(id *)a1;
- (long long)action_StagerJobStartDownload:(id)a0 error:(id *)a1;
- (long long)action_StagerJobDoneDetermine:(id)a0 error:(id *)a1;
- (long long)action_StagerJobProgressDownload:(id)a0 error:(id *)a1;
- (long long)action_StagerJobDoneDownload:(id)a0 error:(id *)a1;
- (long long)action_StagerJobCancel:(id)a0 error:(id *)a1;
- (long long)action_EliminateSchedulerDone:(id)a0 error:(id *)a1;
- (long long)action_EliminateStagerDone:(id)a0 error:(id *)a1;
- (void)trackClientRequest:(id)a0;
- (void)removeClientRequest:(id)a0 fromLocation:(id)a1;
- (void)clientRequestsAwaitingSyncToAwaitingFirstUnlock:(id)a0;
- (void)clientRequestsAwaitingDispatchAll:(id)a0;
- (void)addToCurrentJobs:(id)a0 usingSelector:(id)a1 withJobUUID:(id)a2 triggeredByClientMessage:(id)a3 downloadingDescriptor:(id)a4 baseForPatchDescriptor:(id)a5;
- (void)removeCurrentJob:(id)a0 schedulerInvolved:(BOOL)a1 potentialNetworkFailure:(BOOL)a2 fromLocation:(id)a3;
- (id)jobSelectorKey:(id)a0;
- (id)currentJobBySelector:(id)a0;
- (id)currentJobByUUID:(id)a0 fromLocation:(id)a1 notFoundCode:(long long)a2 notFoundReason:(id)a3;
- (id)currentJobByUUID:(id)a0 potentiallyResumingJob:(id)a1 withOriginalSelector:(id)a2 fromLocation:(id)a3 notFoundCode:(long long)a4 notFoundReason:(id)a5 downloadingDescriptor:(id)a6 baseForPatchDescriptor:(id)a7;
- (void)initialStatusForJob:(id)a0 usingSelector:(id)a1 withJobUUID:(id)a2 downloadingDescriptor:(id)a3 baseForPatchDescriptor:(id)a4;
- (void)updateAutoAssetStatus:(id)a0 forActiveJobUUID:(id)a1 withLatestJobStatus:(id)a2 fromLocation:(id)a3;
- (id)updateAutoAssetStatus:(id)a0 forActiveJobUUID:(id)a1 forJobResponse:(id)a2 withResponseError:(id)a3;
- (void)updateAssociatedStatus:(id)a0 forActiveJobUUID:(id)a1 withLatestJobStatus:(id)a2;
- (id)notifyLockerAsIndicatedByJob:(id)a0;
- (void)_statsIncrement:(id)a0 forClientRequest:(id)a1;
- (void)_statsIncrementAutoAssetJobsStarted;
- (void)_statsIncrementAutoJobsFinished;
- (void)_statsIncrementStagerDetermineJobsStarted;
- (void)_statsIncrementStagerDetermineJobsFinished;
- (void)_statsIncrementStagerDownloadJobsStarted;
- (void)_statsIncrementStagerDownloadJobsFinished;
- (void)_statsIncrementResumedInFlightJobs;
- (void)_statsIncrementSchedulerTriggeredJobs;
- (void)_statsIncrementFailuresToStartJobs;
- (void)_statsIncrementPreviouslyDownloadedForDescriptor:(id)a0;
- (void)_statsIncrementDownloadedForDescriptor:(id)a0;
- (void)_statsIncrementPromotedForDescriptor:(id)a0;
- (void)_statsIncrementRemovedForDescriptor:(id)a0;
- (id)_statsCombinedCopy:(BOOL)a0;
- (void)_statsMaintainReporting;
- (void)_statsClearingAfterReporting;
- (void)_statsRestartNextMaintentanceReport;
- (void)_scheduledAndRouteClientRequest:(id)a0 fromLocation:(id)a1;
- (BOOL)_messageShouldBeScheduled:(id)a0 forAssetSelector:(id)a1;
- (BOOL)_messageBlockedUntilDownloadManagerSync:(id)a0 forAssetSelector:(id)a1;
- (BOOL)_messageBlockedUntilFirstUnlock:(id)a0 forAssetSelector:(id)a1;
- (void)_routeClientRequest:(id)a0 fromLocation:(id)a1;
- (BOOL)handleClientPotentialJob:(id)a0 forAutoJob:(id)a1 fromLocation:(id)a2;
- (BOOL)handleClientCheckForNewer:(id)a0 forAutoJob:(id)a1 instance:(id)a2 desire:(id)a3 fromLocation:(id)a4;
- (BOOL)handleClientLockContent:(id)a0 forAutoJob:(id)a1 instance:(id)a2 desire:(id)a3 fromLocation:(id)a4;
- (id)buildFoundResponseMessage:(id)a0 forClientRequest:(id)a1 withFoundDescriptor:(id)a2 withInstance:(id)a3 withDesire:(id)a4 fromLocation:(id)a5;
- (void)handleClientAlterLockOperation:(id)a0 forAutoJob:(id)a1;
- (void)handleClientCurrentStatusRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleClientEliminateAllForSelectorRequest:(id)a0;
- (void)handleClientEliminateAllForAssetTypeRequest:(id)a0;
- (void)handleClientEliminatePromotedNeverLockedForSelectorRequest:(id)a0;
- (void)handleControlClientControlStatisticsRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientKnownAssetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientLockedAssetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientStagedAssetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientActiveJobSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientScheduledJobSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientForceGlobalUnlockRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientForceGlobalForgetRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientForceGlobalPurgeRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientForceGlobalAbandonRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientSimulatedCacheDeleteDetermineReclaimableRequest:(id)a0;
- (void)handleControlClientSimulatedCacheDeleteReclaimSpaceRequest:(id)a0;
- (void)handleControlClientSimulateSetJobOperation:(id)a0;
- (void)addActiveJobs:(id)a0 basedOnControl:(id)a1;
- (void)addSuccessfullyDownloadedJobs:(id)a0 basedOnControl:(id)a1;
- (void)issueResponseToClientRequest:(id)a0 issuingResponseMessage:(id)a1 withResponseError:(id)a2;
- (void)issueBuiltResponseForEventInfo:(id)a0 issuingResponseMessage:(id)a1 withResponseError:(id)a2;
- (void)issueResponseForEventInfo:(id)a0 withErrorCode:(long long)a1 fromAction:(id)a2 withDescription:(id)a3;
- (void)issueResponseForEventInfo:(id)a0 withAutoAssetError:(id)a1 fromAction:(id)a2 withDescription:(id)a3;
- (id)clientRequestMessageName:(id)a0;
- (id)clientRequestMessageInstance:(id)a0;
- (id)clientRequestMessageDesire:(id)a0;
- (BOOL)clientRequestIndicatesNoWait:(id)a0;
- (id)jobToBeGivenGrant:(id)a0;
- (void)handleStagingClientDetermineAllAvailableRequest:(id)a0;
- (void)handleStagingClientDownloadAllRequest:(id)a0;
- (void)handleStagingClientPurgeAllRequest:(id)a0;
- (id)_combinedStatisticsWithStagerClientRepliesSuccess:(id)a0 withStagerClientRepliesFailure:(id)a1 withStagerTotalStaged:(id)a2 withStagerTotalUnstaged:(id)a3;
- (id)_latestDownloadedDescriptor:(id)a0 forAssetType:(id)a1 withAssetSpecifier:(id)a2;
- (id)_latestDownloadedDescriptor:(id)a0 forAssetType:(id)a1 withAssetSpecifier:(id)a2 matchingAssetVersion:(id)a3;
- (long long)_bytesDownloadedForDescriptor:(id)a0;
- (BOOL)_updateTrackedDescriptor:(id)a0 fromLatestDescriptor:(id)a1;
- (void)_routeCatalogFinished:(id)a0 withEventInfo:(id)a1;
- (void)_routeConfigFinished:(id)a0 withEventInfo:(id)a1;
- (void)_routeAssetProgress:(id)a0 withEventInfo:(id)a1;
- (void)_routeAssetFinished:(id)a0 withEventInfo:(id)a1;
- (void)_awaitingResumeRemoveType:(long long)a0;
- (void)_awaitingResumeReduceToLatest;
- (void)_requestDownloadManagerSync;
- (id)_updatePolicyForSelector:(id)a0;
- (void)loadPersistedDescriptors;
- (void)resumeJobsWhenBeforeFirstUnlock:(BOOL)a0;
- (void)_moveFromAwaitingResumedInto:(id)a0 forSelector:(id)a1;
- (BOOL)_inDownloadsInFlight:(id)a0;
- (BOOL)_inMatchedTaskDescriptors:(id)a0 addingMatchingJobUUID:(id)a1;
- (BOOL)_taskDescriptorEncountered:(id)a0 inMatchedDescriptors:(id)a1;
- (id)jobControlInformationForSelector:(id)a0;
- (void)_removeFromPersistedActiveJobs:(id)a0;
- (void)_scheduleSelector:(id)a0;
- (void)promoteAnyPreviouslyStagedNowDownloaded:(id)a0;
- (void)_promotePreviouslyStagedNowDownloaded:(id)a0 forHistoryOperation:(long long)a1;
- (void)trackDescriptor:(id)a0 persisting:(BOOL)a1 fromLocation:(id)a2 changedWhileTerminated:(BOOL)a3 changedNeverBeenLocked:(BOOL)a4 historyOperation:(long long)a5 firstClientName:(id)a6;
- (void)trackDescriptorForgetAssetSelector:(id)a0 forHistoryOperation:(long long)a1 firstClientName:(id)a2;
- (void)trackDescriptorForgetAssetType:(id)a0 forAssetSpecifier:(id)a1 firstClientName:(id)a2;
- (void)trackDescriptorForgetAssetType:(id)a0 firstClientName:(id)a1;
- (void)_trackActiveDescriptor:(id)a0 operation:(id)a1 usingSelector:(id)a2 withJobUUID:(id)a3 triggeredByClientMessage:(id)a4 downloadingDescriptor:(id)a5 baseForPatchDescriptor:(id)a6 message:(id)a7;
- (void)_logTrackedDescriptors:(id)a0 forAssetType:(id)a1 withAssetSpecifier:(id)a2 matchingAssetVersion:(id)a3;
- (BOOL)jobDescriptorOnFilesystemValidated:(id)a0;
- (BOOL)jobDescriptorInFlightNowOnFilesystem:(id)a0;
- (void)_eliminatePromotedNeverLocked:(id)a0 forAssetSelector:(id)a1;
- (void)_eliminateBegin:(id)a0 forAssetSelector:(id)a1 fromLocation:(id)a2;
- (void)_removeAllContentForEliminateTracker:(id)a0 unlessCurrentlyLocked:(id)a1;
- (void)_removeAllUnlockedForSelectorWithoutVersion:(id)a0;
- (void)_removeDescriptorFromFilesystem:(id)a0 forHistoryOperation:(long long)a1 firstClientName:(id)a2;
- (void)_removeAllQueuedForEliminateSelector:(id)a0;
- (BOOL)_selectorBeingEliminated:(id)a0 fromLocation:(id)a1;
- (BOOL)_isClientRequestSubjectToElimination:(id)a0;
- (void)_refreshEliminate:(id)a0 withJobUUID:(id)a1;
- (void)_eliminateCompleteIfAllDone:(id)a0;
- (BOOL)_doesEliminateSelector:(id)a0 matchAssetType:(id)a1 withAssetSpecifier:(id)a2 withAssetVersion:(id)a3 fromLocation:(id)a4;
- (void)timerStartForRequest:(id)a0 fromLocation:(id)a1;
- (void)timerStopForClientRequest:(id)a0 fromLocation:(id)a1;
- (long long)clientRequestTimeoutSecs:(id)a0;
- (void)_logPersistedEntry:(id)a0 forComponentType:(id)a1 operation:(id)a2 forPersistedEntryID:(id)a3 forClientRequest:(id)a4 withJobUUID:(id)a5 withAssetDescriptor:(id)a6 baseForPatchDescriptor:(id)a7 message:(id)a8;
- (void)_logPersistedRemovedEntry:(id)a0 forComponentType:(id)a1 removedPersistedEntryID:(id)a2 removedDescriptor:(id)a3 message:(id)a4;
- (void)_logPersistedTableOfContents:(id)a0 forComponentType:(id)a1;
- (void)_logLookupGrantObtained:(id)a0 ofLookupGrant:(id)a1 message:(id)a2;
- (void)_logLookupGrantAwaiting:(id)a0 ofLookupGrant:(id)a1 message:(id)a2;
- (void)_logLookupGrantReleased:(id)a0 ofLookupGrant:(id)a1 message:(id)a2;
- (BOOL)jobToBeIncluded:(id)a0 basedOnControl:(id)a1;

@end
