@class RTLocationManager, RTNetworkOfInterestManager, SMCMNoMovementMonitor, SMAppDeletionManager, NSMutableArray, RTVehicleLocationProvider, RTXPCActivityManager, RTStarkManager, RTAuthorizationManager, SMInitiatorSessionInitializationRequest, SMSessionManager, SMSafetyCacheStore, RTLearnedLocationManager, RTPlatform, RTDefaultsManager, SMSuggestionsManager, SMSessionStore, RTContactsManager, SMSuggestionsHelper, RTHealthKitManager, RTInvocationDispatcher, SMDeviceConfigurationChecker, SMMessagingService, SMActiveSessionZone, SMSessionMetricManager, RTMotionActivityManager, RTBatteryManager, RTBiomeManager, SMSessionMonitor, NSString, RTLocationAwarenessManager, SMWatchdog, NSHashTable, NSTimer, RTWatchWristStateManager, RTDataProtectionManager;

@interface SMInitiatorService : RTService <SMInitiatorCacheManagerDelegateProtocol, RTPurgable, SMInitiatorCacheProtocol, SMInitiatorSessionConfigurationProtocol, SMInitiatorGroupChatProtocol, SMSessionManagerObserverProtocol, SMUserNotificationProtocol, SMWorkoutSnapshotProtocol>

@property (retain, nonatomic) NSHashTable *observers;
@property (nonatomic) BOOL fetchAllZonesRetried;
@property (nonatomic) BOOL frequentSingleShotFetchAllZonesInProgress;
@property (nonatomic) BOOL fetchAllZonesFromContainerInProgress;
@property (retain, nonatomic) RTContactsManager *contactsManager;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTLocationAwarenessManager *locationAwarenessManager;
@property (readonly, nonatomic) RTPlatform *platform;
@property (readonly, nonatomic) SMSessionMonitor *sessionMonitor;
@property (readonly, nonatomic) SMMessagingService *messagingService;
@property (readonly, nonatomic) RTNetworkOfInterestManager *networkOfInterestManager;
@property (retain, nonatomic) NSMutableArray *cacheManagerArray;
@property (readonly, nonatomic) SMSafetyCacheStore *safetyCacheStore;
@property (nonatomic) unsigned long long safetyCacheStoreAvailability;
@property (readonly, nonatomic) SMSessionStore *sessionStore;
@property (nonatomic) unsigned long long sessionStoreAvailability;
@property (readonly, nonatomic) RTDataProtectionManager *dataProtectionManager;
@property (readonly, nonatomic) RTBatteryManager *batteryManager;
@property (readonly, nonatomic) RTXPCActivityManager *xpcActivityManager;
@property (readonly, nonatomic) RTAuthorizationManager *authorizationManager;
@property (readonly, nonatomic) RTHealthKitManager *healthKitManager;
@property (readonly, nonatomic) SMDeviceConfigurationChecker *deviceConfigurationChecker;
@property (nonatomic) BOOL sessionsLoadedFromDisk;
@property (nonatomic) BOOL sessionManagerBootstrapped;
@property (retain, nonatomic) SMInitiatorSessionInitializationRequest *pendingInitializationRequest;
@property (readonly, nonatomic) RTWatchWristStateManager *wristStateManager;
@property (readonly, nonatomic) RTVehicleLocationProvider *vehicleLocationProvider;
@property (readonly, nonatomic) SMSessionMetricManager *sessionMetricManager;
@property (readonly, nonatomic) RTStarkManager *starkManager;
@property (readonly, nonatomic) SMSuggestionsManager *suggestionsManager;
@property (readonly, nonatomic) SMSuggestionsHelper *suggestionsHelper;
@property (retain, nonatomic) RTInvocationDispatcher *dispatcher;
@property (retain, nonatomic) SMWatchdog *watchdog;
@property (retain, nonatomic) SMActiveSessionZone *activeSessionDetailsZone;
@property (retain, nonatomic) NSTimer *workoutSessionEndBufferTimerAlarm;
@property (retain, nonatomic) SMCMNoMovementMonitor *noMovementMonitor;
@property (retain, nonatomic) RTBiomeManager *biomeManager;
@property (retain, nonatomic) SMAppDeletionManager *appDeletionManager;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (readonly, nonatomic) SMSessionManager *sessionManager;
@property (readonly, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (long long)periodicPurgePolicy;

- (void)dealloc;
- (void).cxx_destruct;
- (void)removeObserver:(id)a0;
- (void)addObserver:(id)a0;
- (void)_setup;
- (void)_onWorkoutPause;
- (void)_setupCacheManagersWithHandler:(id /* block */)a0;
- (id)invocationError;
- (void)onHealthKitManagerNotification:(id)a0;
- (void)onSafetyCacheStoreNotification:(id)a0;
- (void)_cancelInitializationForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)_cancelInitializationWithHandler:(id /* block */)a0;
- (id)_createInitiatorCacheManagerForSessionID:(id)a0 conversation:(id)a1;
- (void)_endSessionEarlyIfNecessaryWithConfiguration:(id)a0;
- (void)_endSessionForSessionID:(id)a0 reason:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)_fetchCurrentLocalSessionStateWithHandler:(id /* block */)a0;
- (void)_fetchCurrentSessionStateWithHandler:(id /* block */)a0;
- (void)_fetchCurrentWorkoutSnapshotWithHandler:(id /* block */)a0;
- (void)_fetchDeviceConfigurationLowPowerModeWarningStateWithHandler:(id /* block */)a0;
- (void)_fetchInitiatorSafetyCacheForSessionID:(id)a0 completion:(id /* block */)a1;
- (void)_fetchSOSReceiversWithCompletion:(id /* block */)a0;
- (void)_handoffSessionForSessionID:(id)a0 handler:(id /* block */)a1;
- (BOOL)_hasSetupObjectsDependentOnPersistenceStack;
- (void)_initializeAndStartSessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)_initializeSessionWithConversation:(id)a0 handler:(id /* block */)a1;
- (void)_modifySessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)_onBecomingActiveDevice:(id)a0;
- (void)_onBecomingNonActiveDevice:(id)a0;
- (void)_onDeletedConversation:(id)a0;
- (void)_onDeletedMessage:(id)a0;
- (void)_onHealthKitManagerNotification:(id)a0;
- (void)_onMessageReceived:(id)a0;
- (void)_onNearbyEffectivePairedDeviceChangedNotification:(id)a0;
- (void)_onSafetyCacheStoreNotification:(id)a0;
- (void)_onSecondarySOSTriggerWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)_onSessionResumedWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)_onSessionStartMessageSendResult:(id)a0;
- (void)_onSessionStateChanged:(id)a0 forActiveDevice:(BOOL)a1;
- (void)_onSessionStoreNotification:(id)a0;
- (void)_onWorkoutResume;
- (void)_promptDestinationAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_promptRoundTripAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_promptSafeArrivalWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_promptTimerEndedVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_promptWorkoutAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_purgePredating:(id)a0 completion:(id /* block */)a1;
- (void)_respondToNotificationWithIdentifier:(id)a0 sessionIdentifier:(id)a1 actionIdentifier:(id)a2 handler:(id /* block */)a3;
- (void)_respondToTriggerPromptForSessionID:(id)a0 response:(long long)a1 handler:(id /* block */)a2;
- (void)_sendHeartbeatForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)_sendSafetyCacheForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)_sendSessionStartMessageWithInvitationTokenMap:(id)a0;
- (void)_setupOncePersistenceStackAvailable;
- (void)_setupSessionManager;
- (void)_setupSessionMonitor;
- (void)_shutdownWithHandler:(id /* block */)a0;
- (void)_startInitializationProcess;
- (void)_startSessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)addObserverForSessionManager:(id)a0;
- (void)cacheManagerCleanedUpForSessionID:(id)a0;
- (void)cacheManagerDidUpdateCacheForSessionID:(id)a0 phoneCache:(id)a1 watchCache:(id)a2 cacheExpiryDate:(id)a3 cacheReleaseDate:(id)a4;
- (void)cancelInitializationForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)cancelInitializationWithHandler:(id /* block */)a0;
- (void)checkAndDeleteKey:(id)a0 forIdentifier:(id)a1;
- (id)convertEligibilityToSMErrorWithInitiator:(long long)a0 receiver:(long long)a1;
- (long long)convertInitiatorEligibilityToSMError:(long long)a0;
- (long long)convertReceiverEligibilityToSMError:(long long)a0;
- (void)deleteAllStoredDefaults;
- (void)endSessionForSessionID:(id)a0 reason:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)fetchCurrentLocalSessionStateWithHandler:(id /* block */)a0;
- (void)fetchCurrentSessionStateWithHandler:(id /* block */)a0;
- (void)fetchCurrentWorkoutSnapshotWithHandler:(id /* block */)a0;
- (void)fetchDeviceConfigurationLowPowerModeWarningStateWithHandler:(id /* block */)a0;
- (void)fetchInitiatorSafetyCacheForSessionID:(id)a0 completion:(id /* block */)a1;
- (void)fetchSOSReceiversWithCompletion:(id /* block */)a0;
- (id)getCacheManagerForSessionID:(id)a0;
- (void)handleSessionStateForNonActiveSessions:(id)a0;
- (void)handoffSessionForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)iMessageGroupDisplayNameChangedFor:(id)a0;
- (void)iMessageGroupMembershipChangedFor:(id)a0;
- (void)iMessageGroupPhotoChangedFor:(id)a0;
- (id)initWithDefaultsManager:(id)a0 contactsManager:(id)a1 locationManager:(id)a2 motionActivityManager:(id)a3 platform:(id)a4 messagingService:(id)a5 safetyCacheStore:(id)a6 sessionStore:(id)a7 dataProtectionManager:(id)a8 batteryManager:(id)a9 xpcActivityManager:(id)a10 networkOfInterestManager:(id)a11 authorizationManager:(id)a12 wristStateManager:(id)a13 vehicleLocationProvider:(id)a14 starkManager:(id)a15 suggestionsManager:(id)a16 suggestionsHelper:(id)a17 learnedLocationManager:(id)a18 healthKitManager:(id)a19 deviceConfigurationChecker:(id)a20 noMovementMonitor:(id)a21 biomeManager:(id)a22 appDeletionManager:(id)a23;
- (id)initWithDefaultsManager:(id)a0 contactsManager:(id)a1 locationManager:(id)a2 motionActivityManager:(id)a3 platform:(id)a4 sessionManager:(id)a5 sessionMonitor:(id)a6 messagingService:(id)a7 safetyCacheStore:(id)a8 sessionStore:(id)a9 dataProtectionManager:(id)a10 batteryManager:(id)a11 xpcActivityManager:(id)a12 networkOfInterestManager:(id)a13 authorizationManager:(id)a14 wristStateManager:(id)a15 vehicleLocationProvider:(id)a16 starkManager:(id)a17 suggestionsManager:(id)a18 suggestionsHelper:(id)a19 learnedLocationManager:(id)a20 healthKitManager:(id)a21 deviceConfigurationChecker:(id)a22 noMovementMonitor:(id)a23 biomeManager:(id)a24 appDeletionManager:(id)a25;
- (void)initializeAndStartSessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)initializeSessionWithConversation:(id)a0 handler:(id /* block */)a1;
- (void)kickedFromIMessageGroupWith:(id)a0;
- (void)modifySessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)notifyObserversSafetyCacheDidUpdateForSessionID:(id)a0 phoneCache:(id)a1 watchCache:(id)a2 cacheExpiryDate:(id)a3 cacheReleaseDate:(id)a4;
- (void)onBecomingActiveDevice:(id)a0;
- (void)onBecomingNonActiveDevice:(id)a0;
- (void)onDeletedConversation:(id)a0;
- (void)onDeletedMessage:(id)a0;
- (void)onMessageReceived:(id)a0;
- (void)onNearbyEffectivePairedDeviceChangedNotification:(id)a0;
- (void)onSecondarySOSTriggerWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onSessionResumedWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onSessionStartMessageSendResult:(id)a0;
- (void)onSessionStateChanged:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onSessionStoreNotification:(id)a0;
- (void)performPurgeOfType:(long long)a0 referenceDate:(id)a1 completion:(id /* block */)a2;
- (void)promptDestinationAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptRoundTripAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptSafeArrivalWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptTimerEndedVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptWorkoutAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)receivedEmergencyContactsNotifiedSyncMessage:(id)a0;
- (void)receivedKeyReleaseInfoRequestMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedResponseToTriggerPromptRemoteControlMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionConfigurationUpdateRemoteControlMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionEndRemoteControlMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionStartInfoRequestMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionStateUpdateReqMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionSyncMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionTypeKeyRelease:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)removeObserverForSessionManager:(id)a0;
- (void)respondToNotificationWithIdentifier:(id)a0 sessionIdentifier:(id)a1 actionIdentifier:(id)a2 handler:(id /* block */)a3;
- (void)respondToTriggerPromptForSessionID:(id)a0 response:(long long)a1 handler:(id /* block */)a2;
- (void)scheduledSendMessageCanceledForSessionID:(id)a0 guid:(id)a1;
- (void)scheduledSendMessageScheduledForSessionID:(id)a0 guid:(id)a1 date:(id)a2;
- (void)scheduledSendMessageSent:(id)a0;
- (void)sendHeartbeatForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)sendSafetyCacheForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)startSessionWithConfiguration:(id)a0 handler:(id /* block */)a1;

@end
