@class RTDefaultsManager, RTBatteryManager, RTWatchWristStateManager, SMSessionManagerState, RTLocationManager, SMScreenLockMonitor, RTAuthorizationManager, RTNetworkOfInterestManager, SMCAMetricCacheUpdate, SMActiveSessionZone, RTXPCActivityManager, RTXPCTimerAlarm, SMMessagingService, SMSessionStore, RTPlatform, NSObject, SMInitiatorContact, SMAppDeletionManager, RTHealthKitManager, NSUUID, SMSafetyCacheZone, RTLocationAwarenessManager, RTVehicleLocationProvider, SMSafetyCacheStore;
@protocol OS_dispatch_queue, SMInitiatorCacheManagerDelegateProtocol;

@interface SMInitiatorCacheManager : NSObject <SMInitiatorCacheProtocol>

@property (nonatomic) BOOL initializationInProgress;
@property (nonatomic) BOOL initializationWasAborted;
@property (nonatomic) BOOL initializationCompletionCalled;
@property (copy, nonatomic) id /* block */ initializationCompletion;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *initiatorEligibilityQueue;
@property (retain, nonatomic) RTXPCTimerAlarm *scheduledSendFireTimerAlarm;
@property (retain, nonatomic) RTXPCTimerAlarm *cacheUpdateBackstopTimerAlarm;
@property (nonatomic) BOOL scheduledSendInProgress;
@property (retain, nonatomic) SMCAMetricCacheUpdate *caMetricCacheUpdate;
@property (copy, nonatomic) id /* block */ deviceStatusReturnBlock;
@property (nonatomic) BOOL wifiLinkQualityFetchInProgress;
@property (nonatomic) BOOL cellularLinkQualityFetchInProgress;
@property (nonatomic) BOOL initiatorContactStoreInProgress;
@property (nonatomic) BOOL isPeriodicallyUpdatingCache;
@property (nonatomic) BOOL registeredForActiveNotifications;
@property (nonatomic) BOOL registeredForGeneralNotifications;
@property (readonly, nonatomic) SMSafetyCacheStore *safetyCacheStore;
@property (readonly, nonatomic) SMSessionStore *sessionStore;
@property (readonly, nonatomic) RTDefaultsManager *defaultsManager;
@property (readonly, nonatomic) RTLocationAwarenessManager *locationAwarenessManager;
@property (readonly, nonatomic) RTLocationManager *locationManager;
@property (readonly, retain) NSObject<OS_dispatch_queue> *queue;
@property (readonly, nonatomic) RTBatteryManager *batteryManager;
@property (retain, nonatomic) SMSafetyCacheZone *activeSessionZone;
@property (readonly, nonatomic) SMInitiatorContact *initiatorContact;
@property (retain, nonatomic) RTXPCActivityManager *xpcActivityManager;
@property (retain, nonatomic) SMSessionManagerState *sessionManagerState;
@property (readonly, nonatomic) SMMessagingService *messagingService;
@property (readonly, nonatomic) RTNetworkOfInterestManager *networkOfInterestManager;
@property (nonatomic) unsigned long long cellularStrength;
@property (nonatomic) unsigned long long wifiStrength;
@property (readonly, nonatomic) RTAuthorizationManager *authorizationManager;
@property (nonatomic) BOOL initiatorContactStored;
@property (nonatomic) BOOL initiatorContactUpdatePending;
@property (retain, nonatomic) NSUUID *cacheUploadInProgress;
@property (nonatomic) long long initiatorEligibility;
@property (nonatomic) long long receiverEligibility;
@property (readonly, nonatomic) RTWatchWristStateManager *wristStateManager;
@property (readonly, nonatomic) RTVehicleLocationProvider *vehicleLocationProvider;
@property (retain, nonatomic) RTXPCTimerAlarm *cleanupCacheTimerAlarm;
@property (retain, nonatomic) SMScreenLockMonitor *screenLockMonitor;
@property (nonatomic) double cacheUpdateBackstopTimeout;
@property (retain, nonatomic) SMActiveSessionZone *activeSessionDetailsZone;
@property (readonly, nonatomic) RTHealthKitManager *healthKitManager;
@property (readonly, nonatomic) RTPlatform *platform;
@property (readonly, nonatomic) SMAppDeletionManager *appDeletionManager;
@property (weak, nonatomic) id<SMInitiatorCacheManagerDelegateProtocol> delegate;
@property (readonly, nonatomic) NSUUID *sessionUUID;

+ (id)getTelemetryEventStringForEvent:(long long)a0;

- (void).cxx_destruct;
- (BOOL)isStandalone;
- (void)_registerForActiveNotifications;
- (void)_updateCacheDataWithCompletion:(id /* block */)a0;
- (void)onHealthKitManagerNotification:(id)a0;
- (void)processSessionStartInfoRequest:(id)a0;
- (void)_cancelScheduledKeyRelease;
- (void)_cancelScheduledKeyReleaseForConversation:(id)a0;
- (void)_checkConversationEligibilityWithCompletion:(id /* block */)a0;
- (void)_checkInitiatorEligibilityWithCompletion:(id /* block */)a0;
- (void)_cleanUpInitiatorContact;
- (void)_cleanUpInitiatorContactLocalStore;
- (void)_cleanupActiveSessionZone;
- (void)_deleteActiveSessionDetails:(long long)a0;
- (void)_evaluateAndManagePeriodicCacheUpdate;
- (void)_fetchDeviceStatusWithCompletion:(id /* block */)a0;
- (void)_fetchLocationWithCompletion:(id /* block */)a0;
- (id)_getScheduleSendCancelRetryXpcActivityIdentifier;
- (void)_handleScheduledSendTimerFired;
- (BOOL)_isEffectivePairedDeviceNearby;
- (BOOL)_isEligibleForCacheUpdateAndPerformRecoveryIfNecessary;
- (BOOL)_isKeyReleaseScheduled;
- (void)_onHealthKitManagerWorkoutSnapshotUpdate:(id)a0;
- (void)_onNearbyEffectivePairedDeviceChangedNotification:(id)a0;
- (void)_periodicCacheUpdateWithCompletion:(id /* block */)a0;
- (void)_processCancelScheduledKeyReleaseResponseWithSuccess:(BOOL)a0 error:(id)a1;
- (void)_processScheduleKeyReleaseResponseScheduledSendDate:(id)a0 messageID:(id)a1 success:(BOOL)a2 error:(id)a3;
- (void)_processUploadCacheResponseForCache:(id)a0 hashString:(id)a1 success:(BOOL)a2 error:(id)a3;
- (void)_registerForGeneralNotifications;
- (void)_requestSmoothedLocationsWithCompletion:(id /* block */)a0;
- (id)_scheduleKeyReleaseWithCompletion:(id /* block */)a0;
- (void)_schedulePeriodicCacheUpdate;
- (void)_scheduleScheduleSendCancelRetry;
- (double)_scheduledSendTimeAdvance;
- (void)_sendCacheUpdatedMessage;
- (void)_sendKeyReleaseMessageForIsSecondarySOSTrigger:(BOOL)a0;
- (void)_setupActiveSessionZone;
- (void)_setupFetchOnZoneUpdates;
- (void)_setupShareZoneWithCompletion:(id /* block */)a0;
- (BOOL)_shouldIncludeWorkoutSnapshotInCache:(id)a0;
- (BOOL)_shouldPerformFirstCacheUpdateCKOperation;
- (BOOL)_shouldScheduleKeyReleaseMessage;
- (void)_stopCleanupCacheTimerAlarm;
- (void)_stopPeriodicCacheUpdate;
- (void)_stopScheduleSendCancelRetry;
- (void)_storeInitiatorContactInStore:(unsigned long long)a0;
- (void)_teardownFetchOnZoneUpdates;
- (void)_transitionToActiveState;
- (void)_transitionToCacheReleaseStateForIsSecondarySOSTrigger:(BOOL)a0;
- (void)_transitionToNotActiveState:(BOOL)a0;
- (void)_unregisterForActiveNotifications;
- (void)_unregisterForGeneralNotifications;
- (void)_updateCacheDataForNonActiveDeviceWithCompletion:(id /* block */)a0;
- (void)_updateInitiatorContactInStore;
- (void)_updateInitiatorContactWithConversation:(id)a0;
- (void)_updateLockState:(BOOL)a0 location:(id)a1;
- (void)_updateScheduledSendFireTimer;
- (void)_updateVehicleParkingLocation:(id)a0;
- (void)_uploadCache:(id)a0 completion:(id /* block */)a1;
- (void)_uploadCacheForNonActiveDevice:(id)a0 completion:(id /* block */)a1;
- (void)_writeActiveSessionDetails:(long long)a0 qos:(id)a1 completion:(id /* block */)a2;
- (void)cleanupNonActiveSession;
- (void)decryptAndStoreSafetyCacheDataWithPhoneCacheData:(id)a0 watchCacheData:(id)a1 metricsDict:(id *)a2;
- (void)deleteZoneFromDatabaseWithRetry:(long long)a0 database:(id)a1 qos:(id)a2 withCompletion:(id /* block */)a3;
- (void)eraseCacheDataInMemory;
- (void)fetchInitiatorSafetyCacheForSessionID:(id)a0 completion:(id /* block */)a1;
- (double)getCacheUpdateBackstopTimeout;
- (id)getXpcActivityIdentifier;
- (id)initWithInitiatorContact:(id)a0 loadedFromDisk:(BOOL)a1 safetyCacheStore:(id)a2 sessionStore:(id)a3 defaultsManager:(id)a4 locationManager:(id)a5 queue:(id)a6 batteryManager:(id)a7 xpcActivityManager:(id)a8 messagingService:(id)a9 networkOfInterestManager:(id)a10 authorizationManager:(id)a11 wristStateManager:(id)a12 vehicleLocationProvider:(id)a13 activeSessionDetailsZone:(id)a14 healthKitManager:(id)a15 platform:(id)a16 appDeletionManager:(id)a17;
- (id)initWithSafetyCacheStore:(id)a0 sessionStore:(id)a1 defaultsManager:(id)a2 locationManager:(id)a3 queue:(id)a4 batteryManager:(id)a5 xpcActivityManager:(id)a6 messagingService:(id)a7 networkOfInterestManager:(id)a8 authorizationManager:(id)a9 sessionID:(id)a10 wristStateManager:(id)a11 vehicleLocationProvider:(id)a12 activeSessionDetailsZone:(id)a13 healthKitManager:(id)a14 platform:(id)a15 appDeletionManager:(id)a16;
- (void)initializeSessionWithCompletion:(id /* block */)a0;
- (BOOL)isActiveDevice;
- (BOOL)isCellularActivated;
- (void)notifyObserversSafetyCacheDidUpdate;
- (void)onBecomingActiveDevice:(id)a0;
- (void)onBecomingNonActiveDevice:(id)a0;
- (void)onCellLinkQualityChangedNotification:(id)a0;
- (void)onLockStateChange:(BOOL)a0;
- (void)onNearbyEffectivePairedDeviceChangedNotification:(id)a0;
- (void)onSecondarySOSTriggerWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onSessionResumedWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onSessionStateChanged:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onVehicleEventNotification:(id)a0;
- (void)onWifiLinkQualityChangedNotification:(id)a0;
- (void)processKeyReleaseInfoRequest:(id)a0;
- (double)requestTimeFromTimed;
- (void)stopCacheUpdateBackstopTimer;
- (void)storeCAMetricForAllLocations:(id)a0;
- (void)submitCAMetricInitiatorSession;
- (void)submitCacheUpdateCAMetricForCache:(id)a0 success:(BOOL)a1 error:(id)a2;
- (void)submitPowerTelemetryMetricForEvent:(long long)a0;
- (void)updateCacheUpdateBackstopTimer;
- (void)updateNonActiveSafetyCacheWithRetry:(long long)a0 data:(id)a1 qos:(id)a2 completion:(id /* block */)a3;
- (void)updateSafetyCacheWithRetry:(long long)a0 data:(id)a1 cacheReleaseTime:(id)a2 qos:(id)a3 completion:(id /* block */)a4;

@end
