@class NSMutableDictionary, NSDictionary, NSObject, MAAutoAssetUpdatePolicy, NSMutableArray, MANAutoAssetControlStatistics, SUCoreFSM, NSString, SUCoreConnectServerPolicy, SUCoreLog, SUCoreConnectServer, MADAutoAssetPersisted, MAAutoAssetSelector, NSTimer, NSArray, MADAutoAssetJob;
@protocol OS_dispatch_queue;

@interface MADAutoAssetControlManager : NSObject <SUCoreFSMDelegate, SUCoreConnectServerDelegate>

@property (readonly, retain, nonatomic) SUCoreLog *logger;
@property (readonly, retain, nonatomic) NSObject<OS_dispatch_queue> *sharedDispatchQueue;
@property (retain, nonatomic) SUCoreConnectServerPolicy *serverConnectionPolicy;
@property (retain, nonatomic) SUCoreConnectServer *connectionServer;
@property (readonly, retain, nonatomic) NSDictionary *stateTable;
@property (retain, nonatomic) NSString *latestSafeSummary;
@property (retain, nonatomic) SUCoreFSM *autoControlManagerFSM;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedActiveJobs;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedKnownDescriptors;
@property (retain, nonatomic) NSMutableDictionary *currentStatusBySelector;
@property (retain, nonatomic) NSMutableDictionary *currentJobsBySelector;
@property (retain, nonatomic) NSMutableDictionary *currentJobsByUUID;
@property (nonatomic) BOOL stagerResumed;
@property (retain, nonatomic) MADAutoAssetJob *stagerCurrentJob;
@property (retain, nonatomic) MADAutoAssetJob *stagerBondedToAutoJob;
@property (retain, nonatomic) NSString *stagerCurrentJobUUID;
@property (retain, nonatomic) MAAutoAssetSelector *stagerDownloadingSelector;
@property (retain, nonatomic) NSMutableDictionary *lookupGrantsByAssetType;
@property (readonly, retain, nonatomic) MAAutoAssetUpdatePolicy *defaultUpdatePolicy;
@property (retain, nonatomic) NSMutableDictionary *timedOperations;
@property (retain, nonatomic) NSMutableDictionary *clientRequestsBeingTracked;
@property (retain, nonatomic) NSMutableArray *clientRequestsAwaitingSync;
@property (retain, nonatomic) NSMutableArray *clientRequestsAwaitingFirstUnlock;
@property (retain, nonatomic) NSMutableArray *downloadManagerEventsAwaitingResumed;
@property (retain, nonatomic) NSMutableArray *downloadManagerInFlightTasks;
@property (retain, nonatomic) NSTimer *beyondFirstUnlockPollTimer;
@property (retain, nonatomic) NSTimer *awaitDownloadManagerSyncTimer;
@property (nonatomic) BOOL receivedDownloadManagerSync;
@property (nonatomic) BOOL maintainingActiveJobStatus;
@property (retain, nonatomic) NSMutableDictionary *activelyEliminatingSelectors;
@property (retain, nonatomic) MANAutoAssetControlStatistics *statistics;
@property (nonatomic) double statisticsNextMaintenanceReport;
@property (retain, nonatomic) NSMutableDictionary *currentSetJobsByIdentifier;
@property (retain, nonatomic) NSMutableDictionary *currentSetStatusByInstance;
@property (retain, nonatomic) NSMutableDictionary *knownSetConfigurationsByIdentifier;
@property (retain, nonatomic) NSMutableDictionary *knownSetAtomicInstancesByInstance;
@property (retain, nonatomic) NSMutableDictionary *downloadedSetDescriptorsByInstance;
@property (retain, nonatomic) NSMutableDictionary *activeSetDescriptorsByIdentifier;
@property (retain, nonatomic) NSMutableDictionary *activeSetDescriptorsByInstance;
@property (nonatomic) BOOL persistedActiveSetJobsLoaded;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedKnownSetConfigurations;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedKnownSetAtomicInstances;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedActiveJobSetDescriptors;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedDownloadedSetDescriptors;
@property (retain, nonatomic) NSMutableDictionary *setLockUsageMap;
@property (nonatomic) BOOL preferenceScheduledAlwaysNonDiscretionary;
@property (nonatomic) BOOL preferenceScheduledBackupTriggersDisabled;
@property (nonatomic) long long preferenceConnectorInitialWaitSecs;
@property (retain, nonatomic) NSArray *preferenceConnectorBackoffRetryTimes;
@property (nonatomic) long long preferenceConnectorWaitBeforeRetrySecs;
@property (nonatomic) BOOL preferenceAutoAssetObserverIgnoreNetworkStatus;
@property (retain, nonatomic) NSString *preferenceAsIfBootedOSIsOSVersion;
@property (retain, nonatomic) NSString *preferenceAsIfBootedOSIsBuildVersion;
@property (nonatomic) BOOL preferenceAlwaysPromoteStagedAssets;
@property (nonatomic) long long preferenceActivityIntervalSecs;
@property (nonatomic) long long preferencePushActivityIntervalSecs;
@property (nonatomic) long long preferenceLookupCacheAssetSelectorValidSecs;
@property (nonatomic) long long preferenceLookupCacheSetConfigurationValidSecs;
@property (nonatomic) long long preferenceBeforeFirstPollSecs;
@property (nonatomic) long long preferenceBeforeFirstDefaultTimeoutSecs;
@property (nonatomic) BOOL operatingBeforeFirstUnlock;
@property (nonatomic) BOOL operatingBeforeResumed;
@property (nonatomic) BOOL simulateOperationRequested;
@property (retain, nonatomic) NSMutableDictionary *simulateOperationsBySelector;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createSeverMessageWithName:(id)a0 sender:(id)a1 clientID:(id)a2 response:(id)a3 error:(id)a4;
+ (void)assetDownloadJobFinished:(id)a0 error:(id)a1;
+ (void)downloadManagerStateSyncSkipped;
+ (void)installAutoAssetWithDescriptor:(id)a0;
+ (id)stagerSetPolicy;
+ (id)_getAutoControlManagerStateTable;
+ (id)allocIntervalString:(long long)a0;
+ (BOOL)assetBeingGarbageCollected:(id)a0 atEmergencyUrgency:(BOOL)a1;
+ (void)assetConfigJobFinished:(id)a0 error:(id)a1;
+ (void)assetDownloadJob:(id)a0 progressReport:(id)a1;
+ (BOOL)assetSetToBeIncluded:(id)a0 consideredClientDomain:(id)a1 basedOnControl:(id)a2;
+ (id)autoAssetJob:(id)a0 bondWithStagerDownloading:(id)a1;
+ (void)autoAssetJobFinished:(id)a0 withAutoAssetUUID:(id)a1 schedulerInvolved:(BOOL)a2 potentialNetworkFailure:(BOOL)a3;
+ (void)autoAssetJobIssueProgress:(id)a0 forAutoAssetSelector:(id)a1 withAutoAssetUUID:(id)a2 withJobInformation:(id)a3 withResponseError:(id)a4;
+ (void)autoAssetJobIssueReply:(id)a0 forAutoAssetSelector:(id)a1 withAutoAssetUUID:(id)a2 fromAutoAssetJob:(id)a3 withOriginalSelector:(id)a4 withJobInformation:(id)a5 withResponseError:(id)a6;
+ (void)autoAssetJobObtainLookupGrant:(id)a0 forAutoAssetUUID:(id)a1 fromAutoAssetJob:(id)a2;
+ (void)autoAssetJobReadyToDownload:(id)a0 withAutoAssetUUID:(id)a1 fromAutoAssetJob:(id)a2 withOriginalSelector:(id)a3 downloadingDescriptor:(id)a4 baseForPatchDescriptor:(id)a5;
+ (void)autoAssetJobReleaseLookupGrant:(id)a0 forAutoAssetUUID:(id)a1 fromAutoAssetJob:(id)a2;
+ (void)autoAssetStagerJobDetermineDone:(id)a0 withDetremineError:(id)a1;
+ (void)autoAssetStagerJobDownloadDone:(id)a0 withDownloadError:(id)a1;
+ (void)autoAssetStagerJobDownloadProgress:(id)a0 withProgressError:(id)a1;
+ (id)autoControlManager;
+ (void)autoSetJobFinished:(id)a0 forAssetSetIdentifier:(id)a1 withAutoAssetUUID:(id)a2 fromAutoAssetJob:(id)a3 withSetJobInformation:(id)a4 schedulerInvolved:(BOOL)a5 potentialNetworkFailure:(BOOL)a6;
+ (void)autoSetJobIssueProgress:(id)a0 forAssetSetIdentifier:(id)a1 withAutoAssetUUID:(id)a2 withSetJobInformation:(id)a3 withResponseError:(id)a4;
+ (void)autoSetJobIssueReply:(id)a0 forDomainName:(id)a1 forAssetSetIdentifier:(id)a2 withAutoAssetUUID:(id)a3 fromAutoAssetJob:(id)a4 withSetJobInformation:(id)a5 withResponseError:(id)a6;
+ (void)catalogDownloadJobFinished:(id)a0 withCatalog:(id)a1 error:(id)a2;
+ (void)copyCurrentDownloadedDescriptors:(BOOL)a0 unlockedDescriptors:(id *)a1 lockedOverridableDescriptors:(id *)a2 lockedNeverRemoveDescriptors:(id *)a3 stagedDescriptors:(id *)a4;
+ (BOOL)descriptorToBeIncluded:(id)a0 basedOnControl:(id)a1;
+ (void)downloadManagerStateSyncDetermined:(id)a0;
+ (void)garbageCollectionOperationComplete:(BOOL)a0 originalUnlockedDescriptors:(id)a1 originalLockedOverridableDescriptors:(id)a2 originalLockedNeverRemoveDescriptors:(id)a3 originalStagedDescriptors:(id)a4 reclaimedV2AssetCount:(long long)a5 reclaimedV2AssetSpace:(long long)a6 reclaimedUnlockedCount:(long long)a7 reclaimedUnlockedSpace:(long long)a8 reclaimedLockedOverridableCount:(long long)a9 reclaimedLockedOverridableSpace:(long long)a10 reclaimedLockedNeverRemoveCount:(long long)a11 reclaimedLockerNeverRemoveSpace:(long long)a12 reclaimedStagedCount:(long long)a13 reclaimedStagedSpace:(long long)a14 reclaimedMetadataBlockedCount:(long long)a15 reclaimedMetadataBlockedSpace:(long long)a16 totalReclaimedSpace:(long long)a17;
+ (void)handleReceivedPushNotifications:(id)a0;
+ (BOOL)isDeviceConsideredBeforeFirstUnlock;
+ (BOOL)isMessageNameForSetMessage:(id)a0;
+ (id)loadDescriptorsForJobSelector:(id)a0 promotingIfCurrentlyStaged:(id)a1 immediatelyPromotedDescriptor:(id *)a2;
+ (id)localAssetURLForAtomicEntry:(id)a0;
+ (id)localAssetURLForDescriptor:(id)a0 fromLocation:(id)a1;
+ (void)lockerResumed;
+ (void)memoryPressureMonitor:(long long)a0;
+ (id)migrateMismatchedPersistedDescriptorVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (id)migrateMismatchedPersistedSetAtomicInstanceVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (id)migrateMismatchedPersistedSetConfigurationVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (id)migrateMismatchedPersistedSetDescriptorVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (id)migrateMismatchedPersistedStateVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (id)newAtomicInstancesDownloadedForSetIdentifier:(id)a0;
+ (id)newSummaryForRequestMessage:(id)a0 includingSelector:(BOOL)a1;
+ (id)newSummaryForSetRequestMessage:(id)a0 includingSetAtomicInstance:(BOOL)a1;
+ (id)newestDownloadedForSetDescriptor:(id)a0;
+ (void)persistForJobSelector:(id)a0 persistingJobDescriptor:(id)a1 justDownloaded:(BOOL)a2 justPatched:(BOOL)a3 withFirstClientName:(id)a4;
+ (void)persistForJobSelector:(id)a0 persistingJobDescriptor:(id)a1 justPatched:(BOOL)a2 withFirstClientName:(id)a3;
+ (void)persistForJobSelector:(id)a0 persistingJobDescriptor:(id)a1 withFirstClientName:(id)a2;
+ (void)persistSetJobDescriptor:(id)a0 withCurrentSetStatus:(id)a1 withFirstClientName:(id)a2;
+ (void)postNotificationName:(id)a0 forAssetType:(id)a1 forAssetSpecifier:(id)a2 fromModule:(id)a3 fromLocation:(id)a4;
+ (void)postSetNotificationName:(id)a0 forAssetSetIdentifier:(id)a1 fromModule:(id)a2 fromLocation:(id)a3;
+ (long long)preferenceActivityIntervalSecs;
+ (BOOL)preferenceAlwaysPromoteStagedAssets;
+ (id)preferenceAsIfBootedOSIsBuildVersion;
+ (id)preferenceAsIfBootedOSIsOSVersion;
+ (BOOL)preferenceAutoAssetObserverIgnoreNetworkStatus;
+ (long long)preferenceBeforeFirstDefaultTimeoutSecs;
+ (long long)preferenceBeforeFirstPollSecs;
+ (id)preferenceConnectorBackoffRetryTimes;
+ (long long)preferenceConnectorInitialWaitSecs;
+ (long long)preferenceConnectorWaitBeforeRetrySecs;
+ (long long)preferenceLookupCacheAssetSelectorValidSecs;
+ (long long)preferenceLookupCacheSetConfigurationValidSecs;
+ (long long)preferencePushActivityIntervalSecs;
+ (BOOL)preferenceScheduledAlwaysNonDiscretionary;
+ (BOOL)preferenceScheduledBackupTriggersDisabled;
+ (id)replyMessageNameForRequest:(id)a0;
+ (void)schedulerEliminatedSelector:(id)a0;
+ (void)schedulerEliminatedSetDomainName:(id)a0 forAssetSetIdentifier:(id)a1;
+ (void)schedulerResumed;
+ (void)schedulerTriggeredNoActivity;
+ (void)schedulerTriggeredSelectors:(id)a0;
+ (void)schedulerTriggeredSets:(id)a0;
+ (id)selectDispatchQueue:(id)a0;
+ (BOOL)selectorToBeIncluded:(id)a0 basedOnControl:(id)a1;
+ (void)stagerCancelCurrentJob;
+ (void)stagerEliminatedSelector:(id)a0;
+ (void)stagerRequestAlreadyDownloadedDescriptors;
+ (void)stagerResumed:(id)a0;
+ (void)stagerStartJobDetermineIfAvailable:(id)a0 withAssetTargetOSVersion:(id)a1 withAssetTargetBuildVersion:(id)a2;
+ (void)stagerStartJobDownloadForStaging:(id)a0 withAssetTargetOSVersion:(id)a1 withAssetTargetBuildVersion:(id)a2;

- (id)init;
- (void).cxx_destruct;
- (id)summary;
- (id)_summary;
- (void)_initializeSUCore;
- (void)_initializeServerConnectionPolicy;
- (long long)actionUnknownAction:(id)a0 error:(id *)a1;
- (void)connectionClosedForClientID:(id)a0;
- (void)handleMessage:(id)a0 proxyObject:(id)a1 reply:(id /* block */)a2;
- (long long)performAction:(id)a0 onEvent:(id)a1 inState:(id)a2 withInfo:(id)a3 nextState:(id)a4 error:(id *)a5;
- (id)_combinedStatisticsWithStagerClientRepliesSuccess:(id)a0 withStagerClientRepliesFailure:(id)a1 withStagerTotalStaged:(id)a2 withStagerTotalUnstaged:(id)a3;
- (void)_removeFromPersistedActiveJobs:(id)a0;
- (long long)action_ObtainLookupGrant:(id)a0 error:(id *)a1;
- (id)atomicInstanceForSetDescriptor:(id)a0;
- (BOOL)jobToBeIncluded:(id)a0 basedOnControl:(id)a1;
- (void)loadPersistedSetAtomicInstances;
- (id)locateDownloadedByFullSelector:(id)a0;
- (id)_preInstalledRelocateAutoAssets;
- (void)_statsIncrementAutoJobsFinished;
- (long long)action_RemoveFinishedJob:(id)a0 error:(id *)a1;
- (long long)action_RouteClientClosed:(id)a0 error:(id *)a1;
- (id)atomicInstanceUUIDForNewSetJob:(id)a0;
- (void)handleSetControlClientScheduledSetJobSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (id)jobSelectorKey:(id)a0;
- (void)setDescriptorAddedPreInstalled:(id)a0;
- (BOOL)setPolicyValidate:(id)a0 fromLocation:(id)a1;
- (id)_autoAssetJobProgressNewValidatedCurrentStatus:(id)a0;
- (id)_autoAssetSetJobProgressNewValidatedCurrentStatus:(id)a0;
- (void)_awaitingResumeReduceToLatest;
- (void)_awaitingResumeRemoveType:(long long)a0;
- (long long)_bytesDownloadedForDescriptor:(id)a0;
- (BOOL)_doesClientRequestInvolveSetConfiguration:(id)a0;
- (BOOL)_doesEliminateSelector:(id)a0 matchAssetType:(id)a1 withAssetSpecifier:(id)a2 withAssetVersion:(id)a3 fromLocation:(id)a4;
- (void)_eliminateBegin:(id)a0 forAssetSelector:(id)a1 fromLocation:(id)a2;
- (void)_eliminateCompleteIfAllDone:(id)a0;
- (void)_eliminatePromotedNeverLocked:(id)a0 forAssetSelector:(id)a1;
- (BOOL)_haveSetAssetEntriesForSchedulerTriggered:(id)a0;
- (BOOL)_inDownloadsInFlight:(id)a0;
- (BOOL)_inMatchedTaskDescriptors:(id)a0 addingMatchingJobUUID:(id)a1;
- (void)_initializeAutoControl;
- (void)_initializeCachedPreferences;
- (void)_initializeConnectionServer;
- (BOOL)_isClientRequestForSetJob:(id)a0;
- (BOOL)_isClientRequestSubjectToElimination:(id)a0;
- (id)_latestDownloadedDescriptor:(id)a0 forAssetType:(id)a1 withAssetSpecifier:(id)a2;
- (id)_latestDownloadedDescriptor:(id)a0 forAssetType:(id)a1 withAssetSpecifier:(id)a2 matchingAssetVersion:(id)a3;
- (id)_limitToCheckAtomicEntries:(id)a0;
- (void)_logLookupGrantAwaiting:(id)a0 ofLookupGrant:(id)a1 message:(id)a2;
- (void)_logLookupGrantObtained:(id)a0 ofLookupGrant:(id)a1 message:(id)a2;
- (void)_logLookupGrantReleased:(id)a0 ofLookupGrant:(id)a1 message:(id)a2;
- (void)_logPersistedEntry:(id)a0 forComponentType:(id)a1 operation:(id)a2 forPersistedEntryID:(id)a3 forClientRequest:(id)a4 withJobUUID:(id)a5 withAssetDescriptor:(id)a6 baseForPatchDescriptor:(id)a7 message:(id)a8;
- (void)_logPersistedRemovedEntry:(id)a0 forComponentType:(id)a1 removedPersistedEntryID:(id)a2 removedDescriptor:(id)a3 message:(id)a4;
- (void)_logPersistedSetAtomicInstance:(id)a0 operation:(id)a1 forPersistedEntryID:(id)a2 withSetAtomicInstance:(id)a3 message:(id)a4;
- (void)_logPersistedSetAtomicInstanceRemoved:(id)a0 removedPersistedEntryID:(id)a1 removedSetAtomicInstance:(id)a2 message:(id)a3;
- (void)_logPersistedSetAtomicInstanceTableOfContents:(id)a0;
- (void)_logPersistedSetConfiguration:(id)a0 operation:(id)a1 forPersistedEntryID:(id)a2 withSetConfiguration:(id)a3 message:(id)a4;
- (void)_logPersistedSetConfigurationRemoved:(id)a0 removedPersistedEntryID:(id)a1 removedSetConfiguration:(id)a2 message:(id)a3;
- (void)_logPersistedSetConfigurationTableOfContents:(id)a0;
- (void)_logPersistedSetDescriptor:(id)a0 forComponentType:(id)a1 operation:(id)a2 forPersistedEntryID:(id)a3 forClientRequest:(id)a4 withJobUUID:(id)a5 withSetDescriptor:(id)a6 message:(id)a7;
- (void)_logPersistedSetDescriptorRemoved:(id)a0 forComponentType:(id)a1 removedPersistedEntryID:(id)a2 removedSetDescriptor:(id)a3 message:(id)a4;
- (void)_logPersistedSetDescriptorTableOfContents:(id)a0 forComponentType:(id)a1;
- (void)_logPersistedTableOfContents:(id)a0 forComponentType:(id)a1;
- (void)_logTrackedDescriptors:(id)a0 forAssetType:(id)a1 withAssetSpecifier:(id)a2 matchingAssetVersion:(id)a3;
- (void)_logTrackedSetDescriptors:(id)a0 forSetJobDescriptor:(id)a1;
- (id)_longSummary;
- (BOOL)_messageBlockedUntilDownloadManagerSync:(id)a0;
- (BOOL)_messageBlockedUntilFirstUnlock:(id)a0 forAssetSelector:(id)a1;
- (BOOL)_messageBlockedUntilFirstUnlock:(id)a0 forSetInstance:(id)a1;
- (BOOL)_messageShouldBeScheduled:(id)a0 forAssetSelector:(id)a1;
- (void)_moveFromAwaitingResumedInto:(id)a0 forSelector:(id)a1;
- (id)_newAtomicEntryIDsOtherThanDescriptor:(id)a0;
- (id)_newAtomicInstancesDownloadedForSetIdentifier:(id)a0;
- (id)_newTrimmedToAutoAssetsInFlight:(id)a0;
- (id)_newestVersionDownloaded:(id)a0;
- (id)_preInstalledAtomicInstanceDescriptors;
- (id)_preInstalledDescriptor:(id)a0 forAssetType:(id)a1 withAssetSpecifier:(id)a2;
- (void)_preInstalledMakeDescriptorAvailable:(id)a0;
- (void)_preInstalledMigrateAssets;
- (id)_preInstalledSetAtomicEntriesFromInstanceEntries:(id)a0;
- (void)_promotePreviouslyStagedNowDownloaded:(id)a0 forHistoryOperation:(long long)a1;
- (void)_reclaimDownloadedDescriptorsWhenJustDownloaded:(id)a0;
- (void)_refreshEliminate:(id)a0 withJobUUID:(id)a1;
- (void)_removeAllContentForEliminateTracker:(id)a0 unlessCurrentlyLocked:(id)a1;
- (void)_removeAllQueuedForEliminateSelector:(id)a0;
- (void)_removeAllUnlockedForOtherAtomicInstances:(id)a0;
- (void)_removeDescriptorFromFilesystem:(id)a0 forHistoryOperation:(long long)a1 firstClientName:(id)a2;
- (void)_removeDownloadedDescriptorsWithNewerDownloaded;
- (void)_removeJobFromDownloadsInFlight:(id)a0;
- (void)_removeUnlockedForOlderSelectorsWithoutVersion:(id)a0;
- (void)_requestDownloadManagerSync;
- (void)_routeAssetFinished:(id)a0 withEventInfo:(id)a1;
- (void)_routeAssetProgress:(id)a0 toCurrentJobByUUID:(id)a1 withDownloadProgress:(id)a2;
- (void)_routeCatalogFinished:(id)a0 withEventInfo:(id)a1;
- (void)_routeClientRequest:(id)a0 fromLocation:(id)a1;
- (void)_routeConfigFinished:(id)a0 withEventInfo:(id)a1;
- (id)_scheduleAndCreateSetConfiguration:(id)a0;
- (void)_schedulePushNotifications:(id)a0;
- (void)_scheduleSelector:(id)a0;
- (void)_scheduleSetConfiguration:(id)a0 withClientSetPolicy:(id)a1;
- (void)_scheduledAndRouteClientRequest:(id)a0 fromLocation:(id)a1;
- (BOOL)_selectorBeingEliminated:(id)a0 fromLocation:(id)a1;
- (BOOL)_setInstanceBeingEliminated:(id)a0 fromLocation:(id)a1;
- (BOOL)_setMessageCanCreateSetConfiguration:(id)a0;
- (BOOL)_setMessageInvolvesSchedulerPolicy:(id)a0;
- (BOOL)_setMessageShouldBeScheduled:(id)a0 forSetConfiguration:(id)a1 forLatestEventInfo:(id)a2;
- (void)_statsClearingAfterReporting;
- (id)_statsCombinedCopy:(BOOL)a0;
- (void)_statsIncrement:(id)a0 forClientRequest:(id)a1;
- (void)_statsIncrementAutoAssetJobsStarted;
- (void)_statsIncrementDownloadedForDescriptor:(id)a0;
- (void)_statsIncrementFailuresToStartJobs;
- (void)_statsIncrementPreviouslyDownloadedForDescriptor:(id)a0;
- (void)_statsIncrementPromotedForDescriptor:(id)a0;
- (void)_statsIncrementRemovedForDescriptor:(id)a0;
- (void)_statsIncrementResumedInFlightJobs;
- (void)_statsIncrementSchedulerTriggeredJobs;
- (void)_statsIncrementStagerDetermineJobsFinished;
- (void)_statsIncrementStagerDetermineJobsStarted;
- (void)_statsIncrementStagerDownloadJobsFinished;
- (void)_statsIncrementStagerDownloadJobsStarted;
- (void)_statsMaintainReporting;
- (void)_statsRestartNextMaintentanceReport;
- (BOOL)_taskDescriptorEncountered:(id)a0 inMatchedDescriptors:(id)a1;
- (void)_trackActiveDescriptor:(id)a0 operation:(id)a1 usingSelector:(id)a2 withJobUUID:(id)a3 triggeredByClientMessage:(id)a4 downloadingDescriptor:(id)a5 baseForPatchDescriptor:(id)a6 message:(id)a7;
- (void)_updateCurrentSetStatus:(id)a0 forSetIdentifier:(id)a1 withSetStatus:(id)a2;
- (id)_updateLatestSummary;
- (id)_updatePolicyForSelector:(id)a0;
- (BOOL)_updateTrackedDescriptor:(id)a0 fromLatestDescriptor:(id)a1;
- (long long)action_AdditionalSynced:(id)a0 error:(id *)a1;
- (long long)action_Before1stAssetFinished:(id)a0 error:(id *)a1;
- (long long)action_Before1stCatalogFinished:(id)a0 error:(id *)a1;
- (long long)action_Before1stConfigFinished:(id)a0 error:(id *)a1;
- (long long)action_EliminateSchedulerDone:(id)a0 error:(id *)a1;
- (long long)action_EliminateStagerDone:(id)a0 error:(id *)a1;
- (long long)action_FailClientTimedOut:(id)a0 error:(id *)a1;
- (long long)action_HandlePushNotifications:(id)a0 error:(id *)a1;
- (long long)action_IgnorePushNotifications:(id)a0 error:(id *)a1;
- (long long)action_InstallAssets:(id)a0 error:(id *)a1;
- (long long)action_IssueClientReplyJobResponse:(id)a0 error:(id *)a1;
- (long long)action_IssueClientReplySetJob:(id)a0 error:(id *)a1;
- (long long)action_LoadPersistedResumeLocker:(id)a0 error:(id *)a1;
- (long long)action_LogStatistics:(id)a0 error:(id *)a1;
- (long long)action_MigrateAssets:(id)a0 error:(id *)a1;
- (long long)action_PollDecideBefore1stUnlock:(id)a0 error:(id *)a1;
- (long long)action_PromoteResumeScheduler:(id)a0 error:(id *)a1;
- (long long)action_ProvidePersistedForJob:(id)a0 error:(id *)a1;
- (long long)action_QueueClientRequest:(id)a0 error:(id *)a1;
- (long long)action_QueueClientRequestBefore1st:(id)a0 error:(id *)a1;
- (long long)action_QueueDownloadManager:(id)a0 error:(id *)a1;
- (long long)action_ReleaseLookupGrant:(id)a0 error:(id *)a1;
- (long long)action_RemoveQueuedClient:(id)a0 error:(id *)a1;
- (long long)action_ResumeJobs:(id)a0 error:(id *)a1;
- (long long)action_ResumeJobsBefore1st:(id)a0 error:(id *)a1;
- (long long)action_ResumeScheduler:(id)a0 error:(id *)a1;
- (long long)action_ResumeStager:(id)a0 error:(id *)a1;
- (long long)action_RouteAssetFinished:(id)a0 error:(id *)a1;
- (long long)action_RouteCatalogFinished:(id)a0 error:(id *)a1;
- (long long)action_RouteClientRequest:(id)a0 error:(id *)a1;
- (long long)action_RouteConfigFinished:(id)a0 error:(id *)a1;
- (long long)action_ScheduleJobs:(id)a0 error:(id *)a1;
- (long long)action_ScheduleJobsBefore1st:(id)a0 error:(id *)a1;
- (long long)action_ScheduleSetJobs:(id)a0 error:(id *)a1;
- (long long)action_StagerAlreadyDownloaded:(id)a0 error:(id *)a1;
- (long long)action_StagerJobCancel:(id)a0 error:(id *)a1;
- (long long)action_StagerJobDoneDetermine:(id)a0 error:(id *)a1;
- (long long)action_StagerJobDoneDownload:(id)a0 error:(id *)a1;
- (long long)action_StagerJobStartDetermine:(id)a0 error:(id *)a1;
- (long long)action_StagerJobStartDownload:(id)a0 error:(id *)a1;
- (long long)action_StartUnlockPollingTimer:(id)a0 error:(id *)a1;
- (long long)action_SyncDecideBefore1st:(id)a0 error:(id *)a1;
- (long long)action_SyncInFlightDownloads:(id)a0 error:(id *)a1;
- (long long)action_SyncSkippedDecideBefore1st:(id)a0 error:(id *)a1;
- (long long)action_Synced:(id)a0 error:(id *)a1;
- (long long)action_SyncedResumeStager:(id)a0 error:(id *)a1;
- (long long)action_SyncedReviewBefore1st:(id)a0 error:(id *)a1;
- (long long)action_SyncedReviewUnlocked:(id)a0 error:(id *)a1;
- (void)addActiveJobs:(id)a0 basedOnControl:(id)a1;
- (void)addSuccessfullyDownloadedJobs:(id)a0 basedOnControl:(id)a1;
- (void)addToCurrentJobs:(id)a0 usingSelector:(id)a1 withJobUUID:(id)a2 triggeredByClientMessage:(id)a3 downloadingDescriptor:(id)a4 baseForPatchDescriptor:(id)a5 usingSetDescriptor:(id)a6;
- (void)atomicInstanceEliminate:(id)a0 forClientDomainName:(id)a1 forAssetSetIdentifier:(id)a2;
- (BOOL)atomicInstanceHasDownloadedSetDescriptor:(id)a0 verboseLogging:(BOOL)a1;
- (void)atomicInstanceLoadedFromPersisted:(id)a0 persistedEntryID:(id)a1;
- (id)atomicInstanceMatchingInfoInstance:(id)a0 withSetInfoInstance:(id)a1;
- (id)atomicInstanceNewEntryIDForSetAtomicInstance:(id)a0;
- (id)atomicInstanceNewIdentifierForSetAtomicInstance:(id)a0;
- (id)atomicInstanceNewSetAtomicInstance:(id)a0 forClientDomainName:(id)a1 forSetClientName:(id)a2 forAssetSetIdentifier:(id)a3 representingInstanceEntries:(id)a4 recoveringAtomicInstanceUUID:(id)a5 asSubAtomicFrom:(id)a6;
- (id)atomicInstanceNewSetAtomicInstance:(id)a0 forSetInfoInstance:(id)a1 asSubAtomicFrom:(id)a2;
- (id)atomicInstanceNewSetAtomicInstance:(id)a0 recoveringForSetDescriptor:(id)a1;
- (id)atomicInstanceNewSubAtomicFromAtomic:(id)a0 forSubsetInfoInstance:(id)a1 error:(id *)a2;
- (long long)atomicInstanceNextCreationIndex:(id)a0 forClientDomainName:(id)a1 forAssetSetIdentifier:(id)a2;
- (void)atomicInstanceRemove:(id)a0 setAtomicInstanceUUID:(id)a1;
- (void)atomicInstanceRemovedSetJob:(id)a0;
- (void)atomicInstanceTrackSetDescriptor:(id)a0 fromLocation:(id)a1 forSpecificAtomicInstance:(id)a2;
- (id)atomicInstanceUUIDArrayForSetDescriptor:(id)a0;
- (id)atomicInstanceUUIDFromCurrentStatus:(id)a0;
- (id)buildFoundResponseMessage:(id)a0 forClientRequest:(id)a1 withFoundDescriptor:(id)a2 withInstance:(id)a3 withDesire:(id)a4 fromLocation:(id)a5;
- (id)buildSetFoundResponseMessage:(id)a0 forClientRequest:(id)a1 withFoundSetDescriptor:(id)a2 withSubAtomicInstance:(id)a3 forLatestDownloaded:(BOOL)a4 withInstance:(id)a5 withDesire:(id)a6 fromLocation:(id)a7;
- (id)chooseNewerSetDescriptor:(id)a0 considering:(id)a1;
- (id)chooseNewerSetStatus:(id)a0 comparingTo:(id)a1;
- (void)clearDownloadedFromSetStatus:(id)a0 forClientDomainName:(id)a1 forAssetSetIdentifier:(id)a2;
- (BOOL)clientRequestIndicatesNoWait:(id)a0;
- (id)clientRequestMessageDesire:(id)a0;
- (id)clientRequestMessageInstance:(id)a0;
- (id)clientRequestMessageName:(id)a0;
- (id)clientRequestMessageSetDesire:(id)a0;
- (id)clientRequestMessageSetEnd:(id)a0;
- (id)clientRequestMessageSetInstance:(id)a0 withEventInfo:(id)a1;
- (id)clientRequestMessageSetPolicy:(id)a0;
- (long long)clientRequestTimeoutSecs:(id)a0 timeoutWasSpecified:(BOOL *)a1;
- (void)clientRequestsAwaitingDispatchAll:(id)a0;
- (void)clientRequestsAwaitingSyncToAwaitingFirstUnlock:(id)a0;
- (id)currentJobBySelector:(id)a0;
- (id)currentJobByUUID:(id)a0 fromLocation:(id)a1 notFoundCode:(long long)a2 notFoundReason:(id)a3;
- (id)currentJobByUUID:(id)a0 potentiallyResumingJob:(id)a1 withOriginalSelector:(id)a2 fromLocation:(id)a3 notFoundCode:(long long)a4 notFoundReason:(id)a5 downloadingDescriptor:(id)a6 baseForPatchDescriptor:(id)a7;
- (id)currentSetStatusFromJobInformation:(id)a0;
- (BOOL)doesSetDescriptor:(id)a0 alignWithSetConfiguration:(id)a1;
- (BOOL)doesSetDescriptor:(id)a0 satisfyAllAutoAssetEntries:(id)a1;
- (id)findAtomicEntryForAssetType:(id)a0 forAssetSpecifier:(id)a1 representedByDescriptor:(id)a2;
- (id)findAtomicEntryForAssetType:(id)a0 forAssetSpecifier:(id)a1 representedByStatus:(id)a2;
- (id)findSetEntryForAssetType:(id)a0 forAssetSpecifier:(id)a1 representedByConfiguration:(id)a2;
- (void)handleClientAlterLockOperation:(id)a0 forAutoJob:(id)a1;
- (BOOL)handleClientCheckForNewer:(id)a0 forAutoJob:(id)a1 instance:(id)a2 desire:(id)a3 fromLocation:(id)a4;
- (void)handleClientCurrentStatusRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleClientEliminateAllForAssetTypeRequest:(id)a0;
- (void)handleClientEliminateAllForSelectorRequest:(id)a0;
- (void)handleClientEliminatePromotedNeverLockedForSelectorRequest:(id)a0;
- (BOOL)handleClientLockContent:(id)a0 forAutoJob:(id)a1 instance:(id)a2 desire:(id)a3 fromLocation:(id)a4;
- (BOOL)handleClientPotentialJob:(id)a0 forAutoJob:(id)a1 fromLocation:(id)a2;
- (BOOL)handleClientPotentialSetJob:(id)a0 forAutoJob:(id)a1 fromLocation:(id)a2;
- (void)handleControlClientActiveJobSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientControlStatisticsRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientForceGlobalAbandonRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientForceGlobalForgetRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientForceGlobalPurgeRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientForceGlobalUnlockRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientKnownAssetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientLockedAssetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientScheduledJobSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleControlClientSimulateSetJobOperation:(id)a0;
- (void)handleControlClientSimulatedCacheDeleteDetermineReclaimableRequest:(id)a0;
- (void)handleControlClientSimulatedCacheDeleteReclaimSpaceRequest:(id)a0;
- (void)handleControlClientStagedAssetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetClientAlterEntriesRepresentingAtomicRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetClientAssetSetForStagingRequest:(id)a0 forAutoJob:(id)a1;
- (BOOL)handleSetClientCheckAtomic:(id)a0 forAutoJob:(id)a1 instance:(id)a2 desire:(id)a3 fromLocation:(id)a4;
- (void)handleSetClientContinueAtomicLockRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetClientCurrentStatusRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetClientEliminateAtomicRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetClientEndAtomicLockRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetClientEndAtomicLocksForClientRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetClientFormSubAtomicRequest:(id)a0 forAutoJob:(id)a1;
- (BOOL)handleSetClientLockAtomic:(id)a0 forAutoJob:(id)a1 instance:(id)a2 desire:(id)a3 fromLocation:(id)a4;
- (void)handleSetClientNeedForAtomicRequest:(id)a0 fromLocation:(id)a1;
- (void)handleSetControlClientActiveSetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetControlClientAssetSetsOverviewRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetControlClientInstanceInfoRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetControlClientKnownAssetSetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetControlClientLockedAssetSetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleSetControlClientStagedAssetSetSummaryRequest:(id)a0 forAutoJob:(id)a1;
- (void)handleStagingClientDetermineAllAvailableRequest:(id)a0;
- (void)handleStagingClientDownloadAllRequest:(id)a0;
- (void)handleStagingClientPurgeAllRequest:(id)a0;
- (void)initialStatusForJob:(id)a0 usingSelector:(id)a1 withJobUUID:(id)a2 downloadingDescriptor:(id)a3 baseForPatchDescriptor:(id)a4;
- (void)initialStatusForSetJob:(id)a0 withJobUUID:(id)a1 usingSetDescriptor:(id)a2 usingSetPolicy:(id)a3;
- (BOOL)isSetDescriptor:(id)a0 coveredBySetDescriptorStatus:(id)a1;
- (void)issueBuiltResponseForEventInfo:(id)a0 issuingResponseMessage:(id)a1 withResponseError:(id)a2;
- (void)issueResponseForEventInfo:(id)a0 withAutoAssetError:(id)a1 fromAction:(id)a2 withDescription:(id)a3;
- (void)issueResponseForEventInfo:(id)a0 withErrorCode:(long long)a1 fromAction:(id)a2 withDescription:(id)a3;
- (void)issueResponseToClientRequest:(id)a0 issuingResponseMessage:(id)a1 withResponseError:(id)a2;
- (id)jobControlInformationForSelector:(id)a0;
- (BOOL)jobDescriptorInFlightNowOnFilesystem:(id)a0;
- (BOOL)jobDescriptorOnFilesystemValidated:(id)a0;
- (id)jobToBeGivenGrant:(id)a0;
- (void)loadPersistedActiveJobs;
- (void)loadPersistedCrossCheckTrim;
- (void)loadPersistedCrossCheckTrimAtomicInstances;
- (void)loadPersistedDescriptors;
- (void)loadPersistedRecoverLost;
- (void)loadPersistedSetActiveJobDescriptors;
- (void)loadPersistedSetConfigurations;
- (void)loadPersistedSetDownloadedDescriptors;
- (id)locateActiveAutoJobForSetDescriptor:(id)a0;
- (id)locateActiveJobDescriptorBySelector:(id)a0;
- (long long)locateDownloadedCurrentDownloadedCount;
- (id)locateDownloadedNewAllBySelector;
- (id)locateDownloadedNewBySelectorForAssetType:(id)a0;
- (id)locateSetAtomicInstanceByInstanceUUID:(id)a0;
- (id)locateSetConfigurationByClientDomain:(id)a0 forAssetSetIdentifier:(id)a1;
- (id)locateSetDescriptorActiveJobByAtomicInstanceUUID:(id)a0;
- (id)locateSetDescriptorActiveJobByClientDomain:(id)a0 forAssetSetIdentifier:(id)a1;
- (id)locateSetDescriptorActiveJobPreferringByAtomicInstance:(id)a0 elseByClientDomain:(id)a1 forAssetSetIdentifier:(id)a2;
- (id)locateSetDescriptorDownloadedByAtomicInstanceUUID:(id)a0;
- (id)locateSetDescriptorDownloadedByClientDomain:(id)a0 forAssetSetIdentifier:(id)a1;
- (id)locateSetDescriptorDownloadedLatest:(id)a0 forAssetSetIdentifier:(id)a1;
- (id)locateSetDescriptorDownloadedPreferringByAtomicInstance:(id)a0 elseByClientDomain:(id)a1 forAssetSetIdentifier:(id)a2;
- (id)locateSetDescriptorsDownloaded;
- (id)locateSetJobForClientDomain:(id)a0 byIdentifier:(id)a1;
- (id)locateSetStatusByInstance:(id)a0;
- (id)locateSetStatusForDomainName:(id)a0 byIdentifier:(id)a1;
- (id)locateSetStatusPreferringByInstance:(id)a0 elseByClientDomain:(id)a1 forAssetSetIdentifier:(id)a2;
- (id)newAssetSetStatus:(id)a0 forReason:(id)a1 forClientDomain:(id)a2 forAssetSetIdentifier:(id)a3 withAtomicInstancesDownloaded:(id)a4 withCatalogCachedAssetSetID:(id)a5 withCatalogDownloadedFromLive:(id)a6 withCatalogLastTimeChecked:(id)a7 withCatalogPostedDate:(id)a8 withNewerAtomicInstanceDiscovered:(id)a9 withNewerDiscoveredAtomicEntries:(id)a10 withLatestDownloadedAtomicInstance:(id)a11 withLatestDowloadedAtomicInstanceEntries:(id)a12 withDownloadedCatalogCachedAssetSetID:(id)a13 withDownloadedCatalogDownloadedFromLive:(id)a14 withDownloadedCatalogLastTimeChecked:(id)a15 withDownloadedCatalogPostedDate:(id)a16 withCurrentNotifications:(id)a17 withCurrentNeedPolicy:(id)a18 withSchedulerPolicy:(id)a19 withStagerPolicy:(id)a20 withDownloadUserInitiated:(BOOL)a21 withDownloadProgress:(id)a22 withDownloadedNetworkBytes:(long long)a23 withDownloadedFilesystemBytes:(long long)a24 extendingWithCurrentLockUsage:(BOOL)a25 withSelectorsForStaging:(id)a26 withAvailableForUseError:(id)a27 withNewerVersionError:(id)a28;
- (id)newAssetStatusForSelector:(id)a0 withNotifications:(id)a1 withAvailableForUseAttributes:(id)a2 withNewerVersionAttributes:(id)a3 withNeverBeenLocked:(BOOL)a4 withDownloadUserInitiated:(BOOL)a5 withDownloadProgress:(id)a6 withDownloadedNetworkBytes:(long long)a7 withDownloadedFilesystemBytes:(long long)a8 withDownloadedAsPatch:(BOOL)a9 withPatchedFromBaseSelector:(id)a10 withPatchedFromBaseFilesystemBytes:(long long)a11 withPatchingAttempted:(BOOL)a12 withStagedPriorToAvailable:(BOOL)a13 withStagedFromOSVersion:(id)a14 withStagedFromBuildVersion:(id)a15 extendingWithCurrentLockUsage:(BOOL)a16 withAvailableForUseError:(id)a17 withPatchingAttemptError:(id)a18 withNewerVersionError:(id)a19;
- (id)newAtomicInstancesDownloadedForDescriptor:(id)a0;
- (id)newSetDescriptorFromAlreadyDownloaded:(id)a0 forSetInfoInstance:(id)a1 fromDownloadedSetDescriptor:(id)a2 forAtomicInstance:(id)a3;
- (id)newSetDescriptorIfOtherSatisfying:(id)a0 forSetInfoInstance:(id)a1;
- (id)newSetDescriptorLimitedToCheckInformation:(id)a0;
- (id)newSetEntryIDForClientDomain:(id)a0 forAssetSetIdentifier:(id)a1;
- (id)newSetEntryIDForClientDomain:(id)a0 forAssetSetIdentifier:(id)a1 ofAtomicInstance:(id)a2;
- (id)newSetInfoLimitedToCheckInformation:(id)a0 forAssetSetIdentifier:(id)a1 fromSetInfoFound:(id)a2;
- (id)newSetLockUsageMapKeyForClientDomain:(id)a0 forSetIdentifier:(id)a1;
- (id)notifyLockerAsIndicatedByJob:(id)a0;
- (id)notifyLockerAsIndicatedBySetJob:(id)a0;
- (void)persistSetDescriptorActiveJob:(id)a0 fromLocation:(id)a1;
- (void)persistSetDescriptorDownloadedJob:(id)a0 fromLocation:(id)a1;
- (id)preInstalledSetDescriptorForSetInstance:(id)a0 dueToMessageName:(id)a1;
- (void)promoteAnyPreviouslyStagedNowDownloaded:(id)a0;
- (void)removeActiveJobForFullSelector:(id)a0 removingFullSelector:(id)a1 alsoRemovingNoVersionSelector:(id)a2;
- (void)removeClientRequest:(id)a0 fromLocation:(id)a1;
- (void)removeCurrentJob:(id)a0 schedulerInvolved:(BOOL)a1 potentialNetworkFailure:(BOOL)a2 fromLocation:(id)a3;
- (void)removeCurrentSetJob:(id)a0 schedulerInvolved:(BOOL)a1 potentialNetworkFailure:(BOOL)a2 fromLocation:(id)a3;
- (void)removeSetDescriptorActiveJobByAtomicInstanceUUID:(id)a0;
- (void)removeSetDescriptorActiveJobByClientDomain:(id)a0 forAssetSetIdentifier:(id)a1 fromLocation:(id)a2;
- (void)removeSetDescriptorDownloaded:(id)a0 fromLocation:(id)a1;
- (void)resumeJobsWhenBeforeFirstUnlock:(BOOL)a0;
- (void)resumeSetJobsWhenBeforeFirstUnlock:(BOOL)a0;
- (BOOL)setConfiguration:(id)a0 matchesAssetEntriesFromInfoInstance:(id)a1;
- (id)setConfigurationAssetEntries:(id)a0;
- (id)setConfigurationAssetEntries:(id)a0 forAssetSetIdentifier:(id)a1;
- (void)setConfigurationEliminate:(id)a0 forClientDomainName:(id)a1 forAssetSetIdentifier:(id)a2;
- (id)setConfigurationFromMessageName:(id)a0 withInfoInstance:(id)a1 errorCode:(long long *)a2 errorDescription:(id *)a3;
- (void)setConfigurationLoadedFromPersisted:(id)a0 persistedEntryID:(id)a1;
- (id)setConfigurationNewEntryIDForInfoInstance:(id)a0;
- (id)setConfigurationNewEntryIDForSetConfiguration:(id)a0;
- (id)setConfigurationNewSetConfiguration:(id)a0 forSetInfoInstance:(id)a1 dueToMessageName:(id)a2;
- (id)setConfigurationSelectUsingInfoInstance:(id)a0 dueToMessageName:(id)a1;
- (BOOL)setDescriptorAllEntriesDownloaded:(id)a0;
- (void)setDescriptorDownloadedLoadedFromPersisted:(id)a0 persistedEntryID:(id)a1;
- (void)setDescriptorEliminate:(id)a0 triggeredByClient:(id)a1 forClientDomainName:(id)a2 forAssetSetIdentifier:(id)a3;
- (BOOL)setDescriptorLocked:(id)a0;
- (id)setDescriptorNewEntryIDForDownloaded:(id)a0;
- (id)setJobInstanceKeyForSetInstance:(id)a0;
- (id)setJobInstanceKeyFromSetDescriptor:(id)a0 forLatestDownloaded:(BOOL)a1;
- (id)setJobInstanceKeyFromSetStatus:(id)a0 forLatestDownloaded:(BOOL)a1;
- (void)setLockUsageMapEliminateForClientDomain:(id)a0 forSetIdentifier:(id)a1;
- (void)setLockUsageMapEndedLockForSetDescriptor:(id)a0 forLockReason:(id)a1 endedLockCount:(long long)a2;
- (id)setLockUsageMapForClientDomain:(id)a0 forSetIdentifier:(id)a1;
- (id)setLockUsageMapForSetDescriptor:(id)a0;
- (void)setLockUsageMapLockedSetDescriptor:(id)a0 forLockReason:(id)a1;
- (BOOL)timerStartForRequest:(id)a0 fromLocation:(id)a1;
- (void)timerStopForClientRequest:(id)a0 fromLocation:(id)a1;
- (void)trackClientRequest:(id)a0;
- (void)trackDescriptor:(id)a0 persisting:(BOOL)a1 fromLocation:(id)a2 changedWhileTerminated:(BOOL)a3 changedNeverBeenLocked:(BOOL)a4 historyOperation:(long long)a5 firstClientName:(id)a6;
- (void)trackDescriptorForgetAssetSelector:(id)a0 forHistoryOperation:(long long)a1 firstClientName:(id)a2;
- (void)trackDescriptorForgetAssetType:(id)a0 firstClientName:(id)a1;
- (void)trackDescriptorForgetAssetType:(id)a0 forAssetSpecifier:(id)a1 firstClientName:(id)a2;
- (void)trackSetDescriptor:(id)a0 fromLocation:(id)a1 forLatestDownloaded:(BOOL)a2 forSpecificAtomicInstance:(id)a3 changedWhileTerminated:(BOOL)a4 changedNeverBeenLocked:(BOOL)a5 historyOperation:(long long)a6 firstClientName:(id)a7;
- (void)updateAssociatedStatus:(id)a0 forActiveJobUUID:(id)a1 withLatestJobStatus:(id)a2;
- (id)updateAutoAssetSetStatus:(id)a0 forClientDomain:(id)a1 forAssetSetIdentifier:(id)a2 forJobResponse:(id)a3 withResponseError:(id)a4;
- (void)updateAutoAssetSetStatus:(id)a0 forSetDescriptor:(id)a1;
- (id)updateAutoAssetStatus:(id)a0 forActiveJobUUID:(id)a1 forJobResponse:(id)a2 withResponseError:(id)a3;
- (void)updateAutoAssetStatus:(id)a0 forActiveJobUUID:(id)a1 withLatestJobStatus:(id)a2 fromLocation:(id)a3;

@end
