@class RTPersistenceManager, RTLocationStore, RTDeviceLocationPredictor, RTFingerprintManager, RTAssetManager, RTLocationManager, RTAuthorizationManager, RTAccountManager, RTVisitManager, RTLearnedLocationManager, NSString, RTHintManager, RTScenarioTriggerManager, RTEntitlementProvider, RTBuildingPolygonManager, NSObject, RTWorkoutRouteManager, RTWorkoutScheduler, RTDiagnostics, RTIntermittentGNSSManager, RTMotionActivityManager, NSXPCConnection, RTEventModelProvider, RTVehicleLocationProvider, RTPurgeManager, RTLearnedLocationStore;
@protocol OS_dispatch_queue;

@interface RTDaemonClientInternal : NSObject <RTDaemonInternalProtocol, NSXPCConnectionDelegate>

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) RTEntitlementProvider *entitlementProvider;
@property (retain, nonatomic) RTAccountManager *accountManager;
@property (retain, nonatomic) RTAssetManager *assetManager;
@property (retain, nonatomic) RTAuthorizationManager *authorizationManager;
@property (retain, nonatomic) RTBuildingPolygonManager *buildingPolygonManager;
@property (retain, nonatomic) RTDeviceLocationPredictor *deviceLocationPredictor;
@property (retain, nonatomic) RTDiagnostics *diagnostics;
@property (retain, nonatomic) RTEventModelProvider *eventModelProvider;
@property (retain, nonatomic) RTFingerprintManager *fingerprintManager;
@property (retain, nonatomic) RTHintManager *hintManager;
@property (retain, nonatomic) RTIntermittentGNSSManager *intermittentGNSSManager;
@property (retain, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (retain, nonatomic) RTLearnedLocationStore *learnedLocationStore;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) RTLocationStore *locationStore;
@property (retain, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (retain, nonatomic) RTPersistenceManager *persistenceManager;
@property (retain, nonatomic) RTPurgeManager *purgeManager;
@property (retain, nonatomic) RTScenarioTriggerManager *scenarioTriggerManager;
@property (retain, nonatomic) RTVehicleLocationProvider *vehicleLocationProvider;
@property (retain, nonatomic) RTVisitManager *visitManager;
@property (retain, nonatomic) RTWorkoutRouteManager *workoutRouteManager;
@property (retain, nonatomic) RTWorkoutScheduler *workoutScheduler;
@property (retain, nonatomic) NSXPCConnection *xpcConnection;
@property (copy, nonatomic) NSString *executablePath;
@property (nonatomic) int processIdentifier;
@property (copy, nonatomic) NSString *signingIdentifier;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void).cxx_destruct;
- (void)connection:(id)a0 handleInvocation:(id)a1 isReply:(BOOL)a2;
- (void)forceRelabeling:(id /* block */)a0;
- (id)initWithQueue:(id)a0 accountManager:(id)a1 assetManager:(id)a2 authorizationManager:(id)a3 buildingPolygonManager:(id)a4 deviceLocationPredictor:(id)a5 diagnostics:(id)a6 eventModelProvider:(id)a7 fingerprintManager:(id)a8 hintManager:(id)a9 intermittentGNSSManager:(id)a10 learnedLocationManager:(id)a11 learnedLocationStore:(id)a12 locationManager:(id)a13 locationStore:(id)a14 motionActivityManager:(id)a15 persistenceManager:(id)a16 purgeManager:(id)a17 scenarioTriggerManager:(id)a18 vehicleLocationProvider:(id)a19 visitManager:(id)a20 workoutRouteManager:(id)a21 workoutScheduler:(id)a22;
- (void)fetchDataVaultPath:(id /* block */)a0;
- (void)fetchPathToBackupWithReply:(id /* block */)a0;
- (void)fetchAllLocationsOfInterestWithReply:(id /* block */)a0;
- (void)forceSequentialClusterIdentification:(id /* block */)a0;
- (void)injectLocationOfInterest:(id)a0 reply:(id /* block */)a1;
- (void)injectVisit:(id)a0 locationOfInterest:(id)a1 reply:(id /* block */)a2;
- (void)clearAllLocationsOfInterestWithReply:(id /* block */)a0;
- (void)fetchLocationsOfInterestWithVisitsWithinDistance:(id)a0 location:(id)a1 reply:(id /* block */)a2;
- (void)fetchStoredLocationsCountFromDate:(id)a0 toDate:(id)a1 uncertainty:(double)a2 limit:(unsigned long long)a3 reply:(id /* block */)a4;
- (void)fetchVisitsWithReply:(id /* block */)a0;
- (void)forcePlaceTypeClassificationWithReply:(id /* block */)a0;
- (void)simulateScenarioTrigger:(id)a0 reply:(id /* block */)a1;
- (void)forceUpdateAssetMetadataWithReply:(id /* block */)a0;
- (void)updateAssetServerURL:(id)a0 assetType:(id)a1 reply:(id /* block */)a2;
- (void)forceEventModelRefreshWithReply:(id /* block */)a0;
- (void)storeHints:(id)a0 reply:(id /* block */)a1;
- (void)injectLocations:(id)a0 reply:(id /* block */)a1;
- (void)injectSignalForSignalGeneratorOptions:(id)a0 reply:(id /* block */)a1;
- (void)updateTransitionWithIdentifier:(id)a0 modeOfTransportation:(long long)a1 reply:(id /* block */)a2;
- (void)reconstructTransitionsWithReply:(id /* block */)a0;
- (void)simulateVisit:(id)a0 reply:(id /* block */)a1;
- (void)fetchVisitsBetweenStartDate:(id)a0 endDate:(id)a1 reply:(id /* block */)a2;
- (void)injectRealtimeVisit:(id)a0 reply:(id /* block */)a1;
- (void)performImportMirroringRequest:(id /* block */)a0;
- (void)performExportMirroringRequest:(id /* block */)a0;
- (void)performZoneResetMirroringRequest:(id /* block */)a0;
- (void)mirroringDelegateSetupState:(id /* block */)a0;
- (void)tearDownPersistenceStack:(id /* block */)a0;
- (void)submitHintAtLocation:(id)a0 reply:(id /* block */)a1;
- (void)fetchFusionCandidatesForVisitIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchInferredMapItemForVisitIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)queryProvider:(id)a0 options:(id)a1 reply:(id /* block */)a2;
- (void)fetchFingerprintsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchWiFiAccessPointsForFingerprint:(id)a0 reply:(id /* block */)a1;
- (void)injectFingerprintWithIdentifier:(id)a0 settledState:(unsigned long long)a1 start:(id)a2 reply:(id /* block */)a3;
- (void)injectFingerprintWithSettledState:(BOOL)a0 start:(id)a1 reply:(id /* block */)a2;
- (void)injectWiFiAccessPointWithMac:(id)a0 rssi:(long long)a1 channel:(long long)a2 age:(double)a3 date:(id)a4 reply:(id /* block */)a5;
- (void)fetchFMCEnabledWithReply:(id /* block */)a0;
- (void)fetchMotionActivitiesFromStartDate:(id)a0 endDate:(id)a1 reply:(id /* block */)a2;
- (void)submitMetrics:(id)a0 metricName:(id)a1 reply:(id /* block */)a2;
- (void)submitTransitMetricsWithReply:(id /* block */)a0;
- (void)expireLifetimeOfVisitsWithIdentifiers:(id)a0 expirationDate:(id)a1 reply:(id /* block */)a2;
- (void)extendLifetimeOfVisitsWithIdentifiers:(id)a0 toExpireOn:(id)a1 reply:(id /* block */)a2;
- (void)logDatabasesWithReply:(id /* block */)a0;
- (void)forceProcessWorkoutsClearClusters:(BOOL)a0 clearExistingDistanceMatrix:(BOOL)a1 buildDistanceMatrix:(BOOL)a2 syncClustersToHealhtKit:(BOOL)a3 syncClustersToWatch:(BOOL)a4 filteringDistanceThreshold:(double)a5 topNWorkouts:(unsigned long long)a6 isSchedulerTriggered:(BOOL)a7 reply:(id /* block */)a8;
- (void)updateRelevanceScoresWithReply:(id /* block */)a0;
- (void)processNewlyAddedWorkout:(id)a0 reply:(id /* block */)a1;
- (void)deleteWorkout:(id)a0 reply:(id /* block */)a1;
- (void)displayWorkoutDistanceRecordsWithHandler:(id /* block */)a0;
- (void)fetchBuildingPolygonsFromLocations:(id)a0 radius:(double)a1 limit:(unsigned long long)a2 reply:(id /* block */)a3;
- (void)fetchIntermittentGNSSRegistrationStateWithReply:(id /* block */)a0;
- (void)updateIntermittentGNSSRegistrationOverrideState:(unsigned long long)a0 reply:(id /* block */)a1;

@end
