@class RTIntermittentGNSSManagerMetrics, NSDate, RTMotionActivityManager, RTVehicleLocationProvider, RTInvocationDispatcher, RTDefaultsManager, NSMutableArray, RTPlatform, RTTimerManager, RTWiFiManager, RTLearnedLocationManager, RTLocationManager, RTTimer, RTDistanceCalculator;

@interface RTIntermittentGNSSManager : RTService

@property (nonatomic) long long lastRemoteStatus;
@property (nonatomic) unsigned long long remoteStatusChecklist;
@property (retain, nonatomic) RTInvocationDispatcher *remoteStatusDispatcher;
@property (retain, nonatomic) RTTimer *remoteStatusTimeoutTimer;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) RTIntermittentGNSSManagerMetrics *metrics;
@property (retain, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (retain, nonatomic) RTPlatform *platform;
@property (retain, nonatomic) RTTimerManager *timerManager;
@property (retain, nonatomic) RTVehicleLocationProvider *vehicleLocationProvider;
@property (retain, nonatomic) RTWiFiManager *wifiManager;
@property (retain, nonatomic) RTTimer *conditionCheckTimer;
@property (retain, nonatomic) RTTimer *wifiLocationStarvedTimer;
@property (retain, nonatomic) RTTimer *wifiScanTimer;
@property (retain, nonatomic) RTDistanceCalculator *distanceCalculator;
@property (retain, nonatomic) NSDate *lastRegisteredForIntermittentGNSSVariableFlipDate;
@property (retain, nonatomic) NSDate *lastLOINearbyCheckDate;
@property (retain, nonatomic) NSDate *lastSettledStateChangeDate;
@property (retain, nonatomic) NSDate *lastWifiLocationDate;
@property (retain, nonatomic) NSDate *lastDenseWifiScanResultDate;
@property (nonatomic) BOOL awayFromFrequentlyVisitedLOI;
@property (nonatomic) BOOL motionActivityTypeSatisfied;
@property (nonatomic) BOOL registeredForIntermittentGNSS;
@property (nonatomic) BOOL settledStateLOIVerified;
@property (nonatomic) BOOL signalEnvironmentAtRisk;
@property (nonatomic) BOOL unsettled;
@property (nonatomic) BOOL completedInitialWifiScan;
@property (nonatomic) BOOL wifiLocationStarved;
@property (nonatomic) BOOL activeWifiScan;
@property (nonatomic) double totalDailyDuration;
@property (nonatomic) int currentSignalEnvironment;
@property (nonatomic) int previousSignalEnvironment;
@property (retain, nonatomic) NSMutableArray *accessPoints;
@property (nonatomic) unsigned long long currentDominantMotionType;
@property (nonatomic) unsigned long long intermittentGNSSOverrideState;

+ (BOOL)validLocation:(id)a0;
+ (id)overrideStateToString:(unsigned long long)a0;
+ (BOOL)supportsNotificationName:(id)a0;

- (void)onMotionActivityManagerNotification:(id)a0;
- (void)fetchRemoteStatusWithHandler:(id /* block */)a0;
- (void)onDailyMetricsNotification:(id)a0;
- (void)fetchIntermittentGNSSRegistrationStateWithHandler:(id /* block */)a0;
- (void)_shutdownWithHandler:(id /* block */)a0;
- (void)_considerRegisteringForIntermittentGNSS;
- (void)_setup;
- (void)onNoOpLocationNotification:(id)a0;
- (id)_locationsOfInterestNearLocation:(id)a0 error:(id *)a1;
- (void)onWifiScanResultsNotification:(id)a0;
- (void)_updateSignalEnvironmentRiskStatus:(int)a0;
- (void)updateIntermittentGNSSRegistrationOverrideState:(unsigned long long)a0 handler:(id /* block */)a1;
- (id)initWithDefaultsManager:(id)a0 learnedLocationManager:(id)a1 locationManager:(id)a2 motionActivityManager:(id)a3 platform:(id)a4 vehicleLocationProvider:(id)a5 wifiManager:(id)a6;
- (BOOL)_frequentlyVisitedLocationOfInterest:(id)a0;
- (void)_checkWifiDenseArea;
- (void)_onLocationStarvedTimerExpiry;
- (long long)_remoteStatusForCurrentState;
- (id)_initializeWifiLocationStarvedTimer;
- (void).cxx_destruct;
- (BOOL)_dutyCyclingConditionMet;
- (BOOL)_wifiDenseConditionsMet;
- (void)_registerForRhythmicNonWakingLocation;
- (void)_unregisterForRhythmicNonWakingLocation;
- (void)_updateWifiLocationAvailabilityStatus:(id)a0;
- (void)_processWifiScanResults;
- (id)initWithDefaultsManager:(id)a0 learnedLocationManager:(id)a1 locationManager:(id)a2 motionActivityManager:(id)a3 platform:(id)a4 timerManager:(id)a5 vehicleLocationProvider:(id)a6 wifiManager:(id)a7;
- (BOOL)_motionActivityConditionsSatisifed:(id)a0;
- (void)_completeRemoteStatusChecklistItem:(unsigned long long)a0;
- (BOOL)platformSupported;
- (void)onLeechedLocationNotification:(id)a0;
- (void)onVehicleEventNotification:(id)a0;
- (void)_updateWifiLocationStarvedTimer;
- (void)_updateLocationNearLOI:(id)a0;

@end
