@class NSDictionary, RTDefaultsManager, RTMapsSupportManager, RTMapServiceManager, RTDataSerializer, NSMutableArray, RTVisitManager, NSString, RTLearnedLocationManager, RTXPCActivityManager, RTXPCTimerAlarm, RTPredictedContextStore, NSMutableDictionary, RTPlatform, RTFeatureExtractor, RTDistanceCalculator, RTNavigationManager, PCAlgorithms, RTPredictedContextMetricsManager, RTEventManager, RTPredictedContextResult, RTMotionActivityManager, RTDataProtectionManager, RTVehicleLocationProvider, NSNumber;

@interface RTPredictedContextManager : RTService <RTDiagnosticProvider, RTPurgable>

@property (retain, nonatomic) PCAlgorithms *algorithms;
@property (nonatomic) BOOL available;
@property (retain, nonatomic) NSMutableDictionary *monitoringClientLastCallbackDate;
@property (retain, nonatomic) RTFeatureExtractor *featureExtractor;
@property (retain, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (retain, nonatomic) RTPlatform *platform;
@property (retain, nonatomic) RTXPCActivityManager *activityManager;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTDataProtectionManager *dataProtectionManager;
@property (retain, nonatomic) RTDataSerializer *dataSerializer;
@property (retain, nonatomic) RTVisitManager *visitManager;
@property (retain, nonatomic) RTMapServiceManager *mapServiceManager;
@property (retain, nonatomic) RTMapsSupportManager *mapsSupportManager;
@property (retain, nonatomic) RTNavigationManager *navigationManager;
@property (retain, nonatomic) RTEventManager *eventManager;
@property (retain, nonatomic) RTVehicleLocationProvider *vehicleLocationProvider;
@property (retain, nonatomic) RTDistanceCalculator *distanceCalculator;
@property (retain, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (retain, nonatomic) NSMutableArray *clients;
@property (nonatomic) BOOL monitorPredictedContext;
@property (retain, nonatomic) RTXPCTimerAlarm *periodicTriggerTimer;
@property (retain, nonatomic) RTPredictedContextResult *simulatedPredictedContextResult;
@property (retain, nonatomic) RTPredictedContextStore *predictedContextStore;
@property (retain, nonatomic) RTPredictedContextMetricsManager *metricsManager;
@property (retain) NSNumber *currentVisitType;
@property (retain, nonatomic) NSDictionary *routeSummary;
@property (nonatomic) unsigned long long previousMotionActivity;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)featureEnabled;
+ (long long)periodicPurgePolicy;
+ (id)_dataCollectionDefaultLookbackDurations;
+ (id)_defaultLookbackDurations;
+ (id)_inferenceDefaultLookbackDurations;
+ (BOOL)deferBasedOnFeatureExtractorError:(id)a0;
+ (id)serializedDataContainerPath;
+ (id)stringFromInferenceTriggerReason:(long long)a0;
+ (id)stringFromTrainPolicy:(long long)a0;
+ (id)stringFromTrainResult:(unsigned long long)a0;

- (void)_shutdownWithHandler:(id /* block */)a0;
- (void)performPurgeOfType:(long long)a0 referenceDate:(id)a1 completion:(id /* block */)a2;
- (void)onVisitManagerNotification:(id)a0;
- (BOOL)_generateDiagnosticFilesAtURL:(id)a0 error:(id *)a1;
- (void)_onNavigationNotification:(id)a0;
- (void)_setup;
- (void)onNavigationNotification:(id)a0;
- (void)_onVisitManagerNotification:(id)a0;
- (void)_onMotionActivityManagerNotification:(id)a0;
- (void)onDataProtectionNotification:(id)a0;
- (void)sendDiagnosticsToURL:(id)a0 options:(id)a1 handler:(id /* block */)a2;
- (void).cxx_destruct;
- (void)onMotionActivityManagerNotification:(id)a0;
- (void)_invalidatePeriodicTriggerTimer;
- (id)_lookbackIntervalsWithDefaults:(id)a0;
- (void)_pushResult:(id)a0 toMonitoringClient:(id)a1;
- (void)_setTrainAttemptedDateDefaults:(id)a0;
- (void)_stopMonitoringForClient:(id)a0 reply:(id /* block */)a1;
- (void)_submitMetrics:(id)a0;
- (double)_activityTrainHighPriorityInterval;
- (double)_activityTrainRegularInterval;
- (void)_addClient:(id)a0;
- (id)_convertContextLocation:(id)a0;
- (id)_convertContextResult:(id)a0;
- (id)_convertContextSources:(id)a0;
- (id)_convertContextTransition:(id)a0;
- (id)_convertContextTransport:(id)a0;
- (id)_convertContextWorkout:(id)a0;
- (id)_convertDate:(id)a0;
- (id)_convertDateInterval:(id)a0;
- (id)_convertLocationOfInterest:(id)a0 sources:(id)a1;
- (BOOL)_didHealthKitInaccessibleErrorOccur:(id)a0;
- (void)_evaluateTrainErrorAndReschedule:(id)a0;
- (unsigned long long)_evaluateTrainErrorForResult:(id)a0;
- (id)_extractAndConvertAnalytics:(id)a0;
- (void)_fetchPredictedContextInputSignalsWithHandler:(id /* block */)a0;
- (void)_fetchPredictedContextWithOptions:(id)a0 handler:(id /* block */)a1;
- (id)_filterResult:(id)a0 forClient:(id)a1;
- (id)_fireDate;
- (void)_forceTrainModelWithHandler:(id /* block */)a0;
- (double)_getActivityTrainIntervalForTrainPolicy:(long long)a0;
- (id)_getLocationOfInterestWithIdentifier:(id)a0;
- (id)_getXpcActivityCriteriaForTrainPolicy:(long long)a0;
- (void)_handleComputeResultWithRecords:(id)a0 error:(id)a1 inputSignals:(id)a2 stimulationDate:(id)a3 featureExtractorMemoryFootprint:(double)a4 handler:(id /* block */)a5;
- (void)_handlePeriodicTriggerTimer;
- (BOOL)_isHealthKitInaccessibleErrorIncludedInTheErrorArray:(id)a0;
- (BOOL)_isMonitoringClientEligibleForTriggerReasonClientRegistration:(id)a0;
- (BOOL)_isMonitoringClientEligibleToReceiveResultFromTriggerReasonSingleShot:(id)a0;
- (BOOL)_isSupported;
- (BOOL)_isSupportedForCurrentPlatform;
- (BOOL)_maxTrainAttemptsReachedWithinLast24Hours;
- (void)_onLearnedLocationManagerDidUpdateNotification:(id)a0;
- (void)_onVisit:(id)a0;
- (id)_overrideKeyForFeatureOption:(unsigned long long)a0;
- (double)_periodicTriggerTimerInterval;
- (void)_postprocessRequest:(id)a0;
- (void)_preprocessTrainingEventWithStartDate:(id)a0;
- (void)_processPredictedContextResult:(id)a0 reason:(long long)a1;
- (void)_processTrainingResult:(unsigned long long)a0;
- (id)_readPersistedArrayLastTrainAttemptsDates;
- (long long)_readPersistedTrainPolicyOnSetup;
- (void)_registerActivityTrainWithTrainPolicy:(long long)a0;
- (void)_requestInferenceWithReason:(long long)a0;
- (id)_requestInferenceWithReason:(long long)a0 outError:(id *)a1;
- (BOOL)_requiresPeriodicTriggerTimer;
- (void)_rescheduleActivityTrainWithTrainPolicy:(long long)a0;
- (void)_rescheduleTrainingOnLearnedLocationUpdateNotificationIfNeeded;
- (void)_setInputSignalDefaults:(id)a0;
- (void)_setLastTrainAttemptsDatesToDefaults:(id)a0;
- (void)_setRegisteredActivityTrainPolicyDefaults:(long long)a0;
- (BOOL)_shouldAllClientsReceiveResultForInferenceReason:(long long)a0;
- (BOOL)_shouldPerformManualDelete;
- (void)_simulatePredictedContextResult:(id)a0 handler:(id /* block */)a1;
- (void)_startMonitoringForClient:(id)a0 options:(id)a1 handler:(id /* block */)a2;
- (void)_startPeriodicTriggerTimer;
- (void)_storeRequest:(id)a0;
- (id)_stringForFeatureOption:(unsigned long long)a0;
- (unsigned long long)_trainAttemptsDatesQueueCapacity;
- (long long)_trainPolicyAfterEvaluatingTrainAttempts:(long long)a0;
- (void)_trainWithHandler:(id /* block */)a0;
- (void)_updateMonitorPredictedContext;
- (void)checkMotionActivityChangeAndTriggerPrediction:(unsigned long long)a0 currentActivity:(unsigned long long)a1;
- (void)fetchPredictedContextInputSignalsWithHandler:(id /* block */)a0;
- (void)fetchPredictedContextWithOptions:(id)a0 handler:(id /* block */)a1;
- (void)forceTrainModelWithHandler:(id /* block */)a0;
- (id)initWithFeatureExtractor:(id)a0 learnedLocationManager:(id)a1 platform:(id)a2 activityManager:(id)a3 dataProtectionManager:(id)a4 defaultsManager:(id)a5 visitManager:(id)a6 eventManager:(id)a7 mapServiceManager:(id)a8 mapsSupportManager:(id)a9 navigationManager:(id)a10 motionActivityManager:(id)a11 vehicleLocationProvider:(id)a12 distanceCalculator:(id)a13 predictedContextStore:(id)a14 metricsManager:(id)a15;
- (void)onLearnedLocationManagerDidUpdateNotification:(id)a0;
- (void)saveInteractionRecord:(id)a0;
- (void)simulatePredictedContextResult:(id)a0 handler:(id /* block */)a1;
- (void)startMonitoringForClient:(id)a0 options:(id)a1 handler:(id /* block */)a2;
- (void)stopMonitoringForClient:(id)a0 reply:(id /* block */)a1;

@end
