@class NSData, NSMutableData, NSURL, NSString, NSMutableString, UARPComponentVersion, UARPComponentTag, NSObject, NSMutableArray, NSNumber, UARPRTKitFTAB;
@protocol OS_os_log;

@interface UARPSuperBinaryPayloadLayer3 : NSObject {
    struct UARPPayloadHeader2 { unsigned int payloadHeaderLength; struct UARP4ccTag { unsigned char char1; unsigned char char2; unsigned char char3; unsigned char char4; } payloadTag; struct UARPVersion { unsigned int major; unsigned int minor; unsigned int release; unsigned int build; } payloadVersion; unsigned int payloadMetadataOffset; unsigned int payloadMetadataLength; unsigned int payloadOffset; unsigned int payloadLength; } _layer2PayloadHeader;
    BOOL _useFilesystem;
    NSMutableString *_keyManifest;
    BOOL _isFTABPayload;
    UARPRTKitFTAB *_ftab;
    NSData *_payloadDataInternal;
    NSMutableData *_metaData;
    NSMutableData *_composedMetaData;
    NSURL *_payloadsURL;
    NSString *_filepath;
    NSString *_longname;
    NSURL *_payloadURL;
    NSString *_propertyListPath;
    NSString *_propertyListVersion;
    NSData *_payloadDigest;
    NSData *_compressedPayloadDataInternal;
    NSURL *_compressedPayloadURL;
    NSData *_compressedHash;
    NSData *_uncompressedPayloadDataInternal;
    NSURL *_uncompressedPayloadURL;
    NSData *_uncompressedHash;
    NSMutableArray *_compressedHeaders;
    BOOL _isCompressed;
}

@property (readonly) NSObject<OS_os_log> *log;
@property (readonly) UARPComponentTag *payload4cc;
@property (readonly) UARPComponentVersion *payloadVersion;
@property (readonly, copy) NSMutableArray *tlvs;
@property (readonly) BOOL needsHostPersonalization;
@property (copy) NSData *manifest;
@property BOOL manifestAsTLV;
@property BOOL bootNonceAsTLV;
@property (retain) NSData *nonceSeed;
@property (retain) NSNumber *ftabGeneration;
@property (readonly) unsigned long long index;

- (void).cxx_destruct;
- (unsigned long long)payloadLength;
- (id)metaData;
- (id)init;
- (void)setPayloadData:(id)a0;
- (id)description;
- (BOOL)compressPayload;
- (id)payloadData;
- (void)setPayloadHeader:(struct UARPPayloadHeader2 { unsigned int x0; struct UARP4ccTag { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; } x1; struct UARPVersion { unsigned int x0; unsigned int x1; unsigned int x2; unsigned int x3; } x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; } *)a0;
- (id)getDataBlock:(unsigned long long)a0 offset:(unsigned long long)a1;
- (id)personalizedData;
- (void)setPayloadURL:(id)a0;
- (void)addTLV:(id)a0;
- (id)composeMetaData;
- (id)ftabDescription;
- (void)addTLVs:(id)a0;
- (BOOL)appendCompressedPayloadData:(id)a0 offset:(unsigned long long)a1;
- (BOOL)appendPayloadData:(id)a0 offset:(unsigned long long)a1;
- (void)cachePayloadData;
- (id)cleanFileHandleForWriting:(id)a0 error:(out id *)a1;
- (BOOL)composePayload;
- (BOOL)composePersonalizedFTAB;
- (BOOL)composePersonalizedPayload;
- (id)composedMetaData;
- (id)composedPayloadData;
- (unsigned long long)composedPayloadLength;
- (id)compressedHeaders;
- (id)containsTLV:(Class)a0;
- (BOOL)decompressPayload;
- (id)descriptionOfHeader;
- (long long)determinePayloadHashAlgorithm;
- (BOOL)expandPayloadDictionary:(id)a0;
- (BOOL)expandPayloadDictionaryData:(id)a0;
- (BOOL)expandPayloadDictionaryKeyValuePayload;
- (BOOL)expandPayloadDictionaryPropertyListPayload:(id)a0;
- (BOOL)expandPayloadDictionaryTLVs:(id)a0;
- (id)generateHash:(long long)a0 ftabSubfile:(id)a1;
- (id)generateMetaDataHash:(long long)a0 metaData:(id)a1;
- (id)generatePayloadHash:(long long)a0;
- (id)generatePayloadHash:(long long)a0 measureOffset:(id)a1 measureLength:(id)a2;
- (id)getDataRangeFromData:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a0;
- (id)getDataRangeFromURL:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a0;
- (void)hashPayload;
- (id)initWithPayload4cc:(id)a0 payloadVersion:(id)a1 payloadIndex:(unsigned long long)a2 baseURL:(id)a3;
- (id)initWithPayloadData:(id)a0 payloadMetaData:(id)a1 payload4cc:(id)a2 payloadVersion:(id)a3 payloadIndex:(unsigned long long)a4;
- (id)initWithPayloadDictionary:(id)a0 payloadsURL:(id)a1 payloadIndex:(unsigned long long)a2;
- (id)initWithPayloadDictionary:(id)a0 payloadsURL:(id)a1 payloadIndex:(unsigned long long)a2 useFilesystem:(BOOL)a3;
- (id)initWithPayloadURL:(id)a0 payloadTlvs:(id)a1 payload4cc:(id)a2 payloadVersion:(id)a3 payloadIndex:(unsigned long long)a4;
- (BOOL)isFTAB;
- (BOOL)isPropertyListPayload;
- (id)matchingTLVs:(Class)a0;
- (BOOL)measurementsForDevicePersonalization;
- (BOOL)measurementsForDevicePersonalizationNonFTAB;
- (id)payloadDataAsData;
- (id)payloadDataAsURL;
- (void)prepareComposeMetaData;
- (id)preparePersonalizedURL;
- (void)removeTLV:(id)a0;
- (BOOL)setCompressedDataBlock:(id)a0 offset:(unsigned long long)a1;
- (BOOL)setDataBlock:(id)a0 offset:(unsigned long long)a1;
- (id)setDataBlockToData:(id)a0 offset:(unsigned long long)a1 payloadData:(id)a2;
- (BOOL)setDataBlockToURL:(id)a0 offset:(unsigned long long)a1 url:(id)a2;
- (BOOL)writeComposedPayloadDataToFile:(id)a0 error:(out id *)a1;
- (BOOL)writeComposedPayloadToFile:(id)a0 error:(out id *)a1;
- (BOOL)writeComposedPayloadURLToFile:(id)a0 error:(out id *)a1;

@end
