@class NSUUID, NSData, NSURL, NSString, NSMutableDictionary, NSDictionary, UARPComponentVersion, NSObject, UARPComponentTag, UARPEndpointLayer3, NSMutableArray, NSMutableString;
@protocol OS_os_log, OS_dispatch_queue;

@interface UARPSuperBinaryLayer3 : NSObject {
    BOOL _useFilesystem;
    NSData *_data;
    NSMutableArray *_tlvs;
    NSObject<OS_dispatch_queue> *_endpointQueue;
    struct UARPSuperBinaryHeader { unsigned int superBinaryFormatVersion; unsigned int superBinaryHeaderLength; unsigned int superBinaryLength; struct UARPVersion { unsigned int major; unsigned int minor; unsigned int release; unsigned int build; } superBinaryVersion; unsigned int superBinaryMetadataOffset; unsigned int superBinaryMetadataLength; unsigned int payloadHeadersOffset; unsigned int payloadHeadersLength; } _superbinaryHeader;
    NSMutableArray *_payloads;
    NSMutableArray *_tatsuTickets;
    NSMutableDictionary *_tatsuMeasurements;
    NSData *_manifest;
    NSMutableString *_keyManifest;
    BOOL _needsDevicePersonalization;
    NSURL *_propertyList;
    NSURL *_payloadsURL;
    NSString *_tmpFolderPath;
    unsigned long long _fileLength;
    BOOL _noMissingPayloads;
}

@property (readonly) NSURL *url;
@property (readonly) unsigned long long formatVersion;
@property (readonly) UARPComponentVersion *assetVersion;
@property (readonly) UARPComponentTag *asset4cc;
@property (readonly) NSDictionary *superBinaryPlist;
@property (readonly, weak) UARPEndpointLayer3 *layer3Endpoint;
@property (readonly) NSURL *tssServerURL;
@property (readonly) NSUUID *uuid;
@property (readonly) NSObject<OS_os_log> *log;
@property (readonly) unsigned long long assetLength;
@property (readonly) unsigned long long numPayloads;
@property (readonly) BOOL needsHostPersonalization;
@property (readonly) long long personalizationStatus;
@property (readonly) NSData *metaData;
@property (readonly) NSData *composedMetaData;
@property BOOL needsStaging;
@property BOOL autoApply;
@property BOOL ignoreVersion;
@property (readonly) NSURL *expansionFolderURL;
@property (readonly) NSURL *superbinaryURL;
@property (readonly) NSURL *personalizedURL;
@property void *layer2Context;
@property unsigned long long bytesTransferred;
@property (readonly) unsigned long long totalBytesRequested;
@property unsigned long long selectedPayloadIndex;
@property unsigned long long processingStatus;
@property long long assetType;

- (id)payloads;
- (BOOL)writeToURL:(id)a0 error:(out id *)a1;
- (BOOL)isEqual:(id)a0;
- (void).cxx_destruct;
- (void)addPayload:(id)a0;
- (unsigned long long)hash;
- (id)init;
- (id)description;
- (id)getDataBlock:(unsigned long long)a0 offset:(unsigned long long)a1;
- (id)tlvs;
- (id)tssRequest;
- (id)tssResponse;
- (void)addTLV:(id)a0;
- (id)composeMetaData;
- (BOOL)containsPayloadWithMatchingTag:(id)a0;
- (id)payloadWith4cc:(id)a0;
- (id)percentageRules;
- (id)requiredPersonalizationOptions:(id)a0;
- (void)acceptOffer:(id)a0 queue:(id)a1;
- (id)addPayloadWith4cc:(id)a0 payloadVersion:(id)a1 payloadIndex:(unsigned long long)a2;
- (void)assetMetaDataTLV:(id)a0;
- (id)cleanFileHandleForWriting:(id)a0 error:(out id *)a1;
- (id)composeToData:(out id *)a0;
- (id)composeToDataExcludingTags:(id)a0 error:(out id *)a1;
- (id)containsTLV:(Class)a0;
- (id)countryRules;
- (id)descriptionOfHeader;
- (void)devicePersonalizationStateCompleted;
- (void)devicePersonalizationStatePrepare:(id)a0 tatsuTickets:(id)a1 endpoint:(id)a2;
- (void)devicePersonalizationStateStarted;
- (void)expandPayloadHeadersAndMetaData:(unsigned long long)a0 offset:(unsigned long long)a1;
- (id)expandPayloadWithHeader:(struct UARPPayloadHeader2 { unsigned int x0; struct UARP4ccTag { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; } x1; struct UARPVersion { unsigned int x0; unsigned int x1; unsigned int x2; unsigned int x3; } x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; } *)a0 payloadIndex:(unsigned long long)a1;
- (id)expandPayloadWithHeaderAsData:(struct UARPPayloadHeader2 { unsigned int x0; struct UARP4ccTag { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; } x1; struct UARPVersion { unsigned int x0; unsigned int x1; unsigned int x2; unsigned int x3; } x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; } *)a0 payloadIndex:(unsigned long long)a1 payload4cc:(id)a2 payloadVersion:(id)a3 payloadMetaData:(id)a4;
- (id)expandPayloadWithHeaderAsURL:(struct UARPPayloadHeader2 { unsigned int x0; struct UARP4ccTag { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; } x1; struct UARPVersion { unsigned int x0; unsigned int x1; unsigned int x2; unsigned int x3; } x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; } *)a0 payloadIndex:(unsigned long long)a1 payload4cc:(id)a2 payloadVersion:(id)a3 payloadMetaData:(id)a4;
- (BOOL)expandPropertyListPayload:(id)a0 payloadIndex:(unsigned long long)a1;
- (BOOL)expandPropertyListPayloads:(id)a0;
- (BOOL)expandPropertyListTLVs:(id)a0;
- (BOOL)expandSuperBinaryHeader;
- (BOOL)expandSuperBinaryHeadersAndMetaData;
- (void)expandSuperBinaryMetaData:(unsigned long long)a0 offset:(unsigned long long)a1;
- (BOOL)expandSuperBinaryPlist;
- (BOOL)expandSuperBinaryPropertyList;
- (id)getDataRangeFromData:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a0;
- (id)getDataRangeFromURL:(struct _NSRange { unsigned long long x0; unsigned long long x1; })a0;
- (id)initWithData:(id)a0 assetTag:(id)a1 assetUUID:(id)a2 tmpFolderPath:(id)a3;
- (id)initWithData:(id)a0 assetUUID:(id)a1 tmpFolderPath:(id)a2;
- (id)initWithFilePath:(id)a0 assetUUID:(id)a1 tmpFolderPath:(id)a2;
- (id)initWithFormatVersion:(unsigned long long)a0 assetUUID:(id)a1 assetTag:(id)a2 assetVersion:(id)a3 tmpFolderPath:(id)a4;
- (id)initWithLayer2Context:(void *)a0 assetTag:(id)a1 tmpFolderPath:(id)a2;
- (id)initWithLayer2Context:(void *)a0 tmpFolderPath:(id)a1;
- (id)initWithPropertyList:(id)a0 payloadsURL:(id)a1;
- (id)initWithPropertyList:(id)a0 payloadsURL:(id)a1 noMissingPayloads:(BOOL)a2;
- (id)initWithPropertyList:(id)a0 payloadsURL:(id)a1 noMissingPayloads:(BOOL)a2 useFilesystem:(BOOL)a3;
- (id)initWithURL:(id)a0 assetUUID:(id)a1 assetTag:(id)a2 tmpFolderPath:(id)a3;
- (id)initWithURL:(id)a0 assetUUID:(id)a1 tmpFolderPath:(id)a2;
- (void)mergePayloadsPMAPs;
- (void)offerAsset:(id)a0 queue:(id)a1;
- (id)payloadWithMatchingIndex:(unsigned long long)a0;
- (id)payloadsWith4cc:(id)a0;
- (void)personalizationCompleted:(id)a0;
- (void)personalizationStarted:(id)a0;
- (void)personalizationStateCompleted;
- (void)personalizationStatePrepare:(id)a0;
- (void)personalizationStatePrepare:(id)a0 endpoint:(id)a1;
- (void)personalizationStateStarted;
- (BOOL)prepareComposedComponents:(id)a0 excludingTags:(id)a1 allHeaders:(id)a2 allMetaData:(id)a3 error:(out id *)a4;
- (BOOL)processDeploymentRules:(id)a0;
- (void)processPMAP:(id)a0;
- (BOOL)processPersonalizationTickets:(id)a0;
- (void)removePayloadsWithMatchingTag:(id)a0;
- (id)requiredPersonalizationOptions;
- (BOOL)setupTemporaryFolder;
- (BOOL)setupTemporaryFolderForExpand;
- (id)tatsuTickets;
- (id)tssRequests;
- (id)tssResponses;
- (BOOL)updateIncomingAssetProperties:(id)a0;
- (BOOL)writeToFileHandle:(id)a0 includedPayloads:(id)a1 allHeaders:(id)a2 allMetaData:(id)a3 error:(out id *)a4;
- (BOOL)writeToURL:(id)a0 excludeTags:(id)a1 error:(out id *)a2;

@end
