@class NSMutableDictionary, MADAutoAssetClientRequest, NSDictionary, MANAutoAssetControlStatisticsBySize, NSMutableArray, MADAutoSetConfiguration, SUCoreFSM, NSString, SUCoreLog, MANAutoAssetControlStatisticsByCommand, MADAutoAssetPersisted, MADAutoAssetDescriptor, NSArray;

@interface MADAutoAssetStager : NSObject

@property (readonly, retain, nonatomic) SUCoreLog *logger;
@property (readonly, retain, nonatomic) NSDictionary *stateTable;
@property (retain, nonatomic) SUCoreFSM *autoStagerFSM;
@property (readonly, retain, nonatomic) MADAutoAssetPersisted *persistedState;
@property (retain, nonatomic) MADAutoAssetPersisted *persistedSetLookupResults;
@property (retain, nonatomic) NSString *latestSafeSummary;
@property (retain, nonatomic) NSString *stagingFromOSVersion;
@property (retain, nonatomic) NSString *stagingFromBuildVersion;
@property (nonatomic) BOOL alwaysPromoteStagedAssets;
@property (retain, nonatomic) NSString *assetTargetOSVersion;
@property (retain, nonatomic) NSString *assetTargetBuildVersion;
@property (retain, nonatomic) NSString *assetTargetTrainName;
@property (retain, nonatomic) NSString *assetTargetRestoreVersion;
@property (retain, nonatomic) MADAutoAssetClientRequest *stagingClientRequest;
@property (retain, nonatomic) MADAutoSetConfiguration *activeSetJobConfiguration;
@property (retain, nonatomic) MADAutoAssetDescriptor *activeJobDescriptor;
@property (retain, nonatomic) NSArray *alreadyDownloadedDescriptors;
@property (retain, nonatomic) NSArray *setConfigurations;
@property (retain, nonatomic) NSArray *setTargets;
@property (retain, nonatomic) NSArray *scheduledJobs;
@property (retain, nonatomic) NSMutableArray *candidatesForStaging;
@property (retain, nonatomic) NSMutableArray *candidateSetConfigurations;
@property (retain, nonatomic) NSMutableDictionary *setLookupResults;
@property (retain, nonatomic) NSMutableArray *baseForStagingDescriptors;
@property (retain, nonatomic) NSMutableDictionary *determiningBySelector;
@property (retain, nonatomic) NSMutableArray *availableForStaging;
@property (retain, nonatomic) NSMutableArray *awaitingStagingAttempt;
@property (retain, nonatomic) NSMutableDictionary *successfullyStaged;
@property (nonatomic) long long overallStagedTotalExpectedBytes;
@property (nonatomic) long long overallStagedDownloadedSoFarBytes;
@property (retain, nonatomic) NSMutableDictionary *eliminationSelectors;
@property (retain, nonatomic) NSMutableDictionary *eliminationSelectorsAcknowledged;
@property (retain, nonatomic) MANAutoAssetControlStatisticsByCommand *statisticsClientRepliesSuccess;
@property (retain, nonatomic) MANAutoAssetControlStatisticsByCommand *statisticsClientRepliesFailure;
@property (retain, nonatomic) MANAutoAssetControlStatisticsBySize *statisticsStaged;
@property (retain, nonatomic) MANAutoAssetControlStatisticsBySize *statisticsUnstaged;

+ (id)autoAssetStager;
+ (void)clientPurgeAll:(id)a0;
+ (id)_getAutoAssetStagerStateTable;
+ (void)autoAssetStagerJobDetermineDone:(id)a0 withBaseForStagingDescriptors:(id)a1 withDetermineError:(id)a2;
+ (void)autoAssetStagerJobDownloadDone:(id)a0 withDownloadedDescriptor:(id)a1 withDownloadError:(id)a2;
+ (void)autoAssetStagerJobDownloadProgress:(id)a0 withProgressError:(id)a1;
+ (void)autoAssetStagerJobFailedToStart:(id)a0;
+ (void)clientDetermineAllAvailable:(id)a0;
+ (void)clientDownloadAll:(id)a0;
+ (void)controlAlreadyDownloadedDescriptors:(id)a0 withSetConfigurations:(id)a1 withSetTargets:(id)a2 withScheduldJobs:(id)a3;
+ (id)controlConvertStagedToDownloaded:(id)a0;
+ (id)controlCopyCurrentStagedDescriptors;
+ (void)controlEliminateSelector:(id)a0;
+ (void)controlForcePurge:(id)a0;
+ (void)controlStatisticsClientRepliesSuccess:(id *)a0 clientRepliesFailure:(id *)a1 totalStaged:(id *)a2 totalUnstaged:(id *)a3 clearingAfter:(BOOL)a4;
+ (void)extendSummaryWithDeterminedAssets:(id)a0 basedOnControl:(id)a1;
+ (void)extendSummaryWithStagedAssets:(id)a0 basedOnControl:(id)a1;
+ (void)extendSummaryWithStagingAssets:(id)a0 basedOnControl:(id)a1;
+ (void)garbageCollectEliminateSelector:(id)a0;
+ (id)migrateMismatchedPersistedSetPromotionVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (id)migrateMismatchedPersistedStateVersion:(id)a0 forEntryID:(id)a1 withMismatchedState:(id)a2;
+ (long long)persistedStagedCount;
+ (void)resumeFromPersisted;

- (id)description;
- (id)init;
- (void).cxx_destruct;
- (id)summary;
- (long long)actionUnknownAction:(id)a0 error:(id *)a1;
- (long long)performAction:(id)a0 onEvent:(id)a1 inState:(id)a2 withInfo:(id)a3 nextState:(id)a4 error:(id *)a5;
- (id)newAssetMetadataFromAssetCatalog:(id)a0 forAssetype:(id)a1 forAssetSpecifier:(id)a2;
- (void)_logPersistedConfigSet:(id)a0 message:(id)a1;
- (long long)action_ReplyNoCandidates:(id)a0 error:(id *)a1;
- (void)_acceptStagingClientRequest:(id)a0;
- (void)_acknowledgeEliminatedForCurrentJob;
- (void)_acknowlegdeAndClearAllEliminations;
- (void)_addDescriptor:(id)a0 withRepresentation:(long long)a1 toSummary:(id)a2;
- (id)_allEliminationSelectors;
- (void)_cancelCurrentJob;
- (void)_clearAllTrackingOfActiveOperations;
- (void)_clearBeforeDetermineAvailable;
- (id)_controlConvertStagedToDownloaded:(id)a0;
- (BOOL)_doesSelector:(id)a0 matchDescriptor:(id)a1;
- (BOOL)_doesSelectorMatchCurrentJob:(id)a0;
- (void)_extendLookupByAssetType:(id)a0 fromSource:(id)a1 withAssetType:(id)a2 withAssetSpecifier:(id)a3;
- (void)_extendLookupByAssetType:(id)a0 fromSource:(id)a1 withAssetType:(id)a2 withAssetSpecifier:(id)a3 withDownloadDecryptionKey:(id)a4;
- (void)_extendLookupByAssetTypeWithDownloadedDescriptors:(id)a0;
- (void)_extendLookupByAssetTypeWithSetConfigurations:(id)a0;
- (void)_extendSummaryWithDeterminedAssets:(id)a0 basedOnControl:(id)a1;
- (void)_extendSummaryWithStagedAssets:(id)a0 basedOnControl:(id)a1;
- (void)_extendSummaryWithStagingAssets:(id)a0 basedOnControl:(id)a1;
- (BOOL)_formCandidateSetLookupArray;
- (BOOL)_isAssetSetEntry:(id)a0 blockedBySetTarget:(id)a1;
- (BOOL)_isAssetTypeInvolvedInStaging:(id)a0;
- (BOOL)_isDescriptorAssetTypeManagedAsSet:(id)a0;
- (BOOL)_isSetTargetWithinRange:(id)a0 asCandidate:(BOOL)a1;
- (void)_logPersistedConfigLoad:(id)a0 lastStagingFromOSVersion:(id)a1 lastStagingFromBuildVersion:(id)a2 assetTargetOSVersion:(id)a3 assetTargetBuildVersion:(id)a4 candidateAssetCount:(unsigned long long)a5 determinedAvailableAssetCount:(unsigned long long)a6 activelyStagingAssetCount:(unsigned long long)a7 awaitingStagingAssetCount:(unsigned long long)a8 stagedAssetCount:(unsigned long long)a9 stagedAssetTotalContentBytes:(unsigned long long)a10 message:(id)a11;
- (void)_logPersistedEntry:(id)a0 operation:(id)a1 persistingDescriptor:(id)a2 withRepresentation:(long long)a3 message:(id)a4;
- (void)_logPersistedRemovedEntry:(id)a0 removedDescriptor:(id)a1 message:(id)a2;
- (void)_logPersistedSetLookupResult:(id)a0 operation:(id)a1 forPersistedEntryID:(id)a2 withSetLookupResult:(id)a3 message:(id)a4;
- (void)_logPersistedSetLookupResultRemoved:(id)a0 removedPersistedEntryID:(id)a1 removedSetLookupResult:(id)a2 message:(id)a3;
- (void)_logPersistedSetLookupResultTableOfContents:(id)a0;
- (void)_logPersistedTableOfContents:(id)a0;
- (void)_maintainLatestCandidate:(id)a0 candidateDescriptor:(id)a1;
- (long long)_persistDescriptor:(id)a0 operation:(id)a1 persistingDescriptor:(id)a2 withRepresentation:(long long)a3 message:(id)a4;
- (void)_persistLastStagingFrom;
- (id)_persistRebuildTrackingNewHandedOffDescriptors:(id)a0;
- (void)_persistRemoveAll:(id)a0 message:(id)a1 flushing:(BOOL)a2;
- (void)_removeAllStagedContent;
- (void)_removeDescriptorFromSuccessfullyStaged:(id)a0 message:(id)a1;
- (void)_removeEliminatedFromCandidatesAndAvaliable;
- (void)_removeEliminatedFromStaged;
- (void)_removeStagedAssetFromFilesystem:(id)a0 forHistoryOperation:(long long)a1;
- (void)_replyHaveStagedContent;
- (void)_replyNothingStaged;
- (void)_replyToStagingClient:(id)a0 withErrorCode:(long long)a1 withUnderlyingError:(id)a2 withDescription:(id)a3;
- (void)_replyToStagingClientOperationSuccess;
- (id)_setConfigurationForAssetType:(id)a0 forAssetSpecifier:(id)a1;
- (BOOL)_setConfigurationHasEntriesWhenTargeting:(id)a0;
- (id)_setTargetForAssetType:(id)a0;
- (id)_setTargetForSetConfiguration:(id)a0;
- (void)_setupAwaitingStagingAndBeginFirstDownload;
- (id)_stagingClientMessageDesire;
- (id)_stagingClientMessageInstance;
- (id)_stagingClientMessageStaging;
- (void)_trackReloadedDescriptorAvailableForStaging:(id)a0;
- (id)_trimConsideringToLatestDownloaded:(id)a0;
- (void)_updateDescriptor:(id)a0 withLatestJobStatus:(id)a1;
- (id)_updateLatestSummary;
- (long long)action_AddToAvailableDecideAnyAvailable:(id)a0 error:(id *)a1;
- (long long)action_AddToAvailableDecideMoreCandidates:(id)a0 error:(id *)a1;
- (long long)action_AddToStagedDecideMoreAvailable:(id)a0 error:(id *)a1;
- (long long)action_CancelActiveJob:(id)a0 error:(id *)a1;
- (long long)action_ClientAccept:(id)a0 error:(id *)a1;
- (long long)action_ClientAcceptCancelActiveJob:(id)a0 error:(id *)a1;
- (long long)action_ClientAcceptNextAvailableBeginDownload:(id)a0 error:(id *)a1;
- (long long)action_ClientAcceptRemoveAllReplyPurged:(id)a0 error:(id *)a1;
- (long long)action_ClientContinueRestartingMaxDetermining:(id)a0 error:(id *)a1;
- (long long)action_ClientContinueUsingLatestRequest:(id)a0 error:(id *)a1;
- (long long)action_ClientHaveStagedContent:(id)a0 error:(id *)a1;
- (long long)action_ClientInvalidStagingPhase:(id)a0 error:(id *)a1;
- (long long)action_ClientNothingStaged:(id)a0 error:(id *)a1;
- (long long)action_ClientRequestAlreadyDownloaded:(id)a0 error:(id *)a1;
- (long long)action_ControlUnstagedDecideCancelJob:(id)a0 error:(id *)a1;
- (long long)action_ControlUnstagedDecideRemoveAll:(id)a0 error:(id *)a1;
- (long long)action_DecideMoreAvailable:(id)a0 error:(id *)a1;
- (long long)action_DecideMoreCandidates:(id)a0 error:(id *)a1;
- (long long)action_DoneAvailableDecideAnyStaged:(id)a0 error:(id *)a1;
- (long long)action_DoneCandidatesDecideAnyAvailable:(id)a0 error:(id *)a1;
- (long long)action_EliminateAvailableDecideEmpty:(id)a0 error:(id *)a1;
- (long long)action_EliminateCancelActiveJob:(id)a0 error:(id *)a1;
- (long long)action_EliminateDecideMatch:(id)a0 error:(id *)a1;
- (long long)action_EliminateDeterminingDecideMatch:(id)a0 error:(id *)a1;
- (long long)action_EliminateDone:(id)a0 error:(id *)a1;
- (long long)action_EliminateDoneDecideMoreCandidates:(id)a0 error:(id *)a1;
- (long long)action_EliminateDoneDecideMoreDownload:(id)a0 error:(id *)a1;
- (long long)action_EliminateDoneStagedDecideEmpty:(id)a0 error:(id *)a1;
- (long long)action_FormCandidatesDecideDetermine:(id)a0 error:(id *)a1;
- (long long)action_LoadPersistedDecideResume:(id)a0 error:(id *)a1;
- (long long)action_NextAwaitingBeginDownload:(id)a0 error:(id *)a1;
- (long long)action_NextCandidateBeginDetermine:(id)a0 error:(id *)a1;
- (long long)action_RemeberEliminateDone:(id)a0 error:(id *)a1;
- (long long)action_RemoveAllReplyPurged:(id)a0 error:(id *)a1;
- (long long)action_ReplyHaveAvailable:(id)a0 error:(id *)a1;
- (long long)action_ReplyHaveStaged:(id)a0 error:(id *)a1;
- (long long)action_ReplyNothingStaged:(id)a0 error:(id *)a1;
- (long long)action_ReportStagingProgressToClient:(id)a0 error:(id *)a1;
- (long long)action_ResumingNextAvailableBeginDownload:(id)a0 error:(id *)a1;
- (id)assetMetadataFromAssetCatalog:(id)a0 forAssetype:(id)a1 forAssetSpecifier:(id)a2 preferringBestFormat:(BOOL)a3;
- (id)baseForPatchingToSelector:(id)a0;
- (void)loadPersistedSetLookupResults;
- (void)lookupCacheUpdateWithDetermineResult:(id)a0 fromLocation:(id)a1;
- (id)newSetLookupResult:(id)a0 forSetCatalog:(id)a1;
- (id)newSetLookupResultsForTargetOS;
- (void)setLookupResultLoadedFromPersisted:(id)a0 persistedEntryID:(id)a1;
- (void)startMaxTimeSpentDeterminingTimer;

@end
