@class RTTrustedTimeCache, RTDefaultsManager, RTLocationManager, RTVisitManager, RTAuthorizationManager, RTAuthorizedLocationConfirmationStatusStore, RTVisit, RTAuthorizedLocationManagerCachedStatus, RTLearnedLocationManager, RTAuthorizedLocationStatus, RTXPCActivityManager, RTXPCActivityCriteria, NSArray, RTAuthorizedLocationMetrics, RTPlatform, RTAuthorizedLocationVisitLogStore, RTAuthorizedLocationZDRLocationManager, RTDistanceCalculator, RTAuthorizedLocationBiometricsManager, NSLock, NSObject, RTPersistenceMirroringManager, RTMotionActivityManager, RTDataProtectionManager, RTAuthorizedLocationZDRLocationsStore, NSDate;
@protocol OS_os_transaction;

@interface RTAuthorizedLocationManager : RTService

@property (readonly, nonatomic) RTPlatform *platform;
@property (readonly, nonatomic) BOOL isSupportedDevice;
@property (retain, nonatomic) RTAuthorizationManager *authorizationManager;
@property (retain, nonatomic) RTAuthorizedLocationZDRLocationManager *zdrLocationManager;
@property (readonly, nonatomic) RTVisitManager *visitManager;
@property (readonly, nonatomic) RTLocationManager *locationManager;
@property (readonly, nonatomic) RTDistanceCalculator *distanceCalculator;
@property (readonly, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (readonly, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (retain) NSArray *authorizedLocationArr;
@property (readonly, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain) NSDate *dateOfLastAuthorizedLocationsCuration;
@property (retain) NSDate *dateOfLastAuthorizedLocationsUserRequest;
@property (retain) NSDate *dateOfLastAuthorizedLocationsNonUserRequest;
@property (readonly, nonatomic) RTAuthorizedLocationVisitLogStore *visitLogStore;
@property (readonly, nonatomic) RTAuthorizedLocationConfirmationStatusStore *confirmationStatusStore;
@property (readonly, nonatomic) RTAuthorizedLocationZDRLocationsStore *zdrLocationsStore;
@property (readonly, nonatomic) RTXPCActivityManager *xpcActivityManager;
@property (readonly, nonatomic) RTDataProtectionManager *dataProtectionManager;
@property (nonatomic) BOOL isUnlockedSinceBoot;
@property (readonly, nonatomic) RTTrustedTimeCache *trustedTimeCache;
@property BOOL allowUnsecureTimeFallback;
@property (retain, nonatomic) RTAuthorizedLocationMetrics *metrics;
@property (readonly, nonatomic) RTPersistenceMirroringManager *persistenceMirroringManager;
@property (nonatomic) BOOL isEraseInstallDatabaseInitializationRequired;
@property (nonatomic) unsigned long long eraseInstallDatabaseInitializationMaxAttemptCount;
@property (nonatomic) unsigned long long eraseInstallDatabaseInitializationAttemptCount;
@property (retain, nonatomic) NSDate *eraseInstallInitializationStartDate;
@property (retain, nonatomic) RTXPCActivityCriteria *eraseInstallInitializationXpcCriteria;
@property (retain) RTAuthorizedLocationStatus *overrideAuthorizedLocationStatus;
@property (nonatomic) BOOL relaxTrustedTimeRequirement;
@property (nonatomic) BOOL forceTrustedTimeUnavailability;
@property (readonly, nonatomic) RTAuthorizedLocationBiometricsManager *biometricsManager;
@property (retain, nonatomic) NSDate *mostRecentDateAtWhichDeviceDataIsTrusted;
@property (retain, nonatomic) RTAuthorizedLocationManagerCachedStatus *authLocConfirmationStatus;
@property (retain, nonatomic) NSDate *lastAuthLocConfirmationLocationTriggerTime;
@property (retain, nonatomic) NSDate *lastAuthLocConfirmationXPCTriggerTime;
@property (retain, nonatomic) RTVisit *currentVisitCached;
@property (nonatomic) unsigned long long technologiesMissingToLookForInLocationUpdates;
@property (retain, nonatomic) NSLock *metricLock;
@property (retain, nonatomic) NSObject<OS_os_transaction> *eraseInstallInitTransaction;

+ (unsigned long long)_locationAvailabilityFromCLLocation:(id)a0;

- (void)_setup;
- (void)onLeechedLocationNotification:(id)a0;
- (void)onDataProtectionNotification:(id)a0;
- (void).cxx_destruct;
- (void)_updateVisitLogWithTrustedTime:(id)a0 isRetroRegistrationTime:(BOOL)a1 handler:(id /* block */)a2;
- (void)_readConfirmationStatusFromDisk;
- (BOOL)_assertMotionConsistencyForLocations:(id)a0 positionUncertaintyRate:(double)a1;
- (BOOL)_assertRecentLocationTechnologyQualityForAuthorizedLocation:(id)a0 visit:(id)a1 errorCode:(long long *)a2;
- (BOOL)_assertRecentLocationTechnologyQualityForAuthorizedLocationInParts:(id)a0 visit:(id)a1 recentLocation:(id)a2 technologyBitfield:(unsigned long long *)a3 proximityStatus:(long long *)a4 errorCode:(long long *)a5;
- (BOOL)_assertRecentMotionActivityAndLocationHistoryAreConsistentForAuthorizedLocation:(id)a0 visit:(id)a1 errorCode:(long long *)a2;
- (BOOL)_assertUserTimeAndTrustedTimeAreConsistent:(long long *)a0;
- (id)_assertWeAreAtAuthorizedLocation:(id)a0;
- (void)_checkConfiguration;
- (void)_checkStatusOverrideDefault;
- (unsigned long long)_computeLocationTechnologyAvailabilityForDateInterval:(id)a0;
- (unsigned long long)_computeLocationTechnologyExpectationFromHistoricalAvailability:(id)a0;
- (void)_curateAuthorizedLocationsWithHandler:(id /* block */)a0;
- (void)_deleteConfirmationStatusFromDisk;
- (BOOL)_doesNewLocationChangeTechnologyAvailability:(id)a0;
- (void)_fetchAuthorizedLocationExtendedStatus:(id /* block */)a0;
- (void)_fetchAuthorizedLocationExtendedStatusWithMetrics:(id /* block */)a0;
- (void)_fetchAuthorizedLocationStatusWithZdr:(id /* block */)a0;
- (void)_fetchAuthorizedLocations:(id /* block */)a0;
- (void)_fetchCurrentLocationWithHandler:(id /* block */)a0;
- (void)_fetchZDRLocations:(id /* block */)a0;
- (double)_getActiveLocationRequestTime;
- (id)_getCurrentVisit;
- (int)_getMaintenanceXPCTimeoutInSeconds;
- (int)_getMinimumLocationRequestIntervalSeconds;
- (void)_initAtUserRequest;
- (BOOL)_isExpeditedSyncAndLearnRequired;
- (BOOL)_isLocationServiceEnabled;
- (BOOL)_isRoutineEnabled;
- (BOOL)_loadEraseInstallInitializationXPCCriteriaFromDefaults;
- (BOOL)_oneTimeRetroactivelyRegisterAllStoredVisits;
- (double)_positionUncertaintyRateFromMotionActivity:(id)a0 dateInterval:(id)a1;
- (void)_registerForDeviceUnlockNotification;
- (BOOL)_requestLocation;
- (void)_runEraseInstallDatabaseInitialization:(id /* block */)a0;
- (void)_runPeriodicConfirmationAlgorithm:(long long)a0 handler:(id /* block */)a1;
- (void)_setupEraseInstallDatabaseInitializationActivity;
- (void)_setupVisitLogActivity;
- (void)_storeConfirmationStatusToDisk;
- (void)_submitMetrics;
- (void)_updateMostRecentDateAtWhichDeviceDataIsTrusted;
- (void)_updateReferenceTimeBoundsFromVisitLog;
- (void)collectMetricDataForTest:(long long)a0 handler:(id /* block */)a1;
- (void)curateAuthorizedLocationsWithHandler:(id /* block */)a0;
- (void)eraseVisitLogDatabase:(id /* block */)a0;
- (void)fetchAuthorizedLocationCachedStatus:(id /* block */)a0;
- (void)fetchAuthorizedLocationDetailedStatus:(id /* block */)a0;
- (void)fetchAuthorizedLocationExtendedStatus:(id /* block */)a0;
- (void)fetchAuthorizedLocations:(id /* block */)a0;
- (void)fetchVisitLogsWithOptions:(id)a0 handler:(id /* block */)a1;
- (id)initWithVisitManager:(id)a0 locationManager:(id)a1 distanceCalculator:(id)a2 learnedLocationManager:(id)a3 motionActivityManager:(id)a4 visitLogStore:(id)a5 confirmationStatusStore:(id)a6 zdrLocationsStore:(id)a7 defaultsManager:(id)a8 xpcActivityManager:(id)a9 dataProtectionManager:(id)a10 persistenceMirroringManager:(id)a11 platform:(id)a12 authorizationManager:(id)a13;
- (void)onVisitMonitorNotification:(id)a0;
- (void)prepareTestSetup:(long long)a0;
- (void)prepareZDRLocationSetupForTesting:(id /* block */)a0;
- (void)runEraseInstallDatabaseInitialization:(id /* block */)a0;
- (void)runPeriodicConfirmationAlgorithmForTest:(id /* block */)a0;
- (void)testFetchZDRLocationStatus:(id)a0 fullSecurityAloiList:(id)a1 handler:(id /* block */)a2;
- (id)trustedTimeNow;

@end
