@class RTDefaultsManager, RTLocationManager, NSMutableArray, CLTripSegmentProcessorManager, RTElevationAdjuster, RTLearnedLocationManager, NSMutableDictionary, RTTripRegionChecker, RTTripSegmentManager, NSObject, RTTripClusterManager, RTVehicleStore, CLLocation, RTTripSegmentStore, RTMotionActivityManager, NSUUID, RTBackgroundInertialOdometryManager, RTTripSegmentInertialDataManager, RTTripClusterProcessorOptions, CLTripSegmentProcessorOptions, NSDate, RTTripSegmentTransitionPreprocessor;
@protocol OS_dispatch_queue;

@interface RTTripSegmentProvider : NSObject

@property (retain, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (retain, nonatomic) RTTripSegmentManager *tripSegmentManager;
@property (retain, nonatomic) CLTripSegmentProcessorManager *tripProcessorManager;
@property (retain, nonatomic) CLTripSegmentProcessorOptions *tripProcessorOptions;
@property (retain, nonatomic) RTTripSegmentInertialDataManager *inertialDataManager;
@property (retain, nonatomic) RTBackgroundInertialOdometryManager *inertialOdometryManager;
@property (retain, nonatomic) RTElevationAdjuster *elevationAdjuster;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTTripClusterManager *tripClusterManager;
@property (retain, nonatomic) RTTripClusterProcessorOptions *tripClusterProcessorOptions;
@property (retain, nonatomic) RTVehicleStore *vehicleStore;
@property (retain, nonatomic) RTTripSegmentStore *tripSegmentStore;
@property (retain, nonatomic) RTTripSegmentTransitionPreprocessor *transitionPreprocessor;
@property (retain, nonatomic) RTTripRegionChecker *regionChecker;
@property (retain, nonatomic) CLLocation *transitionStartLocation;
@property (retain, nonatomic) CLLocation *transitionStopLocation;
@property (retain, nonatomic) NSMutableArray *transitionLocations;
@property (retain, nonatomic) CLLocation *startVisitLocation;
@property (retain, nonatomic) CLLocation *stopVisitLocation;
@property (nonatomic) int tripSequenceNumberBetweenOneTransition;
@property (nonatomic) int maxTripSequenceNumberBetweenOneTransition;
@property (retain, nonatomic) NSUUID *tripCommuteID;
@property (nonatomic) double processingChunkWidthSeconds;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (nonatomic) BOOL sessionInProgress;
@property (nonatomic) BOOL usingLegacyInertialData;
@property (retain, nonatomic) NSMutableArray *transitionsToProcess;
@property (retain, nonatomic) NSDate *lastTransitionPreprocessTimestamp;
@property BOOL shouldDeferTripSegmentAndClusterProcessing;
@property (retain) NSUUID *idOfCurrentlyProcessingChunk;
@property (retain, nonatomic) NSMutableDictionary *debuggingData;
@property (nonatomic) int numTripSegmentsProcessedInThisProcessingCycle;
@property (nonatomic) int numTripSegmentChunksProcessedInThisProcessingCycle;
@property (nonatomic) int numTripSegmentProcessingFailedInThisProcessingCycle;
@property (nonatomic) BOOL fetchedNewTransitionsForProcessing;
@property (nonatomic) int successfulTransitionsSinceLastClustering;

+ (long long)CLTripModeFromRTModeOfTransportation:(long long)a0;
+ (id)convertToTripSegmentLocations:(id)a0;
+ (BOOL)isLocationTypeSupported:(int)a0;
+ (BOOL)isTripSegmentGenerationSupportedOnPlatform:(id)a0;

- (id)init;
- (void).cxx_destruct;
- (void)_updateClusterMetricTspRunTime:(double)a0;
- (BOOL)_isMatchingODPair:(id)a0 tripCluster2:(id)a1;
- (BOOL)processChunkWithIndex:(unsigned long long)a0 inChunks:(id)a1;
- (void)_checkAndStartReconstructTripSegmentWithTrainMode:(unsigned long long)a0 trainReason:(unsigned long long)a1 currentPipelineError:(id)a2 handler:(id /* block */)a3;
- (void)_computeMultiModalMetric;
- (void)_fetchAndPreProcessVisitTransitions;
- (id)_getTripClusterMetadata;
- (BOOL)_isValidTransitionToProcess:(id)a0;
- (void)_logDeferTripSegmentAndClusterProcessingDate:(id)a0;
- (void)_processNextVisitTransition:(unsigned long long)a0 completionHandler:(id /* block */)a1;
- (void)_processOneVisitTransition:(id)a0 trainMode:(unsigned long long)a1;
- (void)_processSingleOrCompoundedVisitTransition:(unsigned long long)a0;
- (void)_startReconstructTripSegmentWithTrainMode:(unsigned long long)a0 trainReason:(unsigned long long)a1 completionHandler:(id /* block */)a2;
- (void)_updateClusterMetricProcessingTime:(double)a0;
- (void)addToTransitionLocationsBuffer:(id)a0 forDateInterval:(id)a1;
- (void)addTripSegmentFeaturesItem:(id)a0 intoList:(id)a1 overlapDateInterval:(id)a2 uuidType:(long long)a3;
- (BOOL)allowReprocessingOfTransitionsWithTripSegments;
- (BOOL)applyElevationAdjustmentToBreadcrumbs;
- (id)buildTinySegmentArrayForTransitionWithIndex:(unsigned long long)a0 withinDateInterval:(id)a1 fromActivity:(id)a2 uuidType:(long long)a3;
- (id)buildTripSegmentsFeaturesWithIndex:(unsigned long long)a0 inTransitions:(id)a1 trainMode:(unsigned long long)a2 startVisitLocationOut:(id *)a3 stopVisitLocationOut:(id *)a4 transitionStartStopLocationsOut:(id *)a5;
- (BOOL)buildTripSegmentsFromTripSegmentFeaturesList:(id)a0 startVisitLocation:(id)a1 stopVisitLocation:(id)a2 transitionStartStopLocations:(id)a3;
- (BOOL)chunkLocationsCloseEnoughToCompound:(id)a0 stitchDateEndInterval:(id)a1;
- (id)collectVehicleConnectionTimeIntervals:(id)a0;
- (void)deferTripSegmentAndClusterProcessing:(BOOL)a0;
- (void)getCountDistanceStartAndEndDateOfLocationsInInterval:(id)a0 startDate:(id *)a1 endDate:(id *)a2 numLocations:(id *)a3 distance:(id *)a4;
- (int)getMaxTripSegmentDuration;
- (double)getProcessingChunkWidthSeconds;
- (id)getStoredLocationWithOptions:(id)a0;
- (id)getTransitionlocations;
- (id)getTripSegmentOfTypeFinalInThisTimeInterval:(id)a0;
- (id)getTripSegmentStartAndEndTimeUsingAllChunks:(id)a0 currentChunk:(id)a1 numLocations:(id *)a2 distance:(id *)a3;
- (id)initWithLearnedLocationManager:(id)a0 locationManager:(id)a1 motionActivityManager:(id)a2 tripSegmentInertialDataManager:(id)a3 inertialOdometryManager:(id)a4 vehicleStore:(id)a5 tripSegmentStore:(id)a6 tripSegmentManager:(id)a7 elevationAdjuster:(id)a8 distanceCalculator:(id)a9 defaultsManager:(id)a10 visitManager:(id)a11 tripClusterManager:(id)a12;
- (BOOL)isTripSegmentGenerationEnabled;
- (void)outputAndResetDebuggingData:(BOOL)a0 trainMode:(unsigned long long)a1 trainReason:(unsigned long long)a2;
- (void)prepareTripProcessorOptions;
- (BOOL)purgeUsedTripSegmentLocations;
- (void)saveFailedProcessingToTripSegmentMetaDataWithComuteID:(id)a0 inputData:(id)a1 allChunks:(id)a2 currentChunk:(id)a3 tripVisitStartLocation:(id)a4 tripVisitEndLocation:(id)a5 tripSegSequenceNumber:(int)a6 tripSegSequenceNumberMax:(int)a7 processingFailureError:(id)a8;
- (void)startTripSegmentAndClusterProcessing:(unsigned long long)a0 trainReason:(unsigned long long)a1 currentPipelineError:(id)a2 enableTripSegmentProcessingOnBattery:(BOOL)a3 handler:(id /* block */)a4;
- (id)trimTimeOfTripSegment:(id)a0 dateInterval:(id)a1 uuidType:(long long)a2;
- (void)unlockAllRouteClusters;

@end
