@class NSDictionary, MAAutoAssetInfoEnd, MAMsuDownloadOptions, NSMutableArray, NSString, MAAutoAssetInfoDesire, MAAutoAssetSelector, MADAutoSetJobInformation, MAAutoAssetSummary, NSMutableDictionary, MANAutoAssetSetNotifications, NSArray, MADAutoAssetDescriptor, MANAutoAssetSetInfoDesire, MAAutoAssetInfoListen, MANAutoAssetSetStatus, MAAutoAssetProgress, SUCoreLog, MANAutoAssetSetInfoInstance, MADAutoAssetJobInformation, SUCoreFSM, MAAutoAssetPolicy, MANAutoAssetSetPolicy, MANAutoAssetSetSummary, MAAutoAssetStatus, MANAutoAssetSetInfoFound, MADAutoSetDescriptor, MADAutoSetConfiguration, MAAutoAssetInfoInstance, MAAutoAssetInfoFound;

@interface MADAutoAssetJob : NSObject <SUCoreFSMDelegate>

@property (retain, nonatomic) MAAutoAssetInfoInstance *autoAssetInstance;
@property (retain, nonatomic) NSString *latestSafeSummary;
@property (retain, nonatomic) MAAutoAssetSummary *latestAutoAssetSummary;
@property (nonatomic) BOOL schedulerInvolved;
@property (nonatomic) BOOL potentialNetworkFailure;
@property (nonatomic) BOOL stagerJob;
@property (nonatomic) BOOL stagerJobDownloadContent;
@property (nonatomic) BOOL stagerJobResultsReported;
@property (retain, nonatomic) NSString *stagerAssetTargetOSVersion;
@property (retain, nonatomic) NSString *stagerAssetTargetBuildVersion;
@property (retain, nonatomic) NSString *stagerAssetTargetTrainName;
@property (retain, nonatomic) NSString *stagerAssetTargetRestoreVersion;
@property (retain, nonatomic) NSDictionary *stagerJobAutoAssetCatalog;
@property (retain, nonatomic) MADAutoAssetJob *bondedWithJob;
@property (readonly, retain, nonatomic) SUCoreLog *logger;
@property (retain, nonatomic) NSMutableArray *activeJobTasks;
@property (readonly, retain, nonatomic) NSDictionary *stateTable;
@property (retain, nonatomic) NSString *autoJobName;
@property (retain, nonatomic) SUCoreFSM *autoJobFSM;
@property (retain, nonatomic) MAAutoAssetInfoInstance *activeInstance;
@property (retain, nonatomic) MAAutoAssetInfoDesire *activeDesire;
@property (retain, nonatomic) MAAutoAssetInfoFound *activeFound;
@property (retain, nonatomic) MAAutoAssetInfoEnd *activeEnd;
@property (retain, nonatomic) MAAutoAssetInfoListen *activeListen;
@property (retain, nonatomic) MADAutoAssetJobInformation *autoAssetJobInformation;
@property (retain, nonatomic) MAAutoAssetPolicy *aggregatedClientAssetPolicy;
@property (nonatomic) BOOL aggregatedClientAssetPolicySpecified;
@property (nonatomic) BOOL clientRequestedOperation;
@property (retain, nonatomic) NSString *firstClientName;
@property (retain, nonatomic) NSString *jobCreationTriggeringLayer;
@property (retain, nonatomic) NSMutableDictionary *onFilesystemByVersion;
@property (retain, nonatomic) NSString *checkUUIDBasePortion;
@property (retain, nonatomic) NSString *checkUUID;
@property (nonatomic) BOOL holdingLookupGrant;
@property (nonatomic) BOOL rampingForeground;
@property (nonatomic) BOOL rampingForegroundLatched;
@property (retain, nonatomic) MAMsuDownloadOptions *catalogDownloadOptions;
@property (retain, nonatomic) MAMsuDownloadOptions *assetDownloadOptions;
@property (retain, nonatomic) MADAutoAssetDescriptor *baseForPatch;
@property (retain, nonatomic) MADAutoAssetDescriptor *foundNewerPatch;
@property (retain, nonatomic) MADAutoAssetDescriptor *foundNewerFull;
@property (retain, nonatomic) MADAutoAssetDescriptor *newerFoundAssetDescriptor;
@property (retain, nonatomic) MADAutoAssetDescriptor *downloadingAssetDescriptor;
@property (nonatomic) BOOL schedulerTriggerReceived;
@property (nonatomic) BOOL downloadingUserInitiated;
@property (nonatomic) BOOL boostedToUserInitiated;
@property (nonatomic) BOOL checkingAssetContent;
@property (nonatomic) BOOL determiningAssetContent;
@property (nonatomic) BOOL lockingAssetContent;
@property (nonatomic) BOOL wasPatched;
@property (retain, nonatomic) NSString *latestInstalledAssetVersion;
@property (retain, nonatomic) NSString *latestInstalledAssetBuild;
@property (retain, nonatomic) MAAutoAssetStatus *currentStatus;
@property (nonatomic) long long progressReportPhase;
@property (retain, nonatomic) MAAutoAssetProgress *lastReportedPatchProgress;
@property (retain, nonatomic) MAAutoAssetSelector *resultSelector;
@property (retain, nonatomic) MAAutoAssetInfoInstance *resultInstance;
@property (retain, nonatomic) MAAutoAssetInfoFound *resultFound;
@property (retain, nonatomic) MAAutoAssetInfoEnd *resultEnd;
@property (retain, nonatomic) MAAutoAssetInfoListen *resultListen;
@property (nonatomic) long long simulateOperation;
@property (nonatomic) long long simulateEnd;
@property (nonatomic) long long simulateTriggered;
@property (retain, nonatomic) MADAutoAssetDescriptor *simulateDescriptor;
@property (retain, nonatomic) MADAutoAssetDescriptor *simulateBaseForPatch;
@property (nonatomic) BOOL autoAssetSetJob;
@property (retain, nonatomic) NSString *clientDomainName;
@property (retain, nonatomic) NSString *autoAssetSetIdentifier;
@property (retain, nonatomic) MADAutoSetConfiguration *setConfiguration;
@property (retain, nonatomic) NSDictionary *cachedAutoAssetCatalog;
@property (retain, nonatomic) MADAutoSetJobInformation *setJobInformation;
@property (retain, nonatomic) MANAutoAssetSetInfoInstance *autoAssetSetInstance;
@property (retain, nonatomic) MANAutoAssetSetInfoDesire *autoAssetSetDesire;
@property (retain, nonatomic) MANAutoAssetSetPolicy *schedulerSetPolicy;
@property (retain, nonatomic) MANAutoAssetSetPolicy *stagerSetPolicy;
@property (retain, nonatomic) MANAutoAssetSetStatus *currentSetStatus;
@property (retain, nonatomic) MANAutoAssetSetNotifications *currentSetNotifications;
@property (retain, nonatomic) MANAutoAssetSetPolicy *aggregatedClientSetPolicy;
@property (nonatomic) BOOL aggregatedClientSetPolicySpecified;
@property (nonatomic) long long setProgressOverallTotalWrittenBytes;
@property (nonatomic) long long setProgressAssetTotalWrittenBytes;
@property (retain, nonatomic) MADAutoSetDescriptor *assignedSetDescriptor;
@property (retain, nonatomic) NSMutableDictionary *latestAssetDescriptorOnFilesystemBySpecifier;
@property (retain, nonatomic) NSMutableDictionary *foundSetPatchDescriptorsBySpecifier;
@property (retain, nonatomic) NSMutableDictionary *foundSetFullDescriptorsBySpecifier;
@property (retain, nonatomic) NSArray *foundSetNewerDiscoveredAtomicEntries;
@property (nonatomic) BOOL foundSameAtomicInstanceAlreadyDownloaded;
@property (retain, nonatomic) MANAutoAssetSetStatus *newestDownloadedSetStatus;
@property (retain, nonatomic) MADAutoSetDescriptor *autoAssetSetDescriptor;
@property (nonatomic) long long nextSetSpecifierToDownload;
@property (retain, nonatomic) MANAutoAssetSetSummary *latestAutoAssetSetSummary;
@property (nonatomic) BOOL anomalyNoAssignedSetDescriptor;
@property (nonatomic) BOOL anomalyNoActiveSetDescriptor;
@property (retain, nonatomic) MANAutoAssetSetInfoFound *resultSetFound;
@property (nonatomic) BOOL reportingProgress;
@property (nonatomic) int progressLogsFilteredCount;
@property (readonly, retain, nonatomic) MAAutoAssetSelector *autoAssetSelector;
@property (readonly, retain, nonatomic) NSString *autoAssetUUID;
@property (nonatomic) long long clientRequestCount;
@property (nonatomic) BOOL earlierSchedulerInvolved;
@property (nonatomic) BOOL beingCanceled;
@property (nonatomic) BOOL earlierPotentialNetworkFailure;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)_getAutoAssetJobStateTable;

- (void).cxx_destruct;
- (id)clientName;
- (id)summary;
- (id)_summary;
- (long long)actionUnknownAction:(id)a0 error:(id *)a1;
- (long long)performAction:(id)a0 onEvent:(id)a1 inState:(id)a2 withInfo:(id)a3 nextState:(id)a4 error:(id *)a5;
- (long long)action_DecideDonePurging:(id)a0 error:(id *)a1;
- (long long)action_JobFailedCanceled:(id)a0 error:(id *)a1;
- (long long)action_MergeContinueLock:(id)a0 error:(id *)a1;
- (long long)action_JobFailedAwaiting:(id)a0 error:(id *)a1;
- (long long)action_JobFailedSchedule:(id)a0 error:(id *)a1;
- (long long)action_SetDecideDownload:(id)a0 error:(id *)a1;
- (long long)errorCodeForNoNewerContentFound;
- (void)reportJustDownloadedAssetOfSet:(id)a0;
- (void)statusChangeSuccesfullyPatched:(id)a0;
- (void)_autoAssetJobFinished:(id)a0 forJobFinishedReason:(id)a1 failingWithError:(id)a2;
- (id)_baseAnalyticsData:(id)a0;
- (void)_extendAssetDownloadOptionsWithAnalyticsData:(id)a0 forDescriptor:(id)a1 withBaseForPatch:(id)a2;
- (void)_extendCatalogDownloadOptionsWithAnalyticsData:(id)a0;
- (id)_longSummary;
- (id)_newSelectorForCachedAssetCatalog:(id)a0;
- (void)_rememberIfSchedulerInvolved:(id)a0;
- (void)_setPolicyFromClientRequest:(id)a0;
- (void)_statusChangeDownloadProgressDecideLog:(id)a0;
- (id)_updateLatestSummary;
- (long long)action_AddAtomicAlterDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddAtomicCheckDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddAtomicContinueDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddAtomicEndDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddAtomicLockDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddAtomicNeedDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddTaskCheckDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddTaskDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddTaskDetermineDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddTaskInterestDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddTaskLockDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AddTaskScheduler:(id)a0 error:(id *)a1;
- (long long)action_AddTaskSchedulerDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_AdoptRegister:(id)a0 error:(id *)a1;
- (long long)action_BoostAndRequestLookupGrant:(id)a0 error:(id *)a1;
- (long long)action_BoostToUserInitiated:(id)a0 error:(id *)a1;
- (long long)action_CancelAssetDownload:(id)a0 error:(id *)a1;
- (long long)action_CheckSimulateEndStatusRequest:(id)a0 error:(id *)a1;
- (long long)action_DecideDownloadOrPostpone:(id)a0 error:(id *)a1;
- (long long)action_DecideStartupDownloading:(id)a0 error:(id *)a1;
- (long long)action_DoneReportingProgress:(id)a0 error:(id *)a1;
- (long long)action_DownloadCatalog:(id)a0 error:(id *)a1;
- (long long)action_DownloadNewestFull:(id)a0 error:(id *)a1;
- (long long)action_DownloadNewestPatch:(id)a0 error:(id *)a1;
- (long long)action_DownloadSuccessDecideMore:(id)a0 error:(id *)a1;
- (long long)action_FailRequestCanceling:(id)a0 error:(id *)a1;
- (long long)action_FailedPatchDecideTryFull:(id)a0 error:(id *)a1;
- (long long)action_JobEndedSchedule:(id)a0 error:(id *)a1;
- (long long)action_JobNoNewerSchedule:(id)a0 error:(id *)a1;
- (long long)action_JobPostponedSchedule:(id)a0 error:(id *)a1;
- (long long)action_JobRevokedSchedule:(id)a0 error:(id *)a1;
- (long long)action_JobSuccessAlreadyDownloaded:(id)a0 error:(id *)a1;
- (long long)action_JobSuccessDownloadedAwaiting:(id)a0 error:(id *)a1;
- (long long)action_JobSuccessDownloadedSchedule:(id)a0 error:(id *)a1;
- (long long)action_JobSuccessFoundSameSchedule:(id)a0 error:(id *)a1;
- (long long)action_JobSuccessPatchedAwaiting:(id)a0 error:(id *)a1;
- (long long)action_JobSuccessPatchedSchedule:(id)a0 error:(id *)a1;
- (long long)action_LookupFailedContinue:(id)a0 error:(id *)a1;
- (long long)action_LookupNoNewerContinue:(id)a0 error:(id *)a1;
- (long long)action_LookupRevokedContinue:(id)a0 error:(id *)a1;
- (long long)action_LookupSuccessContinue:(id)a0 error:(id *)a1;
- (long long)action_MergeAddLock:(id)a0 error:(id *)a1;
- (long long)action_MergeAddLockDecideBoost:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicAddLock:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicAlterDecideLookup:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicAlterDecideLookupBoost:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicAlterNeeds:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicCntnuDecideLookupBoost:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicContinueLock:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicEndLockDecideInterest:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicLockDecideLookupBoost:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicNeeds:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicNeedsDecideLookup:(id)a0 error:(id *)a1;
- (long long)action_MergeAtomicNeedsDecideLookupBoost:(id)a0 error:(id *)a1;
- (long long)action_MergeContinueLockDecideBoost:(id)a0 error:(id *)a1;
- (long long)action_MergeNeeds:(id)a0 error:(id *)a1;
- (long long)action_MergeNeedsDecideBoost:(id)a0 error:(id *)a1;
- (long long)action_MergeNeedsDecideLookup:(id)a0 error:(id *)a1;
- (long long)action_MergeNeedsDecideLookupBoost:(id)a0 error:(id *)a1;
- (long long)action_MergeRemoveLock:(id)a0 error:(id *)a1;
- (long long)action_MergeRemoveLockDecideInterest:(id)a0 error:(id *)a1;
- (long long)action_NowUserInitiated:(id)a0 error:(id *)a1;
- (long long)action_PersistedDecideDownload:(id)a0 error:(id *)a1;
- (long long)action_RecordSimulateOperation:(id)a0 error:(id *)a1;
- (long long)action_ReleaseGrantCanceling:(id)a0 error:(id *)a1;
- (long long)action_ReleaseGrantJobFailedCanceled:(id)a0 error:(id *)a1;
- (long long)action_ReleaseGrantJobFailedSchedule:(id)a0 error:(id *)a1;
- (long long)action_RemoveClient:(id)a0 error:(id *)a1;
- (long long)action_RemoveClientDecideInterest:(id)a0 error:(id *)a1;
- (long long)action_ReportCatalogDecideFound:(id)a0 error:(id *)a1;
- (long long)action_ReportFailBoostSetDownloadNext:(id)a0 error:(id *)a1;
- (long long)action_ReportFailureUserInitiated:(id)a0 error:(id *)a1;
- (long long)action_RequestLookupGrant:(id)a0 error:(id *)a1;
- (long long)action_RequestSpecificPersisted:(id)a0 error:(id *)a1;
- (long long)action_SetDoneDetermine:(id)a0 error:(id *)a1;
- (long long)action_SetDownloadNewestFull:(id)a0 error:(id *)a1;
- (long long)action_SetDownloadNext:(id)a0 error:(id *)a1;
- (long long)action_SetDownloadSameFull:(id)a0 error:(id *)a1;
- (long long)action_SetJobEndedSchedule:(id)a0 error:(id *)a1;
- (long long)action_SetJobFailedAwaiting:(id)a0 error:(id *)a1;
- (long long)action_SetJobFailedSchedule:(id)a0 error:(id *)a1;
- (long long)action_SetJobLookupRevokedContinue:(id)a0 error:(id *)a1;
- (long long)action_SetJobNoNewerSchedule:(id)a0 error:(id *)a1;
- (long long)action_SetJobNoneSchedule:(id)a0 error:(id *)a1;
- (long long)action_SetJobSuccessAwaiting:(id)a0 error:(id *)a1;
- (long long)action_SetJobSuccessFoundSameSchedule:(id)a0 error:(id *)a1;
- (long long)action_SetJobSuccessSchedule:(id)a0 error:(id *)a1;
- (long long)action_SetLookupNoNewerContinue:(id)a0 error:(id *)a1;
- (long long)action_SetLookupNoneContinue:(id)a0 error:(id *)a1;
- (long long)action_SetLookupSuccessContinue:(id)a0 error:(id *)a1;
- (long long)action_SimulateSuspendCatalogLookupIssue:(id)a0 error:(id *)a1;
- (long long)action_StagerDetermineDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_StagerDownloadDecideFilesystem:(id)a0 error:(id *)a1;
- (long long)action_UserInitiatedDownloadNewestFull:(id)a0 error:(id *)a1;
- (long long)action_UserInitiatedSetDownloadNext:(id)a0 error:(id *)a1;
- (void)addClientRequestAndMergeNeeds:(id)a0 forJobEvent:(id)a1;
- (void)addToActiveJobTasks:(id)a0;
- (void)adoptCachedLookupResult:(id)a0;
- (BOOL)anyJobInterestedInContent;
- (void)appendUniqueSelectorForDescriptor:(id)a0 toArray:(id)a1;
- (id)assetSetEntryForAssetMetadata:(id)a0;
- (void)autoAssetJobFinished:(id)a0 forJobFinishedReason:(id)a1;
- (void)autoAssetJobFinished:(id)a0 forJobFinishedReason:(id)a1 failingWithError:(id)a2;
- (id)autoAssetSetAssetType;
- (BOOL)buildPotentialDescriptors:(id)a0 fromLookupResults:(id)a1 buildingPatchDescriptors:(id)a2 andFullDescriptors:(id)a3;
- (void)cancelAutoAssetJob;
- (void)checkFilesystemAndDecidePurgeOrLookup;
- (void)clearSetStatusStartingSetJob;
- (void)clientRequestedStatus:(id)a0;
- (id)currentJobInformation:(id *)a0;
- (id)decideFollowupBoost:(id)a0 forJobEvent:(id)a1 boostEvent:(id)a2 noBoostEvent:(id)a3;
- (void)desireChangedToUserInitiated;
- (void)determineWhetherNetworkConnectivityError:(id)a0;
- (void)doneWithAllJobs:(id)a0;
- (void)doneWithAllJobs:(id)a0 withLookupError:(id)a1;
- (void)downloadCatalog:(id)a0;
- (long long)errorCodeFromUnderling:(id)a0;
- (void)exclusiveLookupForAssetTypeGranted:(id)a0;
- (void)finishJobTaskForJobParam:(id)a0 withResponseError:(id)a1;
- (void)finishJobTaskForJobParam:(id)a0 withUnderlyingError:(id)a1 fromAction:(id)a2;
- (void)finishedSetJobFinalizeStatus:(id)a0 failingWithError:(id)a1;
- (void)foundAndDownloaded:(id)a0 forJobParam:(id)a1 wasPatched:(BOOL)a2;
- (void)foundAndDownloadedSet:(id)a0;
- (id)getCurrentJobTask;
- (void)handleClientRequest:(id)a0 withControlInformation:(id)a1;
- (void)handleDownloadAssetJobFinished:(id)a0 downloadError:(id)a1;
- (void)handleDownloadAssetProgressForJob:(id)a0 withProgress:(id)a1;
- (void)handleDownloadCatalogJobFinished:(id)a0 withCatalog:(id)a1 downloadError:(id)a2;
- (void)handleDownloadConfigJobFinished:(id)a0 configError:(id)a1;
- (void)handleSimulateOperation:(id)a0;
- (id)initForDescriptor:(id)a0 baseForPatchDescriptor:(id)a1 withAutoAssetUUID:(id)a2;
- (id)initForInstance:(id)a0 orForSelector:(id)a1 orForDescriptor:(id)a2 orForSetInstance:(id)a3 withSetDesire:(id)a4 withSchedulerSetPolicy:(id)a5 withStagerSetPolicy:(id)a6 usingSetConfiguration:(id)a7 usingSetDescriptor:(id)a8 withBaseForPatchDescriptor:(id)a9 withAutoAssetUUID:(id)a10 downloadingUserInitiated:(BOOL)a11 asStagerJob:(BOOL)a12 usingCachedAutoAssetCatalog:(id)a13;
- (id)initForInstance:(id)a0 withAutoAssetUUID:(id)a1 downloadingUserInitiated:(BOOL)a2;
- (id)initForSelector:(id)a0 withAutoAssetUUID:(id)a1;
- (id)initForSelector:(id)a0 withAutoAssetUUID:(id)a1 asStagerJob:(BOOL)a2 withStagerSetPolicy:(id)a3 usingCachedAutoAssetCatalog:(id)a4 usingBaseForPatching:(id)a5;
- (id)initForSetConfiguration:(id)a0 withAutoAssetUUID:(id)a1 asStagerJob:(BOOL)a2 withStagerSetPolicy:(id)a3;
- (id)initForSetInstance:(id)a0 withSchedulerSetPolicy:(id)a1 usingSetConfiguration:(id)a2 usingSetDescriptor:(id)a3 withAutoAssetUUID:(id)a4;
- (id)initForSetInstance:(id)a0 withSetDesire:(id)a1 usingSetConfiguration:(id)a2 usingSetDescriptor:(id)a3 withAutoAssetUUID:(id)a4;
- (id)installedOnFilesystemWithVersion:(id)a0 fromLocation:(id)a1;
- (BOOL)isFoundAlreadyOnFilesystem;
- (BOOL)isMorePreferredFormat:(id)a0 comparedTo:(id)a1;
- (BOOL)isSetFoundAlreadyOnFilesystem:(id)a0 justPromotedAnyDescriptor:(BOOL *)a1;
- (void)latchWhetherDownloadingUserInitiated;
- (id)latestInstalledOnFilesystem;
- (void)mergeSetPolicyIntoAggregated:(id)a0;
- (id)mostSpecificSelectorToReport;
- (id)newAssetDownloadOptions;
- (id)newAtomicInstancesDownloadedForDescriptor:(id)a0;
- (id)newCatalogDownloadOptions;
- (id)newCurrentStatusForDescriptor:(id)a0;
- (id)newFoundSetDescriptorsAsNewerDiscovered;
- (void)newFoundSetDescriptorsFromCachedLookup:(id)a0;
- (id)newSessionID;
- (void)obtainLookupGrant;
- (void)persistedStateForDownloadJob:(id)a0;
- (BOOL)placeNextSetAssetDescriptorToDownload:(id)a0 restrictToFull:(BOOL)a1 error:(id *)a2;
- (BOOL)preferenceAsIfRampOrUse:(BOOL)a0;
- (id)progressReportPhaseName;
- (void)refreshDownloadedToManager;
- (void)refreshFoundToManager;
- (id)refreshOnFilesystemFromManagerPromotingIfStaged:(BOOL)a0;
- (void)refreshSetFoundToManager:(BOOL)a0;
- (void)releaseLookupGrant;
- (BOOL)remainingSetDescriptorToBeDownloaded;
- (id)removeCurrentJobTask;
- (void)replyToClientForJobParam:(id)a0 withResponseError:(id)a1;
- (void)replyToJobsWhenCatalogDownloaded:(id)a0 discoveredNewer:(BOOL)a1;
- (void)replyToJobsWhenContentDownloaded:(id)a0;
- (void)replyToJobsWhenLookupFailed:(id)a0 withLookupError:(id)a1;
- (void)replyToJobsWhenOperationFoundSame:(id)a0 forCheckAtomic:(BOOL)a1 withLookupError:(id)a2;
- (void)replyToSetCheckAtomicDownloadSuccess;
- (id)reportSetCatalogDecideFound:(id)a0;
- (void)requestDownloadManagerAssetDownload:(id)a0 forDescriptor:(id)a1 withBaseForPatch:(id)a2;
- (void)requestDownloadManagerCancelDownload:(id)a0 forDescriptor:(id)a1;
- (void)requestDownloadManagerCatalogLookup:(id)a0;
- (void)requestDownloadManagerConfigDownload:(id)a0 forDescriptor:(id)a1;
- (void)setCurrentJobTask:(id)a0;
- (id)setEntryBeingDownloaded;
- (void)setProgressAssetDownload:(id)a0;
- (void)setProgressReadyToStartDownloads;
- (void)simulateEnd:(long long)a0;
- (void)simulateSet:(id)a0;
- (void)stagerJobDetermineDone:(id)a0 reportingError:(id)a1;
- (void)stagerJobDone:(id)a0 reportingError:(id)a1;
- (void)stagerJobDownloadDone:(id)a0 reportingError:(id)a1;
- (void)stagerJobReportProgress:(id)a0 reportingError:(id)a1;
- (void)startHandlingClientRequest:(id)a0 withControlInformation:(id)a1;
- (void)startResumingInFlightDownload:(id)a0 withControlInformation:(id)a1;
- (void)startScheduleTriggeredSelector:(id)a0 withControlInformation:(id)a1;
- (void)startScheduleTriggeredSetJob:(id)a0;
- (void)startStagerDetermineIfAvailable:(id)a0 withAssetTargetBuildVersion:(id)a1 withAssetTargetTrainName:(id)a2 withAssetTargetRestoreVersion:(id)a3 withControlInformation:(id)a4;
- (void)startStagerDownloadForStaging:(id)a0 withAssetTargetBuildVersion:(id)a1 withControlInformation:(id)a2;
- (void)statusChange:(id)a0 catalogAnomaly:(long long)a1 forReason:(id)a2;
- (void)statusChange:(id)a0 catalogFailure:(long long)a1 forReason:(id)a2;
- (void)statusChangeCatalogFoundNewer:(id)a0;
- (void)statusChangeCatalogFoundSame:(id)a0;
- (void)statusChangeDownloadProgress:(id)a0;
- (void)statusChangeJobFinished:(id)a0 withResponseError:(id)a1;
- (void)statusChangeReportCurrent:(id)a0;
- (void)statusChangeSetCatalogFoundNewer:(id)a0;
- (void)statusChangeSetCatalogFoundSame:(id)a0;
- (void)statusChangeStartingAssetDownload:(id)a0 downloadingPatch:(BOOL)a1;
- (void)statusChangeSuccessfullyDownloaded:(id)a0;
- (id)summaryOfJob;
- (void)trackAnomaly:(long long)a0 forReason:(id)a1;
- (void)updateAutoAssetSetDescriptor;
- (void)updateResultPropertiesWithDescriptor:(id)a0;
- (void)updateSetDescriptorDownloaded:(id)a0 justDownloaded:(BOOL)a1;
- (void)updateSetResults:(id)a0 atomicInstanceDiscovered:(BOOL)a1 availableForUse:(BOOL)a2 downloading:(BOOL)a3 buildingResultSetFound:(BOOL)a4;
- (void)updateSetTrackingWithSuccessfulAssetDownload;
- (id)verifyDownloadNotBlockedBySetPolicy:(BOOL)a0;
- (BOOL)wasAssetSetSpecifierRequested:(id)a0;

@end
