@class RTLearnedLocationReconcilerPerVisit, RTDefaultsManager, RTContactsManager, RTLocationStore, RTBiomeManager, RTMapServiceManager, RTMapsSupportManager, RTFingerprintManager, RTLocationManager, RTAccountManager, RTLearnedLocationEngineTrainingMetrics, RTSettledStateTransitionStore, RTLearnedLocationReconcilerPerDevice, RTVisitManager, RTXPCActivityManager, RTTransitMetricManager, RTPlatform, RTDistanceCalculator, RTPlaceTypeClassifierMetricsCalculator, NSString, NSObject, RTDailyTrainingSessionCounter, RTPointOfInterestMetricsManager, RTPlaceInferenceQueryStore, RTMetricManager, RTEventManager, RTDiagnostics, RTLearnedPlaceTypeInferenceStore, RTPersonalizationPortraitManager, RTElevationManager, RTMotionActivityManager, RTLearnedLocationStore, RTTripSegmentProvider;
@protocol OS_dispatch_queue, RTLearnedLocationEngineProtocol;

@interface RTLearnedLocationEngine : NSObject <RTPurgable, RTDiagnosticProvider>

@property (nonatomic) BOOL registerTrainOnBattery;
@property (nonatomic) BOOL shouldRecoverKnownPlaceTypes;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (readonly, nonatomic) RTAccountManager *accountManager;
@property (readonly, nonatomic) RTBiomeManager *biomeManager;
@property (readonly, nonatomic) RTContactsManager *contactsManager;
@property (readonly, nonatomic) RTDailyTrainingSessionCounter *dailyTrainingSessionCounter;
@property (readonly, nonatomic) RTDefaultsManager *defaultsManager;
@property (readonly, nonatomic) RTDiagnostics *diagnostics;
@property (readonly, nonatomic) RTElevationManager *elevationManager;
@property (readonly, nonatomic) RTEventManager *eventManager;
@property (readonly, nonatomic) RTFingerprintManager *fingerprintManager;
@property (readonly, nonatomic) RTLearnedLocationStore *learnedLocationStore;
@property (readonly, nonatomic) RTLearnedPlaceTypeInferenceStore *learnedPlaceTypeInferenceStore;
@property (readonly, nonatomic) RTDistanceCalculator *distanceCalculator;
@property (readonly, nonatomic) RTLocationStore *locationStore;
@property (readonly, nonatomic) RTLocationManager *locationManager;
@property (readonly, nonatomic) RTMapServiceManager *mapServiceManager;
@property (readonly, nonatomic) RTMapsSupportManager *mapsSupportManager;
@property (readonly, nonatomic) RTPlaceTypeClassifierMetricsCalculator *placeTypeClassifierMetricsCalculator;
@property (readonly, nonatomic) RTMetricManager *metricManager;
@property (readonly, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (readonly, nonatomic) RTPlaceInferenceQueryStore *placeInferenceQueryStore;
@property (readonly, nonatomic) RTPlatform *platform;
@property (readonly, nonatomic) RTPointOfInterestMetricsManager *pointOfInterestMetricsManager;
@property (readonly, nonatomic) RTPersonalizationPortraitManager *portraitManager;
@property (retain, nonatomic) RTLearnedLocationEngineTrainingMetrics *trainingMetrics;
@property (readonly, nonatomic) RTLearnedLocationReconcilerPerVisit *reconcilerPerVisit;
@property (readonly, nonatomic) RTLearnedLocationReconcilerPerDevice *reconcilerPerDevice;
@property (readonly, nonatomic) RTSettledStateTransitionStore *settledStateTransitionStore;
@property (readonly, nonatomic) RTTransitMetricManager *transitMetricManager;
@property (readonly, nonatomic) RTTripSegmentProvider *tripSegmentProvider;
@property (readonly, nonatomic) RTVisitManager *visitManager;
@property (readonly, nonatomic) RTXPCActivityManager *xpcActivityManager;
@property (nonatomic) BOOL monitorFingerprints;
@property (weak, nonatomic) id<RTLearnedLocationEngineProtocol> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)computeVisitLabelingMetricsForLabelingRetried:(BOOL)a0 labelingSkipped:(BOOL)a1 revGeoCalled:(BOOL)a2 bluePOICalled:(BOOL)a3 unlabeledVisit:(BOOL)a4 visitAge:(double)a5 error:(id)a6;
+ (long long)periodicPurgePolicy;
+ (void)submitVisitLabelingMetricsForLabelingRetried:(BOOL)a0 labelingSkipped:(BOOL)a1 revGeoCalled:(BOOL)a2 bluePOICalled:(BOOL)a3 unlabeledVisit:(BOOL)a4 visitAge:(double)a5 error:(id)a6;

- (id)init;
- (void).cxx_destruct;
- (void)_registerForNotifications;
- (void)_setup;
- (void)_unregisterForNotifications;
- (void)shutdown;
- (BOOL)_isAuthorized;
- (void)_shutdown;
- (void)_classifyPlaceTypesWithHandler:(id /* block */)a0;
- (BOOL)_isRecentVisit:(id)a0;
- (BOOL)_isUpdateLearnedPlaceWithGEOAddressObjectSerializationRequired:(id)a0;
- (id)_storedMapItemForMapItem:(id)a0 error:(id *)a1;
- (BOOL)_deferTrainingDueToAvailability;
- (id)_filterVisits:(id)a0 lastLearnedVisit:(id)a1;
- (id)_mapItemProviderForClass:(Class)a0 error:(id *)a1;
- (void)_onContactsManagerNotification:(id)a0;
- (id)createRelabeler;
- (id)extractCandidate:(id)a0 fromNearbyCandidates:(id)a1 extractedCandidate:(id *)a2 error:(id *)a3;
- (BOOL)_appendVisits:(id)a0 lastVisit:(id)a1 lastTransition:(id)a2 outError:(id *)a3;
- (BOOL)_appendVisitsToLocationsOfInterestModelWithError:(id *)a0;
- (id)_bestFusedInferredMapItemForVisit:(id)a0 fromCandidates:(id)a1 error:(id *)a2;
- (id)_bestInferredMapItemForVisit:(id)a0 bestFinerGranularityInferredMapItem:(id *)a1 error:(id *)a2;
- (id)_candidatesForInferredMapItems:(id)a0 error:(id *)a1;
- (id)_candidatesForVisit:(id)a0 providers:(id)a1 continueOnError:(BOOL)a2 error:(id *)a3;
- (BOOL)_classifyPlaceTypes:(id *)a0;
- (BOOL)_consolidateKnownPlaceTypesWithError:(id *)a0;
- (id)_createLocationOfInterestsWithVisits:(id)a0 visitToTransitionMapping:(id)a1 visitToPlaceMapping:(id)a2;
- (BOOL)_deferSubmittingLoiMetricsDueToNoTrainingSinceLastSubmission;
- (BOOL)_deferTrainingDueToRecentResetSync;
- (BOOL)_deferTrainingLOIsDueToCloudStoreNotChangeSinceLastTrainingDate:(id)a0;
- (BOOL)_deferTrainingOnBatteryDueToLackOfLongVisitSinceDate:(id)a0;
- (BOOL)_enableTrainOnBatteryForTripSegments;
- (id)_enabledMapItemProviders;
- (id)_extractBluePOIQueriesJSONDObjectBetweenStartDate:(id)a0 endDate:(id)a1 error:(id *)a2;
- (id)_extractBluePOIQueriesJSONDObjectForVisit:(id)a0 bluePOIMapItemProvider:(id)a1;
- (id)_fetchCloudCurrentDeviceVisitsBetweenStartDate:(id)a0 endDate:(id)a1 ascending:(BOOL)a2 error:(id *)a3;
- (void)_fetchLatestVisitWithHandler:(id /* block */)a0;
- (id)_finerGranularityCandidatesDictionaryForFusionCandidates:(id)a0;
- (id)_finerGranularityPOIForInferredMapItem:(id)a0 visit:(id)a1 finerGranularityCandidatesDictionary:(id)a2 error:(id *)a3;
- (BOOL)_generateDiagnosticFilesAtURL:(id)a0 error:(id *)a1;
- (id)_getDailyTrainingMetrics;
- (void)_harvestFeedbackData;
- (void)_harvestVisits:(id)a0 places:(id)a1;
- (BOOL)_homeLocationOfInterestExist;
- (BOOL)_isAOIInferredMapItem:(id)a0;
- (BOOL)_isBluePOICalledForVisit:(id)a0 providers:(id)a1;
- (BOOL)_isFinerGranularityPOIInferredMapItem:(id)a0;
- (BOOL)_isNotTooOldToLabelVisit:(id)a0;
- (BOOL)_isUpdateLearnedPlaceWithISO3166CountryCodeAndSubdivisionCodeRequired:(id)a0;
- (BOOL)_isUpdateLearnedPlaceWithMapItemPlaceTypeRequired:(id)a0;
- (BOOL)_isUpdateLearnedPlaceWithPOICategoryCodeRequired:(id)a0;
- (id)_lastVisitWithError:(id *)a0;
- (void)_logCloudStoreWithReason:(id)a0;
- (void)_logDatabasesWithReason:(id)a0;
- (void)_logLocalStoreWithReason:(id)a0;
- (id)_maximumExpirationDateForLearnedPlace:(id)a0;
- (BOOL)_momentsdOnBoarding;
- (void)_onDailyMetricsNotification:(id)a0;
- (void)_onFingerprintManagerNotification:(id)a0;
- (void)_onLearnedLocationStoreNotification:(id)a0;
- (void)_onMapsSupportManagerNotification:(id)a0;
- (void)_onVisitManagerNotification:(id)a0;
- (id)_performPerDeviceReconiliationWithError:(id *)a0;
- (id)_performPerVisitReconciliationWithError:(id *)a0;
- (id)_placeForMapItem:(id)a0 error:(id *)a1;
- (BOOL)_processVisits:(id)a0 forLastLearnedVisit:(id)a1 error:(id *)a2;
- (BOOL)_purgeWithReferenceDate:(id)a0 error:(id *)a1;
- (BOOL)_reconcileLearnedLocationsWithError:(id *)a0;
- (void)_reconcileLearnedLocationsWithHandler:(id /* block */)a0;
- (BOOL)_recoverKnownPlaceTypesWithPlaceTypeClassifier:(id)a0 outError:(id *)a1;
- (BOOL)_refreshMapItemsForLocationsOfInterestWithError:(id *)a0;
- (void)_registerXpcActivityTrainOnBattery;
- (BOOL)_relabelWithError:(id *)a0;
- (BOOL)_relabelWithRelabeler:(id)a0 relabelerPersister:(id)a1 error:(id *)a2;
- (BOOL)_removeUnusedMapItems:(id *)a0;
- (void)_requestTrainLocationsOfInterestModelWithHandler:(id /* block */)a0;
- (BOOL)_retrainVisitsWithoutPlaces:(id *)a0;
- (BOOL)_saveIdentifiersOfKnownPlaceTypesWithError:(id *)a0;
- (void)_setupTrainingMetricsFromDate:(id)a0 toDate:(id)a1 mode:(unsigned long long)a2 reason:(unsigned long long)a3;
- (void)_setupXpcActivityTrain;
- (BOOL)_skipLabelingForVisit:(id)a0;
- (void)_submitDailyTrainingMetrics;
- (void)_submitDailyTrainingSessionCount;
- (BOOL)_submitDailyVisitMetrics;
- (void)_submitMetricsForVisit:(id)a0 possibleInferredMapItems:(id)a1 selectedInferredMapItem:(id)a2;
- (void)_submitPlaceTypeClassificationFeatureInputMetrics;
- (void)_teardownTrainingMetrics;
- (void)_teardownXpcActivityTrain;
- (void)_trainForReason:(unsigned long long)a0 mode:(unsigned long long)a1 handler:(id /* block */)a2;
- (BOOL)_trainLocationsOfInterestModelWithError:(id *)a0;
- (BOOL)_trainVisitsFromDate:(id)a0 toDate:(id)a1 forLastLearnedVisit:(id)a2 error:(id *)a3;
- (void)_trainWithFromDate:(id)a0 ToDate:(id)a1 forLastLearnedVisit:(id)a2 reason:(unsigned long long)a3 mode:(unsigned long long)a4 handler:(id /* block */)a5;
- (id)_transitionsForVisits:(id)a0 lastLearnedVisit:(id)a1 creationDate:(id)a2;
- (void)_unregisterXpcActivityTrainOnBattery;
- (id)_updateLearnedPlaceWithCategory:(id)a0;
- (id)_updateLearnedPlaceWithGEOAddressObjectSerialization:(id)a0;
- (id)_updateLearnedPlaceWithISO3166CountryCodeAndSubdivisionCode:(id)a0;
- (id)_updateLearnedPlaceWithMapItemPlaceType:(id)a0;
- (id)_updateLocationOfInterestsWithVisits:(id)a0 visitToTransitionMapping:(id)a1 visitToLocationOfInterestMapping:(id)a2;
- (void)_updateMonitorFingerprintsWithVisit:(id)a0;
- (void)_updateUnlabeledVisitsWithPlaceInformation:(id)a0;
- (id)_visitsFromDate:(id)a0 toDate:(id)a1 error:(id *)a2;
- (id)calculateMetricsToReplayOldHomeWorkInferenceAlgoWithStartDate:(id)a0 endDate:(id)a1 homeMapItem:(id)a2 workMapItem:(id)a3 locationsOfOthers:(id *)a4 error:(id *)a5;
- (void)calculateNewMetricsAndSubmitAlongWithTheOldMetrics:(id)a0 startDate:(id)a1 endDate:(id)a2 homeMapItem:(id)a3 workMapItem:(id)a4 distanceThresholdArray:(id)a5 locationsOfOthers:(id)a6;
- (void)classifyPlaceTypesWithHandler:(id /* block */)a0;
- (id)createRelabelerPersisterWithError:(id *)a0;
- (id)dataWithBluePOIQueriesBetweenStartDate:(id)a0 endDate:(id)a1 error:(id *)a2;
- (void)didClear;
- (void)didFinishTraining;
- (void)didUpdateWithIntervalSinceLastUpdate:(double)a0;
- (void)fetchFusionCandidatesForVisit:(id)a0 handler:(id /* block */)a1;
- (id)getNearbyCandidatesAroundLocation:(id)a0 distance:(double)a1 loiIdentifierToCoalescedSourceMap:(id)a2 error:(id *)a3;
- (id)getRelabeledInferredMapItemForCandidate:(id)a0 relabeler:(id)a1 loiIdentifierToCoalescedSourceMap:(id)a2 submitMetrics:(BOOL)a3 error:(id *)a4;
- (id)initWithAccountManager:(id)a0 biomeManager:(id)a1 contactsManager:(id)a2 dailyTrainingSessionCounter:(id)a3 defaultsManager:(id)a4 diagnostics:(id)a5 distanceCalculator:(id)a6 elevationManager:(id)a7 eventManager:(id)a8 fingerprintManager:(id)a9 learnedLocationStore:(id)a10 learnedPlaceTypeInferenceStore:(id)a11 locationManager:(id)a12 locationStore:(id)a13 mapServiceManager:(id)a14 mapsSupportManager:(id)a15 metricManager:(id)a16 motionActivityManager:(id)a17 placeInferenceQueryStore:(id)a18 platform:(id)a19 pointOfInterestMetricsManager:(id)a20 portraitManager:(id)a21 reconcilerPerVisit:(id)a22 reconcilerPerDevice:(id)a23 settledStateTransitionStore:(id)a24 transitMetricManager:(id)a25 tripSegmentProvider:(id)a26 visitManager:(id)a27 xpcActivityManager:(id)a28;
- (void)onContactsManagerNotification:(id)a0;
- (void)onDailyMetricsNotification:(id)a0;
- (void)onFingerprintManagerNotification:(id)a0;
- (void)onLearnedLocationStoreNotification:(id)a0;
- (void)onMapsSupportManagerNotification:(id)a0;
- (void)onVisitManagerNotification:(id)a0;
- (void)performPurgeOfType:(long long)a0 referenceDate:(id)a1 completion:(id /* block */)a2;
- (void)performTransitAnalyticsWithHandler:(id /* block */)a0;
- (void)queryMapItemProvider:(id)a0 options:(id)a1 handler:(id /* block */)a2;
- (void)reconcileLearnedLocationsWithHandler:(id /* block */)a0;
- (void)relabelWithHandler:(id /* block */)a0;
- (void)requestTrainLocationsOfInterestModelWithHandler:(id /* block */)a0;
- (void)sendDiagnosticsToURL:(id)a0 options:(id)a1 handler:(id /* block */)a2;
- (void)setup;
- (void)submitVisitSettledStateMetricsForVisits:(id)a0 transitions:(id)a1;
- (void)trainForReason:(unsigned long long)a0 mode:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)trainLocationsOfInterestModelWithHandler:(id /* block */)a0;
- (void)willBeginTraining;

@end
