@class RTLearnedLocationReconcilerPerVisit, RTDefaultsManager, RTContactsManager, RTLocationStore, RTMapsSupportManager, RTMapServiceManager, RTFingerprintManager, RTLocationManager, RTVisitManager, RTAccountManager, RTLearnedLocationEngineTrainingMetrics, RTSettledStateTransitionStore, RTLearnedLocationReconcilerPerDevice, RTXPCActivityManager, NSString, RTTransitMetricManager, RTPlatform, RTDistanceCalculator, NSObject, RTPersonalizationPortraitManager, RTMetricManager, RTEventManager, RTDiagnostics, RTMotionActivityManager, RTLearnedLocationStore;
@protocol OS_dispatch_queue, RTLearnedLocationEngineProtocol;

@interface RTLearnedLocationEngine : NSObject <RTPurgable>

@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (readonly, nonatomic) RTAccountManager *accountManager;
@property (readonly, nonatomic) RTContactsManager *contactsManager;
@property (readonly, nonatomic) RTDefaultsManager *defaultsManager;
@property (readonly, nonatomic) RTDiagnostics *diagnostics;
@property (readonly, nonatomic) RTEventManager *eventManager;
@property (readonly, nonatomic) RTFingerprintManager *fingerprintManager;
@property (readonly, nonatomic) RTLearnedLocationStore *learnedLocationStore;
@property (readonly, nonatomic) RTDistanceCalculator *distanceCalculator;
@property (readonly, nonatomic) RTLocationStore *locationStore;
@property (readonly, nonatomic) RTLocationManager *locationManager;
@property (readonly, nonatomic) RTMapServiceManager *mapServiceManager;
@property (readonly, nonatomic) RTMapsSupportManager *mapsSupportManager;
@property (readonly, nonatomic) RTMetricManager *metricManager;
@property (readonly, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (readonly, nonatomic) RTPlatform *platform;
@property (readonly, nonatomic) RTPersonalizationPortraitManager *portraitManager;
@property (retain, nonatomic) RTLearnedLocationEngineTrainingMetrics *trainingMetrics;
@property (readonly, nonatomic) RTLearnedLocationReconcilerPerVisit *reconcilerPerVisit;
@property (readonly, nonatomic) RTLearnedLocationReconcilerPerDevice *reconcilerPerDevice;
@property (readonly, nonatomic) RTSettledStateTransitionStore *settledStateTransitionStore;
@property (readonly, nonatomic) RTTransitMetricManager *transitMetricManager;
@property (readonly, nonatomic) RTVisitManager *visitManager;
@property (readonly, nonatomic) RTXPCActivityManager *xpcActivityManager;
@property (nonatomic) BOOL monitorFingerprints;
@property (weak, nonatomic) id<RTLearnedLocationEngineProtocol> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)init;
- (void).cxx_destruct;
- (void)_setup;
- (void)_unregisterForNotifications;
- (void)_registerForNotifications;
- (void)shutdown;
- (BOOL)_isAuthorized;
- (void)_shutdown;
- (void)setup;
- (void)onDailyMetricsNotification:(id)a0;
- (void)_onDailyMetricsNotification:(id)a0;
- (void)onVisitManagerNotification:(id)a0;
- (void)_onVisitManagerNotification:(id)a0;
- (id)initWithAccountManager:(id)a0 contactsManager:(id)a1 defaultsManager:(id)a2 diagnostics:(id)a3 distanceCalculator:(id)a4 eventManager:(id)a5 fingerprintManager:(id)a6 learnedLocationStore:(id)a7 locationManager:(id)a8 locationStore:(id)a9 mapServiceManager:(id)a10 mapsSupportManager:(id)a11 metricManager:(id)a12 motionActivityManager:(id)a13 platform:(id)a14 portraitManager:(id)a15 reconcilerPerVisit:(id)a16 reconcilerPerDevice:(id)a17 settledStateTransitionStore:(id)a18 transitMetricManager:(id)a19 visitManager:(id)a20 xpcActivityManager:(id)a21;
- (void)trainLocationsOfInterestModelWithHandler:(id /* block */)a0;
- (void)fetchFusionCandidatesForVisit:(id)a0 handler:(id /* block */)a1;
- (void)queryMapItemProvider:(id)a0 options:(id)a1 handler:(id /* block */)a2;
- (void)trainWithHandler:(id /* block */)a0;
- (void)_trainWithHandler:(id /* block */)a0;
- (void)relabelWithHandler:(id /* block */)a0;
- (void)reconcileLearnedLocationsWithHandler:(id /* block */)a0;
- (void)_reconcileLearnedLocationsWithHandler:(id /* block */)a0;
- (void)classifyPlaceTypesWithHandler:(id /* block */)a0;
- (void)_classifyPlaceTypesWithHandler:(id /* block */)a0;
- (void)requestTrainLocationsOfInterestModelWithHandler:(id /* block */)a0;
- (void)performPurgeOfType:(long long)a0 referenceDate:(id)a1 completion:(id /* block */)a2;
- (void)onContactsManagerNotification:(id)a0;
- (void)onMapsSupportManagerNotification:(id)a0;
- (void)_setupXpcActivityTrain;
- (void)_teardownXpcActivityTrain;
- (id)_mapItemProviderForClass:(Class)a0 error:(id *)a1;
- (id)_enabledMapItemProviders;
- (id)_candidatesForVisit:(id)a0 providers:(id)a1 continueOnError:(BOOL)a2 error:(id *)a3;
- (id)_candidatesForInferredMapItems:(id)a0 error:(id *)a1;
- (id)_bestFusedInferredMapItemForVisit:(id)a0 fromCandidates:(id)a1 error:(id *)a2;
- (void)_submitMetricsForVisit:(id)a0 possibleInferredMapItems:(id)a1 selectedInferredMapItem:(id)a2;
- (id)_bestInferredMapItemForVisit:(id)a0 error:(id *)a1;
- (id)_placeForMapItem:(id)a0 error:(id *)a1;
- (id)_updateLearnedPlaceWithISO3166CountryCodeAndSubdivisionCode:(id)a0;
- (void)_harvestVisits:(id)a0 places:(id)a1;
- (id)_filterVisits:(id)a0 lastLearnedVisit:(id)a1;
- (id)_transitionsForVisits:(id)a0 lastLearnedVisit:(id)a1 creationDate:(id)a2;
- (void)_updateUnlabeledVisitsWithPlaceInformation:(id)a0;
- (void)submitVisitSettledStateMetricsForVisits:(id)a0 transitions:(id)a1;
- (id)_visitsFromDate:(id)a0 toDate:(id)a1 error:(id *)a2;
- (BOOL)_processVisits:(id)a0 forLastLearnedVisit:(id)a1 error:(id *)a2;
- (BOOL)_deferTrainingDueToAvailability;
- (BOOL)_deferTrainingDueToRecentResetSync;
- (id)_lastVisitWithError:(id *)a0;
- (void)_trainWithFromDate:(id)a0 ToDate:(id)a1 forLastLearnedVisit:(id)a2 handler:(id /* block */)a3;
- (void)_setupTrainingMetricsFromDate:(id)a0 toDate:(id)a1;
- (void)_logDatabasesWithReason:(id)a0;
- (BOOL)_retrainVisitsWithoutPlaces:(id *)a0;
- (BOOL)_trainVisitsFromDate:(id)a0 toDate:(id)a1 forLastLearnedVisit:(id)a2 error:(id *)a3;
- (BOOL)_trainLocationsOfInterestModelWithError:(id *)a0;
- (BOOL)_removeUnusedMapItems:(id *)a0;
- (void)_teardownTrainingMetrics;
- (BOOL)_deferTrainingLOIsDueToCloudStoreNotChangeSinceLastTrainingDate:(id)a0;
- (void)willBeginTraining;
- (BOOL)_reconcileLearnedLocationsWithError:(id *)a0;
- (void)didFinishTraining;
- (BOOL)_relabelWithError:(id *)a0;
- (BOOL)_classifyPlaceTypes:(id *)a0;
- (void)submitVisitMetrics;
- (BOOL)_consolidateKnownPlaceTypesWithError:(id *)a0;
- (id)calculateMetricsToReplayOldHomeWorkInferenceAlgoWithStartDate:(id)a0 endDate:(id)a1 homeMapItem:(id)a2 workMapItem:(id)a3 locationsOfOthers:(id *)a4 error:(id *)a5;
- (void)calculateNewMetricsAndSubmitAlongWithTheOldMetrics:(id)a0 startDate:(id)a1 endDate:(id)a2 homeMapItem:(id)a3 workMapItem:(id)a4 distanceThresholdArray:(id)a5 locationsOfOthers:(id)a6;
- (void)_requestTrainLocationsOfInterestModelWithHandler:(id /* block */)a0;
- (id)_performPerVisitReconciliationWithError:(id *)a0;
- (id)_performPerDeviceReconiliationWithError:(id *)a0;
- (id)getNearbyCandidatesAroundLocation:(id)a0 distance:(double)a1 loiIdentifierToCoalescedSourceMap:(id)a2 error:(id *)a3;
- (id)extractCandidate:(id)a0 fromNearbyCandidates:(id)a1 extractedCandidate:(id *)a2 error:(id *)a3;
- (id)createRelabeler;
- (id)createRelabelerPersisterWithError:(id *)a0;
- (BOOL)_relabelWithRelabeler:(id)a0 relabelerPersister:(id)a1 error:(id *)a2;
- (id)getRelabeledInferredMapItemForCandidate:(id)a0 relabeler:(id)a1 loiIdentifierToCoalescedSourceMap:(id)a2 submitMetrics:(BOOL)a3 error:(id *)a4;
- (void)_logLocalStoreWithReason:(id)a0;
- (void)_onContactsManagerNotification:(id)a0;
- (void)_onMapsSupportManagerNotification:(id)a0;
- (id)_getDailyVisitMetrics;
- (BOOL)_deferSubmittingLoiMetricsDueToNoTrainingSinceLastSubmission;
- (void)performTransitAnalyticsWithHandler:(id /* block */)a0;
- (void)_submitDailyVisitMetrics;
- (void)onFingerprintManagerNotification:(id)a0;
- (void)_onFingerprintManagerNotification:(id)a0;
- (void)_updateMonitorFingerprintsWithVisit:(id)a0;
- (void)_fetchLatestVisitWithHandler:(id /* block */)a0;
- (BOOL)_purgeWithReferenceDate:(id)a0 error:(id *)a1;
- (void)_logCloudStoreWithReason:(id)a0;
- (void)_harvestFeedbackData;
- (BOOL)_isUpdateLearnedPlaceWithISO3166CountryCodeAndSubdivisionCodeRequired:(id)a0;

@end
