@class RTMapServiceManager, RTLocationManager, RTDaemonClientRegistrarScenarioTrigger, RTMetricManager, RTAccountManager, RTBackgroundInertialOdometryManager, RTVisitConsolidator, RTUserCurationManager, RTLocationStore, RTDeviceLocationPredictor, RTEventModelProvider, RTScenarioTriggerManager, RTVehicleLocationProvider, NSXPCConnection, RTAuthorizationManager, RTLearnedLocationManager, RTDiagnostics, RTDaemonClientRegistrarPredictedContext, RTPurgeManager, RTTimerManager, RTDefaultsManager, RTLearnedLocationStore, RTVehicleStore, RTHealthKitManager, RTContactsManager, RTVisitManager, RTIntermittentGNSSManager, RTWiFiManager, RTPlaceInferenceOptions, RTMotionActivityManager, RTDaemonClientRegistrarGeneratedTripSegments, RTLocationContextManager, RTPredictedContextManager, RTElevationManager, RTEventAgentManager, RTAssetManager, NSMutableDictionary, RTDaemonClientRegistrarVehicleEvent, RTDaemonClientRegistrarRemoteStatus, RTAuthorizedLocationManager, RTPlaceInferenceManager, RTTripSegmentManager, NSObject, NSString, RTHintManager, RTEntitlementProvider, RTTripClusterManager, RTFingerprintManager, RTPeopleDiscoveryProvider;
@protocol OS_dispatch_queue, RTClientListenerProtocol;

@interface RTDaemonClient : NSObject <RTDaemonClientRegistrarVehicleEventProtocol, RTDaemonClientRegistrarScenarioTriggerProtocol, RTDaemonClientRegistrarGeneratedTripSegmentProtocol, RTDaemonClientRegistrarPredictedContextProtocol, RTDaemonClientRegistrarRemoteStatusProtocol, RTDaemonProtocol, NSXPCConnectionDelegate>

@property BOOL enabled;
@property (nonatomic) BOOL supported;
@property (nonatomic) BOOL monitorVisits;
@property (nonatomic) BOOL leechVisits;
@property (nonatomic) BOOL leechLowConfidenceVisits;
@property (nonatomic) BOOL monitorPlaceInferences;
@property (nonatomic) BOOL monitorPredictedContext;
@property (retain, nonatomic) RTPlaceInferenceOptions *placeInferenceOptions;
@property (retain, nonatomic) NSMutableDictionary *restorationData;
@property (retain, nonatomic) RTEntitlementProvider *entitlementProvider;
@property (retain, nonatomic) NSMutableDictionary *vendedClassesStoreManagerDict;
@property (retain, nonatomic) RTDaemonClientRegistrarVehicleEvent *vehicleEventRegistrar;
@property (retain, nonatomic) RTDaemonClientRegistrarScenarioTrigger *scenarioTriggerRegistrar;
@property (retain, nonatomic) RTDaemonClientRegistrarPredictedContext *predictedContextRegistrar;
@property (retain, nonatomic) RTDaemonClientRegistrarRemoteStatus *remoteStatusRegistrar;
@property (retain, nonatomic) RTDaemonClientRegistrarGeneratedTripSegments *generatedTripSegmentsRegistrar;
@property (retain, nonatomic) RTAccountManager *accountManager;
@property (retain, nonatomic) RTAssetManager *assetManager;
@property (retain, nonatomic) RTAuthorizationManager *authorizationManager;
@property (retain, nonatomic) RTBackgroundInertialOdometryManager *backgroundInertialOdometryManager;
@property (retain, nonatomic) RTContactsManager *contactsManager;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTDeviceLocationPredictor *deviceLocationPredictor;
@property (retain, nonatomic) RTDiagnostics *diagnostics;
@property (retain, nonatomic) RTElevationManager *elevationManager;
@property (retain, nonatomic) RTEventAgentManager *eventAgentManager;
@property (retain, nonatomic) RTEventModelProvider *eventModelProvider;
@property (retain, nonatomic) RTFingerprintManager *fingerprintManager;
@property (retain, nonatomic) RTAuthorizedLocationManager *authorizedLocationManager;
@property (retain, nonatomic) RTHealthKitManager *healthKitManager;
@property (retain, nonatomic) RTHintManager *hintManager;
@property (retain, nonatomic) RTIntermittentGNSSManager *intermittentGNSSManager;
@property (retain, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (retain, nonatomic) RTLearnedLocationStore *learnedLocationStore;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) RTLocationContextManager *locationContextManager;
@property (retain, nonatomic) RTLocationStore *locationStore;
@property (retain, nonatomic) RTMapServiceManager *mapServiceManager;
@property (retain, nonatomic) RTMetricManager *metricManager;
@property (retain, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (retain, nonatomic) RTPeopleDiscoveryProvider *peopleDiscoveryProvider;
@property (retain, nonatomic) RTPlaceInferenceManager *placeInferenceManager;
@property (retain, nonatomic) RTPredictedContextManager *predictedContextManager;
@property (retain, nonatomic) RTPurgeManager *purgeManager;
@property (retain, nonatomic) RTScenarioTriggerManager *scenarioTriggerManager;
@property (retain, nonatomic) RTTimerManager *timerManager;
@property (retain, nonatomic) RTVehicleLocationProvider *vehicleLocationProvider;
@property (retain, nonatomic) RTVisitManager *visitManager;
@property (retain, nonatomic) RTTripSegmentManager *tripSegmentManager;
@property (retain, nonatomic) RTUserCurationManager *userCurationManager;
@property (retain, nonatomic) RTVehicleStore *vehicleStore;
@property (retain, nonatomic) RTWiFiManager *wifiManager;
@property (retain, nonatomic) RTTripClusterManager *tripClusterManager;
@property (retain, nonatomic) RTVisitConsolidator *visitConsolidator;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (copy, nonatomic) NSString *executablePath;
@property (copy, nonatomic) NSString *executableName;
@property (nonatomic) int processIdentifier;
@property (copy, nonatomic) NSString *signingIdentifier;
@property (copy, nonatomic) NSString *bundleIdentifier;
@property (retain, nonatomic) NSXPCConnection *xpcConnection;
@property (copy, nonatomic) NSString *restorationIdentifier;
@property (weak, nonatomic) id<RTClientListenerProtocol> clientManagerDelegate;
@property (nonatomic) BOOL targetUserSession;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)filterVisits:(id)a0 executable:(id)a1;

- (void)shutdown;
- (void)removeLocationOfInterestWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)generatedTripSegmentsRegistrar:(id)a0 didReceiveGeneratedTripSegment:(id)a1 withError:(id)a2;
- (void)onLocationContextManagerNotification:(id)a0;
- (void)fetchLookbackWindowStartDateWithLocation:(id)a0 reply:(id /* block */)a1;
- (void)fetchLocationsOfInterestAssociatedToIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)purgeTripClusterWithClusterID:(id)a0 reply:(id /* block */)a1;
- (void)fetchEstimatedLocationAtDate:(id)a0 options:(id)a1 reply:(id /* block */)a2;
- (void)startLeechingLowConfidenceVisitsWithReply:(id /* block */)a0;
- (void)clearRoutineWithReply:(id /* block */)a0;
- (void)fetchAllLocationsOfInterestForSettingsWithReply:(id /* block */)a0;
- (void)updateVehicleEventWithIdentifier:(id)a0 geoMapItem:(id)a1 reply:(id /* block */)a2;
- (void)connection:(id)a0 handleInvocation:(id)a1 isReply:(BOOL)a2;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 customLabel:(id)a1 reply:(id /* block */)a2;
- (void)fetchLastVehicleEventsWithReply:(id /* block */)a0;
- (void)fetchLocationOfInterestWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)startMonitoringVisitsWithReply:(id /* block */)a0;
- (void)startMonitoringPredictedContextWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchLocationsForTripSegmentWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)stopLeechingVisitsWithReply:(id /* block */)a0;
- (void)userInteractionWithPredictedLocationOfInterest:(id)a0 interaction:(unsigned long long)a1 feedback:(id)a2 geoMapItem:(id)a3 reply:(id /* block */)a4;
- (void)startMonitoringVehicleEventsWithReply:(id /* block */)a0;
- (void)restore;
- (void)updateVehicleEventWithIdentifier:(id)a0 notes:(id)a1 reply:(id /* block */)a2;
- (void)fetchPredictedContextWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)launchClient;
- (void)stopMonitoringForGeneratedTripSegmentsWithReply:(id /* block */)a0;
- (void)fetchCloudSyncAuthorizationStateWithReply:(id /* block */)a0;
- (void)startMonitoringPlaceInferencesWithOptions:(id)a0 reply:(id /* block */)a1;
- (BOOL)hasReasonToOutliveClientConnection;
- (void)updateVehicleEventWithIdentifier:(id)a0 photo:(id)a1 reply:(id /* block */)a2;
- (void)fetchPathToDiagnosticFilesWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchTransitionsBetweenStartDate:(id)a0 endDate:(id)a1 reply:(id /* block */)a2;
- (void)removeVisitWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)startMonitoringScenarioTriggerOfType:(unsigned long long)a0 reply:(id /* block */)a1;
- (void)purgeTripClusterTable:(id)a0 reply:(id /* block */)a1;
- (void)stopMonitoringVehicleEventsWithReply:(id /* block */)a0;
- (void)stopMonitoringRemoteStatusWithReply:(id /* block */)a0;
- (void)scenarioTriggerRegistrar:(id)a0 didReceiveScenarioTriggers:(id)a1 error:(id)a2;
- (void)fetchAuthorizedLocationStatus:(id /* block */)a0;
- (void)fetchTripSegmentMetadataWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchPredictedExitDatesFromLocation:(id)a0 onDate:(id)a1 reply:(id /* block */)a2;
- (void)stopMonitoringVisitsWithReply:(id /* block */)a0;
- (id)initWithQueue:(id)a0 restorationData:(id)a1 accountManager:(id)a2 assetManager:(id)a3 authorizationManager:(id)a4 backgroundInertialOdometryManager:(id)a5 contactsManager:(id)a6 defaultsManager:(id)a7 deviceLocationPredictor:(id)a8 diagnostics:(id)a9 elevationManager:(id)a10 eventAgentManager:(id)a11 eventModelProvider:(id)a12 authorizedLocationManager:(id)a13 fingerprintManager:(id)a14 healthKitManager:(id)a15 hintManager:(id)a16 intermittentGNSSManager:(id)a17 learnedLocationManager:(id)a18 learnedLocationStore:(id)a19 locationManager:(id)a20 locationContextManager:(id)a21 locationStore:(id)a22 mapServiceManager:(id)a23 metricManager:(id)a24 motionActivityManager:(id)a25 peopleDiscoveryProvider:(id)a26 placeInferenceManager:(id)a27 predictedContextManager:(id)a28 purgeManager:(id)a29 scenarioTriggerManager:(id)a30 timerManager:(id)a31 tripSegmentManager:(id)a32 userCurationManager:(id)a33 vehicleLocationProvider:(id)a34 vehicleStore:(id)a35 visitManager:(id)a36 wifiManager:(id)a37 tripClusterManager:(id)a38 visitConsolidator:(id)a39;
- (id)_clientIdentity;
- (void)fetchFamiliarityIndexResultsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)startMonitoringRemoteStatusWithReply:(id /* block */)a0;
- (void)updateCloudSyncProvisionedForAccount:(BOOL)a0 reply:(id /* block */)a1;
- (void)fetchEnumerableObjectsWithOptions:(id)a0 offset:(id)a1 reply:(id /* block */)a2;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 mapItemStorage:(id)a1 reply:(id /* block */)a2;
- (void)setHintForRegionState:(long long)a0 significantRegion:(id)a1 reply:(id /* block */)a2;
- (void)fetchTripSegmentsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchRoutineModeFromLocation:(id)a0 reply:(id /* block */)a1;
- (void)fetchStoredVisitsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)predictedContextRegistrar:(id)a0 didReceivePredictedContextResult:(id)a1 error:(id)a2;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 type:(long long)a1 reply:(id /* block */)a2;
- (void)_startMonitoringVehicleEvents;
- (void)addBackgroundInertialOdometrySamples:(id)a0 reply:(id /* block */)a1;
- (void)setRoutineEnabled:(BOOL)a0 reply:(id /* block */)a1;
- (void)engageInVehicleEventWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchDedupedLocationOfInterestIdentifiersWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchTripClusterMetadataWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchLearnedRoutesWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchRoutineEnabledWithReply:(id /* block */)a0;
- (void).cxx_destruct;
- (void)fetchNextPredictedLocationsOfInterestFromLocation:(id)a0 startDate:(id)a1 timeInterval:(double)a2 reply:(id /* block */)a3;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 type:(long long)a1 customLabel:(id)a2 reply:(id /* block */)a3;
- (void)fetchPredictedLocationsOfInterestAssociatedToTitle:(id)a0 location:(id)a1 calendarIdentifier:(id)a2 reply:(id /* block */)a3;
- (void)fetchElevationsWithContext:(id)a0 reply:(id /* block */)a1;
- (void)onVisitManagerNotification:(id)a0;
- (id)_clientIdentifier;
- (void)fetchLocationsCountForTripSegmentWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)startMonitoringForGeneratedTripSegmentsWithReply:(id /* block */)a0;
- (id)init;
- (void)fetchPlaceInferencesWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchElevationsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchFinerGranularityInferredMapItemWithVisitIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchVehiclesWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)startLeechingVisitsWithReply:(id /* block */)a0;
- (void)fetchLocationsOfInterestOfType:(long long)a0 reply:(id /* block */)a1;
- (void)stopLeechingLowConfidenceVisitsWithReply:(id /* block */)a0;
- (void)fetchAutomaticVehicleEventDetectionSupportedWithReply:(id /* block */)a0;
- (void)processHindsightVisitsWithReply:(id /* block */)a0;
- (void)fetchMonitoredScenarioTriggerTypesWithReply:(id /* block */)a0;
- (void)fetchLocationsOfInterestWithinDistance:(double)a0 ofLocation:(id)a1 reply:(id /* block */)a2;
- (void)fetchFormattedPostalAddressesFromMeCard:(id /* block */)a0;
- (void)vehicleEventAtLocation:(id)a0 notes:(id)a1 reply:(id /* block */)a2;
- (void)fetchLocationOfInterestAtLocation:(id)a0 reply:(id /* block */)a1;
- (void)fetchPredictedLocationsOfInterestBetweenStartDate:(id)a0 endDate:(id)a1 reply:(id /* block */)a2;
- (void)addLocationOfInterestOfType:(long long)a0 mapItemStorage:(id)a1 customLabel:(id)a2 reply:(id /* block */)a3;
- (void)extendLifetimeOfVisitsWithIdentifiers:(id)a0 reply:(id /* block */)a1;
- (void)correctLabelForVisitWithIdentifier:(id)a0 entryDate:(id)a1 originalLabel:(id)a2 newLabel:(id)a3 handler:(id /* block */)a4;
- (void)fetchBackgroundInertialOdometrySamplesWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchStoredLocationsWithContext:(id)a0 reply:(id /* block */)a1;
- (void)fetchRemoteStatusWithReply:(id /* block */)a0;
- (void)updateVehicleEventWithIdentifier:(id)a0 location:(id)a1 reply:(id /* block */)a2;
- (void)submitUserCurationForVisitDateRange:(id)a0 newLabel:(id)a1 handler:(id /* block */)a2;
- (void)onAuthorizationNotification:(id)a0;
- (void)stopMonitoringPlaceInferencesWithReply:(id /* block */)a0;
- (void)stopMonitoringScenarioTriggerOfType:(unsigned long long)a0 reply:(id /* block */)a1;
- (void)stopMonitoringPredictedContextWithReply:(id /* block */)a0;
- (void)deleteTripSegmentWithUUID:(id)a0 reply:(id /* block */)a1;
- (void)addElevations:(id)a0 handler:(id /* block */)a1;
- (void)clearAllVehicleEventsWithReply:(id /* block */)a0;
- (void)_onVisitManagerNotification:(id)a0;
- (void)performBluePOIQueryLookingBack:(double)a0 lookingAhead:(double)a1 reply:(id /* block */)a2;
- (void)_onLocationContextManagerNotification:(id)a0;
- (void)fetchLocationsOfInterestVisitedBetweenStartDate:(id)a0 endDate:(id)a1 reply:(id /* block */)a2;
- (void)remoteStatusRegistrar:(id)a0 didReceiveRemoteStatus:(long long)a1 error:(id)a2;
- (void)vehicleEventRegistrar:(id)a0 didReceiveVehicleEvents:(id)a1 error:(id)a2;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 type:(long long)a1 mapItemStorage:(id)a2 customLabel:(id)a3 reply:(id /* block */)a4;
- (void)fetchPredictedLocationsOfInterestOnDate:(id)a0 reply:(id /* block */)a1;
- (void)fetchCurrentPredictedLocationsOfInterestLookingBack:(double)a0 lookingAhead:(double)a1 reply:(id /* block */)a2;
- (void)fetchLocationOfInterestForRegion:(id)a0 reply:(id /* block */)a1;

@end
